# EHRSHOT sequence baseline: numeric-aware embeddings

Цель: взять готовые sequence datasets из предыдущего ноутбука (`raw`, `compressed_dedup`, `compressed_first_last`, `compressed_condition_era`, `compressed_hybrid`) и проверить, помогает ли числовой сигнал (`numeric_values`) внутри sequence-моделей.

Что меняем относительно code-only baseline:

1. `numeric_values` используются в event embedding.
2. Числа нормализуются **по token/code** на train split, чтобы не смешивать разные шкалы лабораторных анализов, дозировок и compression duration.
3. Для GRU/LSTM/RETAIN время кодируется через `Time2Vec`-style encoder.
4. Метрики: AUROC, AUPRC, Brier, LogLoss, top-k lift/event capture.

В code-only sequence baseline каждое событие кодировалось только через `token_id` и временные признаки. В этом ноутбуке event embedding расширен:

```text
event_embedding =
    token_embedding
  + time_embedding(log1p(days_before_prediction), log1p(delta_days))
  + numeric_embedding(z_value, numeric_present)
```

`numeric_value` нормализуется отдельно для каждого token/code по train split. Это нужно, потому что разные коды имеют разные шкалы: лабораторные значения, дозировки, duration у compression tokens и т.д.

## 0. Imports and config

In [1]:
from pathlib import Path
import json
import math
import random
import zipfile
import warnings
from copy import deepcopy

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.metrics import roc_auc_score, average_precision_score, brier_score_loss, log_loss
from sklearn.linear_model import LogisticRegression

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torch.nn.utils.rnn import pack_padded_sequence
from tqdm.auto import tqdm

warnings.filterwarnings("ignore")

RANDOM_STATE = 42
random.seed(RANDOM_STATE)
np.random.seed(RANDOM_STATE)
torch.manual_seed(RANDOM_STATE)

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "mps" if torch.backends.mps.is_available() else "cpu")
print("DEVICE:", DEVICE)

PAD_ID = 0
UNK_ID = 1

DEVICE: mps

## 1. Где лежат готовые sequence datasets

In [2]:
# Если datasets уже лежат рядом с ноутбуком:
USE_LOCAL_SEQUENCE_DATASETS = True
LOCAL_SEQUENCE_DATA_DIR = Path("ehrshot_sequence_datasets")

# Если datasets были загружены как artifact в ClearML:
USE_CLEARML_DOWNLOAD = False
CLEARML_SOURCE_TASK_ID = ""  # например: "84e2aef056324facb0d0dcc12baa9562"
CLEARML_SEQUENCE_ARTIFACT_CANDIDATES = ["sequence_datasets", "sequence_data_dir", "ehrshot_sequence_datasets"]
DOWNLOAD_DIR = Path("clearml_downloads")

RESULTS_DIR = Path("ehrshot_sequence_numeric_results")
CHECKPOINT_DIR = RESULTS_DIR / "checkpoints"
for p in [DOWNLOAD_DIR, RESULTS_DIR, CHECKPOINT_DIR]:
    p.mkdir(parents=True, exist_ok=True)

SELECTED_TASKS = ["guo_readmission", "guo_icu"]
SEQUENCE_VERSIONS = [
    "raw",
    "compressed_dedup",
    "compressed_first_last",
    "compressed_condition_era",
    "compressed_hybrid",
]

DEBUG_RUN = False
if DEBUG_RUN:
    RUN_TASKS = ["guo_readmission"]
    RUN_SEQUENCE_VERSIONS = ["raw", "compressed_dedup"]
    RUN_MODEL_NAMES = ["GRU_1L_numeric", "RETAIN_lite_numeric"]
    MAX_TRAIN_EXAMPLES = 800
    MAX_EVAL_EXAMPLES = 400
    N_EPOCHS = 2
else:
    RUN_TASKS = SELECTED_TASKS
    RUN_SEQUENCE_VERSIONS = SEQUENCE_VERSIONS
    RUN_MODEL_NAMES = [
        "GRU_1L_numeric",
        "GRU_2L_numeric",
        "LSTM_1L_numeric",
        "LSTM_2L_numeric",
        "RETAIN_lite_numeric",
    ]
    MAX_TRAIN_EXAMPLES = None
    MAX_EVAL_EXAMPLES = None
    N_EPOCHS = 12

MAX_LEN = 1024
BATCH_SIZE = 32
LEARNING_RATE = 1e-3
WEIGHT_DECAY = 1e-4
PATIENCE = 3
GRAD_CLIP = 1.0
NUM_WORKERS = 0
SAVE_MODEL_CHECKPOINTS = True

In [3]:
def download_sequence_artifact_from_clearml() -> Path:
    if not CLEARML_SOURCE_TASK_ID:
        raise ValueError("Set CLEARML_SOURCE_TASK_ID before using ClearML download.")
    from clearml import Task
    source_task = Task.get_task(task_id=CLEARML_SOURCE_TASK_ID)
    available = list(source_task.artifacts.keys())
    print("Available artifacts:", available)

    artifact = None
    artifact_name = None
    for name in CLEARML_SEQUENCE_ARTIFACT_CANDIDATES:
        if name in source_task.artifacts:
            artifact = source_task.artifacts[name]
            artifact_name = name
            break
    if artifact is None:
        raise KeyError(f"No sequence artifact found. Available: {available}")

    local_copy = Path(artifact.get_local_copy())
    print(f"Downloaded artifact {artifact_name} to:", local_copy)

    out_dir = DOWNLOAD_DIR / artifact_name
    out_dir.mkdir(parents=True, exist_ok=True)
    if local_copy.is_file() and local_copy.suffix.lower() == ".zip":
        with zipfile.ZipFile(local_copy, "r") as zf:
            zf.extractall(out_dir)
        return out_dir
    if local_copy.is_dir():
        return local_copy
    return local_copy.parent


def looks_like_sequence_root(path: Path) -> bool:
    if not path.exists() or not path.is_dir():
        return False
    for task_name in SELECTED_TASKS:
        for version in SEQUENCE_VERSIONS:
            if (path / task_name / version / "examples.parquet").exists():
                return True
    return False


def find_sequence_dataset_root(base: Path) -> Path:
    candidates = [base, base / "ehrshot_sequence_datasets", base / "sequence_datasets"]
    for c in candidates:
        if looks_like_sequence_root(c):
            return c
    if base.exists():
        for c in base.rglob("examples.parquet"):
            possible_root = c.parent.parent.parent
            if looks_like_sequence_root(possible_root):
                return possible_root
    raise FileNotFoundError(
        f"Could not find sequence dataset root under {base}. Expected: <root>/<task>/<version>/examples.parquet"
    )

if USE_CLEARML_DOWNLOAD:
    SEQUENCE_DATA_DIR = find_sequence_dataset_root(download_sequence_artifact_from_clearml())
elif USE_LOCAL_SEQUENCE_DATASETS:
    SEQUENCE_DATA_DIR = find_sequence_dataset_root(LOCAL_SEQUENCE_DATA_DIR)
else:
    raise ValueError("Set USE_LOCAL_SEQUENCE_DATASETS or USE_CLEARML_DOWNLOAD")

print("SEQUENCE_DATA_DIR:", SEQUENCE_DATA_DIR.resolve())

SEQUENCE_DATA_DIR: /Users/polinakorobeinikova/Практика/ehrshot_sequence_datasets

## 2. Optional ClearML tracking

In [4]:
ENABLE_CLEARML = False
CLEARML_PROJECT = "EHR_Risk_Profiling/EHRSHOT"
CLEARML_TASK_NAME = "sequence_numeric_time_notebook_v1"
CLEARML_OUTPUT_URI = "s3://api.blackhole2.ai.innopolis.university:443/pershin-medailab"

task = None
if ENABLE_CLEARML:
    from clearml import Task
    task = Task.init(
        project_name=CLEARML_PROJECT,
        task_name=CLEARML_TASK_NAME,
        output_uri=CLEARML_OUTPUT_URI,
    )
    task.connect({
        "run_tasks": RUN_TASKS,
        "run_sequence_versions": RUN_SEQUENCE_VERSIONS,
        "run_model_names": RUN_MODEL_NAMES,
        "max_len": MAX_LEN,
        "batch_size": BATCH_SIZE,
        "n_epochs": N_EPOCHS,
        "debug_run": DEBUG_RUN,
    })

## 3. Load data helpers

In [5]:
def load_sequence_examples(task_name: str, version: str) -> pd.DataFrame:
    path = SEQUENCE_DATA_DIR / task_name / version / "examples.parquet"
    if not path.exists():
        raise FileNotFoundError(path)
    return pd.read_parquet(path)


def load_vocab(task_name: str, version: str) -> dict[str, int]:
    path = SEQUENCE_DATA_DIR / task_name / version / "vocab.json"
    if not path.exists():
        raise FileNotFoundError(path)
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def to_plain_list(x):
    if isinstance(x, list):
        return x
    if isinstance(x, np.ndarray):
        return x.tolist()
    if x is None:
        return []
    if isinstance(x, float) and math.isnan(x):
        return []
    return list(x) if hasattr(x, "__iter__") and not isinstance(x, str) else []

rows = []
for task_name in SELECTED_TASKS:
    for version in SEQUENCE_VERSIONS:
        p = SEQUENCE_DATA_DIR / task_name / version / "examples.parquet"
        rows.append({"task": task_name, "version": version, "exists": p.exists(), "path": str(p)})
available_df = pd.DataFrame(rows)
display(available_df)
assert available_df["exists"].all(), "Some sequence datasets are missing"

,task,version,exists,path
0,guo_readmission,raw,True,ehrshot_sequence_datasets/guo_readmission/raw/...
1,guo_readmission,compressed_dedup,True,ehrshot_sequence_datasets/guo_readmission/comp...
2,guo_readmission,compressed_first_last,True,ehrshot_sequence_datasets/guo_readmission/comp...
3,guo_readmission,compressed_condition_era,True,ehrshot_sequence_datasets/guo_readmission/comp...
4,guo_readmission,compressed_hybrid,True,ehrshot_sequence_datasets/guo_readmission/comp...
5,guo_icu,raw,True,ehrshot_sequence_datasets/guo_icu/raw/examples...
6,guo_icu,compressed_dedup,True,ehrshot_sequence_datasets/guo_icu/compressed_d...
7,guo_icu,compressed_first_last,True,ehrshot_sequence_datasets/guo_icu/compressed_f...
8,guo_icu,compressed_condition_era,True,ehrshot_sequence_datasets/guo_icu/compressed_c...
9,guo_icu,compressed_hybrid,True,ehrshot_sequence_datasets/guo_icu/compressed_h...

## 4. Numeric coverage and sequence length audit

In [6]:
def numeric_coverage_for_df(df: pd.DataFrame) -> dict:
    total_events = 0
    numeric_events = 0
    seq_lens = []
    for _, row in df.iterrows():
        nums = to_plain_list(row.get("numeric_values", []))
        toks = to_plain_list(row.get("token_ids", []))
        total_events += len(toks)
        seq_lens.append(len(toks))
        if len(nums) < len(toks):
            nums = nums + [np.nan] * (len(toks) - len(nums))
        for v in nums[:len(toks)]:
            try:
                if np.isfinite(float(v)):
                    numeric_events += 1
            except Exception:
                pass
    return {
        "n_examples": len(df),
        "total_events": total_events,
        "numeric_events": numeric_events,
        "numeric_event_share": numeric_events / total_events if total_events else np.nan,
        "mean_seq_len": float(np.mean(seq_lens)) if seq_lens else np.nan,
        "median_seq_len": float(np.median(seq_lens)) if seq_lens else np.nan,
        "p90_seq_len": float(np.quantile(seq_lens, 0.90)) if seq_lens else np.nan,
    }

coverage_rows = []
for task_name in SELECTED_TASKS:
    for version in SEQUENCE_VERSIONS:
        df = load_sequence_examples(task_name, version)
        for split, part in df.groupby("split"):
            row = numeric_coverage_for_df(part)
            row.update({"task": task_name, "version": version, "split": split, "event_rate": part["label"].mean()})
            coverage_rows.append(row)

numeric_coverage_df = pd.DataFrame(coverage_rows)
display(numeric_coverage_df.sort_values(["task", "version", "split"]))
numeric_coverage_df.to_csv(RESULTS_DIR / "numeric_coverage_sequence_length.csv", index=False)

,n_examples,total_events,numeric_events,numeric_event_share,mean_seq_len,median_seq_len,p90_seq_len,task,version,split,event_rate
24,2037,13136807,9238389,0.703245,6449.095238,3005.0,17397.4,guo_icu,compressed_condition_era,held_out,0.041728
25,2402,17505331,12243042,0.699389,7287.814738,3221.0,18927.0,guo_icu,compressed_condition_era,train,0.047044
26,2052,12345739,8776934,0.710928,6016.442008,2873.0,15211.3,guo_icu,compressed_condition_era,tuning,0.044834
18,2037,13243822,9227538,0.696743,6501.630830,3026.0,17489.4,guo_icu,compressed_dedup,held_out,0.041728
19,2402,17672592,12228257,0.691933,7357.448793,3261.5,18998.5,guo_icu,compressed_dedup,train,0.047044
20,2052,12452316,8765767,0.703947,6068.380117,2901.0,15416.9,guo_icu,compressed_dedup,tuning,0.044834
21,2037,13135868,9227538,0.702469,6448.634266,3005.0,17397.4,guo_icu,compressed_first_last,held_out,0.041728
22,2402,17503990,12228257,0.698598,7287.256453,3220.0,18926.9,guo_icu,compressed_first_last,train,0.047044
23,2052,12344778,8765767,0.710079,6015.973684,2873.0,15211.2,guo_icu,compressed_first_last,tuning,0.044834
27,2037,13135868,9238389,0.703295,6448.634266,3005.0,17397.4,guo_icu,compressed_hybrid,held_out,0.041728
28,2402,17503990,12243042,0.699443,7287.256453,3220.0,18926.9,guo_icu,compressed_hybrid,train,0.047044
29,2052,12344778,8776934,0.710984,6015.973684,2873.0,15211.2,guo_icu,compressed_hybrid,tuning,0.044834
15,2037,13272055,9227538,0.695261,6515.490918,3037.0,17538.0,guo_icu,raw,held_out,0.041728
16,2402,17709742,12228257,0.690482,7372.915071,3263.5,19017.1,guo_icu,raw,train,0.047044
17,2052,12472942,8765767,0.702783,6078.431774,2903.0,15444.1,guo_icu,raw,tuning,0.044834
9,2189,17612368,12606646,0.715784,8045.851074,4567.0,20268.8,guo_readmission,compressed_condition_era,held_out,0.118776
10,2608,24112895,17175138,0.712280,9245.741948,4827.5,23140.4,guo_readmission,compressed_condition_era,train,0.141871
11,2206,17119373,12424509,0.725757,7760.368540,4290.5,18988.5,guo_readmission,compressed_condition_era,tuning,0.127380
3,2189,17740545,12593382,0.709864,8104.406122,4583.0,20351.4,guo_readmission,compressed_dedup,held_out,0.118776
4,2608,24300286,17157384,0.706057,9317.594325,4842.0,23200.5,guo_readmission,compressed_dedup,train,0.141871
5,2206,17243630,12410985,0.719743,7816.695376,4320.5,19209.0,guo_readmission,compressed_dedup,tuning,0.127380
6,2189,17610980,12593382,0.715087,8045.216994,4567.0,20268.0,guo_readmission,compressed_first_last,held_out,0.118776
7,2608,24110893,17157384,0.711603,9244.974310,4827.0,23140.4,guo_readmission,compressed_first_last,train,0.141871
8,2206,17117944,12410985,0.725028,7759.720762,4288.0,18986.5,guo_readmission,compressed_first_last,tuning,0.127380
12,2189,17610980,12606646,0.715840,8045.216994,4567.0,20268.0,guo_readmission,compressed_hybrid,held_out,0.118776
13,2608,24110893,17175138,0.712339,9244.974310,4827.0,23140.4,guo_readmission,compressed_hybrid,train,0.141871
14,2206,17117944,12424509,0.725818,7759.720762,4288.0,18986.5,guo_readmission,compressed_hybrid,tuning,0.127380
0,2189,17778306,12593382,0.708357,8121.656464,4588.0,20492.8,guo_readmission,raw,held_out,0.118776
1,2608,24358302,17157384,0.704375,9339.839724,4847.0,23226.2,guo_readmission,raw,train,0.141871
2,2206,17272718,12410985,0.718531,7829.881233,4328.0,19241.0,guo_readmission,raw,tuning,0.127380

## 5. Token-specific numeric normalization

`numeric_value` нельзя подавать raw без нормализации: разные коды живут в разных шкалах. Поэтому считаем mean/std по `token_id` на train split, а в модель подаем `[z_value, numeric_present]`.

In [7]:
def compute_token_numeric_stats(df_train: pd.DataFrame, vocab_size: int, min_count: int = 3):
    count = np.zeros(vocab_size, dtype=np.float64)
    sum_x = np.zeros(vocab_size, dtype=np.float64)
    sum_x2 = np.zeros(vocab_size, dtype=np.float64)

    for _, row in tqdm(df_train.iterrows(), total=len(df_train), desc="numeric stats"):
        tokens = to_plain_list(row["token_ids"])
        nums = to_plain_list(row.get("numeric_values", []))
        if len(nums) < len(tokens):
            nums = nums + [np.nan] * (len(tokens) - len(nums))
        for token_id, value in zip(tokens, nums):
            token_id = int(token_id)
            if token_id < 0 or token_id >= vocab_size:
                continue
            try:
                x = float(value)
            except Exception:
                continue
            if not np.isfinite(x):
                continue
            count[token_id] += 1
            sum_x[token_id] += x
            sum_x2[token_id] += x * x

    mean = np.zeros(vocab_size, dtype=np.float32)
    std = np.ones(vocab_size, dtype=np.float32)
    valid = count >= min_count
    mean[valid] = (sum_x[valid] / count[valid]).astype(np.float32)
    var = (sum_x2[valid] / count[valid]) - mean[valid] ** 2
    std[valid] = np.sqrt(np.maximum(var, 1e-6)).astype(np.float32)

    stats_df = pd.DataFrame({
        "token_id": np.arange(vocab_size),
        "numeric_count_train": count.astype(int),
        "numeric_mean_train": mean,
        "numeric_std_train": std,
        "has_enough_numeric_stats": valid,
    })
    return mean, std, stats_df

## 6. Dataset and collate

In [8]:
class EHRSequenceNumericDataset(Dataset):
    def __init__(self, df: pd.DataFrame, max_len: int = MAX_LEN):
        self.df = df.reset_index(drop=True)
        self.max_len = max_len

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        token_ids = to_plain_list(row["token_ids"])
        days_before = to_plain_list(row["days_before_prediction"])
        delta_days = to_plain_list(row["delta_days"])
        numeric_values = to_plain_list(row.get("numeric_values", []))

        if len(token_ids) == 0:
            token_ids = [UNK_ID]
            days_before = [0.0]
            delta_days = [0.0]
            numeric_values = [np.nan]

        n = len(token_ids)
        if len(days_before) < n:
            days_before += [0.0] * (n - len(days_before))
        if len(delta_days) < n:
            delta_days += [0.0] * (n - len(delta_days))
        if len(numeric_values) < n:
            numeric_values += [np.nan] * (n - len(numeric_values))

        return {
            "row_id": int(row["row_id"]),
            "subject_id": int(row["subject_id"]),
            "tokens": token_ids[-self.max_len:],
            "days_before": days_before[-self.max_len:],
            "delta_days": delta_days[-self.max_len:],
            "numeric_values": numeric_values[-self.max_len:],
            "label": int(row["label"]),
        }


def make_numeric_collate_fn(token_numeric_mean: np.ndarray, token_numeric_std: np.ndarray):
    mean_t = torch.tensor(token_numeric_mean, dtype=torch.float32)
    std_t = torch.tensor(token_numeric_std, dtype=torch.float32)

    def collate(batch):
        batch_size = len(batch)
        lengths = torch.tensor([len(x["tokens"]) for x in batch], dtype=torch.long)
        max_len = int(lengths.max().item())

        tokens = torch.full((batch_size, max_len), PAD_ID, dtype=torch.long)
        time_features = torch.zeros((batch_size, max_len, 2), dtype=torch.float32)
        numeric_features = torch.zeros((batch_size, max_len, 2), dtype=torch.float32)
        mask = torch.zeros((batch_size, max_len), dtype=torch.bool)
        labels = torch.tensor([x["label"] for x in batch], dtype=torch.float32)
        row_ids = torch.tensor([x["row_id"] for x in batch], dtype=torch.long)
        subject_ids = torch.tensor([x["subject_id"] for x in batch], dtype=torch.long)

        for i, item in enumerate(batch):
            l = len(item["tokens"])
            tok = torch.tensor(item["tokens"], dtype=torch.long)
            tokens[i, :l] = tok
            mask[i, :l] = True

            days_before = torch.tensor(item["days_before"], dtype=torch.float32).clamp(min=0)
            delta_days = torch.tensor(item["delta_days"], dtype=torch.float32).clamp(min=0)
            time_features[i, :l, 0] = torch.log1p(days_before)
            time_features[i, :l, 1] = torch.log1p(delta_days)

            raw_nums, present = [], []
            for v in item["numeric_values"]:
                try:
                    x = float(v)
                    ok = np.isfinite(x)
                except Exception:
                    x, ok = 0.0, False
                raw_nums.append(x if ok else 0.0)
                present.append(1.0 if ok else 0.0)

            raw_nums = torch.tensor(raw_nums, dtype=torch.float32)
            present = torch.tensor(present, dtype=torch.float32)
            m = mean_t[tok]
            s = std_t[tok].clamp(min=1e-6)
            z = ((raw_nums - m) / s).clamp(min=-10.0, max=10.0)
            z = torch.where(present > 0, z, torch.zeros_like(z))

            numeric_features[i, :l, 0] = z
            numeric_features[i, :l, 1] = present

        return {
            "tokens": tokens,
            "time_features": time_features,
            "numeric_features": numeric_features,
            "mask": mask,
            "lengths": lengths,
            "labels": labels,
            "row_ids": row_ids,
            "subject_ids": subject_ids,
        }
    return collate


def maybe_subsample(df: pd.DataFrame, max_examples: int | None):
    if max_examples is None or len(df) <= max_examples:
        return df
    return df.sample(n=max_examples, random_state=RANDOM_STATE).reset_index(drop=True)


def make_loaders(df: pd.DataFrame, token_numeric_mean: np.ndarray, token_numeric_std: np.ndarray):
    split_dfs = {}
    for split in ["train", "tuning", "held_out"]:
        part = df[df["split"] == split].copy().reset_index(drop=True)
        part = maybe_subsample(part, MAX_TRAIN_EXAMPLES if split == "train" else MAX_EVAL_EXAMPLES)
        split_dfs[split] = part

    collate_fn = make_numeric_collate_fn(token_numeric_mean, token_numeric_std)
    loaders = {
        split: DataLoader(
            EHRSequenceNumericDataset(part, max_len=MAX_LEN),
            batch_size=BATCH_SIZE,
            shuffle=(split == "train"),
            num_workers=NUM_WORKERS,
            collate_fn=collate_fn,
        )
        for split, part in split_dfs.items()
    }
    return loaders, split_dfs

## 7. Model components: numeric embedding + Time2Vec

In [9]:
class Time2VecEncoder(nn.Module):
    def __init__(self, input_dim: int = 2, out_dim: int = 64):
        super().__init__()
        linear_dim = max(1, out_dim // 2)
        periodic_dim = out_dim - linear_dim
        self.linear = nn.Linear(input_dim, linear_dim)
        self.periodic = nn.Linear(input_dim, periodic_dim) if periodic_dim > 0 else None

    def forward(self, x):
        parts = [self.linear(x)]
        if self.periodic is not None:
            parts.append(torch.sin(self.periodic(x)))
        return torch.cat(parts, dim=-1)


class EventEmbeddingNumeric(nn.Module):
    def __init__(self, vocab_size: int, emb_dim: int = 64, dropout: float = 0.20):
        super().__init__()
        self.token_emb = nn.Embedding(vocab_size, emb_dim, padding_idx=PAD_ID)
        self.time_proj = Time2VecEncoder(input_dim=2, out_dim=emb_dim)
        self.numeric_proj = nn.Sequential(nn.Linear(2, emb_dim), nn.GELU(), nn.LayerNorm(emb_dim))
        self.norm = nn.LayerNorm(emb_dim)
        self.dropout = nn.Dropout(dropout)

    def forward(self, tokens, time_features, numeric_features):
        x = self.token_emb(tokens) + self.time_proj(time_features) + self.numeric_proj(numeric_features)
        return self.dropout(self.norm(x))


def reverse_by_lengths(x, lengths):
    out = x.clone()
    for i, l in enumerate(lengths.tolist()):
        out[i, :l] = torch.flip(x[i, :l], dims=[0])
    return out

In [10]:
class RNNNumericClassifier(nn.Module):
    def __init__(self, vocab_size: int, rnn_type: str = "GRU", emb_dim: int = 64, hidden_dim: int = 128, num_layers: int = 1, dropout: float = 0.20):
        super().__init__()
        self.model_config = {"model_class": "RNNNumericClassifier", "rnn_type": rnn_type, "emb_dim": emb_dim, "hidden_dim": hidden_dim, "num_layers": num_layers, "dropout": dropout}
        self.event_emb = EventEmbeddingNumeric(vocab_size, emb_dim, dropout=dropout)
        rnn_cls = nn.GRU if rnn_type == "GRU" else nn.LSTM
        self.rnn = rnn_cls(emb_dim, hidden_dim, num_layers=num_layers, dropout=dropout if num_layers > 1 else 0.0, batch_first=True)
        self.head = nn.Sequential(nn.LayerNorm(hidden_dim), nn.Dropout(dropout), nn.Linear(hidden_dim, 1))

    def forward(self, tokens, time_features, numeric_features, mask, lengths):
        x = self.event_emb(tokens, time_features, numeric_features)
        packed = pack_padded_sequence(x, lengths.cpu(), batch_first=True, enforce_sorted=False)
        _, h = self.rnn(packed)
        if isinstance(h, tuple):
            h = h[0]
        return self.head(h[-1]).squeeze(-1)


class RetainLiteNumericClassifier(nn.Module):
    def __init__(self, vocab_size: int, emb_dim: int = 64, hidden_dim: int = 128, dropout: float = 0.20):
        super().__init__()
        self.model_config = {"model_class": "RetainLiteNumericClassifier", "emb_dim": emb_dim, "hidden_dim": hidden_dim, "dropout": dropout}
        self.event_emb = EventEmbeddingNumeric(vocab_size, emb_dim, dropout=dropout)
        self.alpha_gru = nn.GRU(emb_dim, hidden_dim, batch_first=True)
        self.beta_gru = nn.GRU(emb_dim, hidden_dim, batch_first=True)
        self.alpha_fc = nn.Linear(hidden_dim, 1)
        self.beta_fc = nn.Linear(hidden_dim, emb_dim)
        self.head = nn.Sequential(nn.LayerNorm(emb_dim), nn.Dropout(dropout), nn.Linear(emb_dim, 1))

    def forward(self, tokens, time_features, numeric_features, mask, lengths):
        x = self.event_emb(tokens, time_features, numeric_features)
        x_rev = reverse_by_lengths(x, lengths)
        mask_rev = reverse_by_lengths(mask.unsqueeze(-1).float(), lengths).squeeze(-1).bool()
        alpha_h, _ = self.alpha_gru(x_rev)
        beta_h, _ = self.beta_gru(x_rev)
        alpha_logits = self.alpha_fc(alpha_h).squeeze(-1).masked_fill(~mask_rev, -1e9)
        alpha = torch.softmax(alpha_logits, dim=1)
        beta = torch.tanh(self.beta_fc(beta_h))
        context = torch.sum(alpha.unsqueeze(-1) * beta * x_rev, dim=1)
        return self.head(context).squeeze(-1)

In [11]:
def make_model_zoo(vocab_size: int) -> dict[str, nn.Module]:
    return {
        "GRU_1L_numeric": RNNNumericClassifier(vocab_size, rnn_type="GRU", num_layers=1),
        "GRU_2L_numeric": RNNNumericClassifier(vocab_size, rnn_type="GRU", num_layers=2),
        "LSTM_1L_numeric": RNNNumericClassifier(vocab_size, rnn_type="LSTM", num_layers=1),
        "LSTM_2L_numeric": RNNNumericClassifier(vocab_size, rnn_type="LSTM", num_layers=2),
        "RETAIN_lite_numeric": RetainLiteNumericClassifier(vocab_size),
    }

## 8. Training and evaluation

In [12]:
def sigmoid_np(x):
    x = np.asarray(x, dtype=float)
    return 1 / (1 + np.exp(-x))


def compute_ranking_metrics(y_true, y_prob) -> dict:
    y_true = np.asarray(y_true).astype(int)
    y_prob = np.asarray(y_prob).astype(float)
    return {
        "auroc": roc_auc_score(y_true, y_prob) if len(np.unique(y_true)) > 1 else np.nan,
        "auprc": average_precision_score(y_true, y_prob) if len(np.unique(y_true)) > 1 else np.nan,
        "brier": brier_score_loss(y_true, y_prob),
        "logloss": log_loss(y_true, np.clip(y_prob, 1e-6, 1 - 1e-6), labels=[0, 1]),
        "event_rate": float(y_true.mean()),
        "n": int(len(y_true)),
        "n_positive": int(y_true.sum()),
    }


def compute_topk_metrics(y_true, y_prob, top_fracs=(0.01, 0.05, 0.10, 0.20)) -> pd.DataFrame:
    y_true = np.asarray(y_true).astype(int)
    y_prob = np.asarray(y_prob).astype(float)
    n = len(y_true)
    n_pos = int(y_true.sum())
    base_rate = float(y_true.mean()) if n else np.nan
    order = np.argsort(-y_prob)
    rows = []
    for frac in top_fracs:
        k = max(1, int(np.ceil(n * frac)))
        idx = order[:k]
        selected_events = int(y_true[idx].sum())
        event_rate = selected_events / k
        rows.append({
            "top_frac": frac,
            "top_k": k,
            "events_in_top_k": selected_events,
            "top_k_event_rate": event_rate,
            "top_k_lift": event_rate / base_rate if base_rate > 0 else np.nan,
            "event_capture": selected_events / n_pos if n_pos > 0 else np.nan,
            "base_event_rate": base_rate,
            "n": n,
            "n_positive": n_pos,
        })
    return pd.DataFrame(rows)


def run_inference(model, loader):
    model.eval()
    all_logits, all_y, all_row_ids, all_subject_ids = [], [], [], []
    with torch.no_grad():
        for batch in loader:
            tokens = batch["tokens"].to(DEVICE)
            time_features = batch["time_features"].to(DEVICE)
            numeric_features = batch["numeric_features"].to(DEVICE)
            mask = batch["mask"].to(DEVICE)
            lengths = batch["lengths"].to(DEVICE)
            logits = model(tokens, time_features, numeric_features, mask, lengths)
            all_logits.append(logits.detach().cpu().numpy())
            all_y.append(batch["labels"].numpy())
            all_row_ids.append(batch["row_ids"].numpy())
            all_subject_ids.append(batch["subject_ids"].numpy())
    return {
        "logits": np.concatenate(all_logits),
        "y": np.concatenate(all_y).astype(int),
        "row_id": np.concatenate(all_row_ids).astype(int),
        "subject_id": np.concatenate(all_subject_ids).astype(int),
    }

In [13]:
def train_sequence_model(model, loaders):
    model = model.to(DEVICE)
    train_labels = []
    for batch in loaders["train"]:
        train_labels.append(batch["labels"].numpy())
    train_labels = np.concatenate(train_labels)
    n_pos = int(train_labels.sum())
    n_neg = int(len(train_labels) - n_pos)
    pos_weight = torch.tensor([n_neg / max(n_pos, 1)], dtype=torch.float32, device=DEVICE)

    criterion = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
    optimizer = torch.optim.AdamW(model.parameters(), lr=LEARNING_RATE, weight_decay=WEIGHT_DECAY)

    history = []
    best_state = None
    best_tuning_auprc = -np.inf
    bad_epochs = 0

    for epoch in range(1, N_EPOCHS + 1):
        model.train()
        total_loss = 0.0
        n_batches = 0
        for batch in tqdm(loaders["train"], desc=f"epoch {epoch}"):
            optimizer.zero_grad()
            tokens = batch["tokens"].to(DEVICE)
            time_features = batch["time_features"].to(DEVICE)
            numeric_features = batch["numeric_features"].to(DEVICE)
            mask = batch["mask"].to(DEVICE)
            lengths = batch["lengths"].to(DEVICE)
            labels = batch["labels"].to(DEVICE)
            logits = model(tokens, time_features, numeric_features, mask, lengths)
            loss = criterion(logits, labels)
            loss.backward()
            nn.utils.clip_grad_norm_(model.parameters(), GRAD_CLIP)
            optimizer.step()
            total_loss += float(loss.detach().cpu().item())
            n_batches += 1

        tuning_pred = run_inference(model, loaders["tuning"])
        tuning_prob = sigmoid_np(tuning_pred["logits"])
        tuning_metrics = compute_ranking_metrics(tuning_pred["y"], tuning_prob)
        row = {
            "epoch": epoch,
            "train_loss": total_loss / max(n_batches, 1),
            "tuning_auroc": tuning_metrics["auroc"],
            "tuning_auprc": tuning_metrics["auprc"],
            "tuning_brier": tuning_metrics["brier"],
            "tuning_logloss": tuning_metrics["logloss"],
        }
        history.append(row)
        print(row)

        if tuning_metrics["auprc"] > best_tuning_auprc:
            best_tuning_auprc = tuning_metrics["auprc"]
            best_state = deepcopy(model.state_dict())
            bad_epochs = 0
        else:
            bad_epochs += 1
            if bad_epochs >= PATIENCE:
                print(f"Early stopping at epoch {epoch}")
                break

    if best_state is not None:
        model.load_state_dict(best_state)
    return model, pd.DataFrame(history)

In [14]:
def evaluate_model_with_calibration(task_name, version, model_name, model, loaders):
    tuning = run_inference(model, loaders["tuning"])
    heldout = run_inference(model, loaders["held_out"])
    rows, pred_tables, topk_tables = [], [], []

    probs = {"raw": sigmoid_np(heldout["logits"])}
    try:
        calibrator = LogisticRegression(solver="lbfgs")
        calibrator.fit(tuning["logits"].reshape(-1, 1), tuning["y"])
        probs["platt"] = calibrator.predict_proba(heldout["logits"].reshape(-1, 1))[:, 1]
    except Exception as e:
        print("Platt calibration failed:", repr(e))

    for calibration, held_prob in probs.items():
        m = compute_ranking_metrics(heldout["y"], held_prob)
        rows.append({
            "task": task_name,
            "version": version,
            "model": model_name,
            "calibration": calibration,
            "n_tuning": int(len(tuning["y"])),
            "n_heldout": int(len(heldout["y"])),
            "n_positive_heldout": int(heldout["y"].sum()),
            "event_rate_heldout": float(heldout["y"].mean()),
            "heldout_auroc": m["auroc"],
            "heldout_auprc": m["auprc"],
            "heldout_brier": m["brier"],
            "heldout_logloss": m["logloss"],
        })
        pred_tables.append(pd.DataFrame({
            "task": task_name,
            "version": version,
            "model": model_name,
            "calibration": calibration,
            "row_id": heldout["row_id"],
            "subject_id": heldout["subject_id"],
            "y_true": heldout["y"],
            "risk": held_prob,
            "logit": heldout["logits"],
        }))
        tk = compute_topk_metrics(heldout["y"], held_prob)
        tk.insert(0, "calibration", calibration)
        tk.insert(0, "model", model_name)
        tk.insert(0, "version", version)
        tk.insert(0, "task", task_name)
        topk_tables.append(tk)

    return pd.DataFrame(rows), pd.concat(pred_tables, ignore_index=True), pd.concat(topk_tables, ignore_index=True)

## 9. Run experiments

In [15]:
def run_one_experiment(task_name: str, version: str, model_name: str):
    print("\n" + "=" * 100)
    print(f"Experiment: {task_name} | {version} | {model_name}")

    df = load_sequence_examples(task_name, version)
    vocab = load_vocab(task_name, version)
    vocab_size = len(vocab)

    df_train_full = df[df["split"] == "train"].copy().reset_index(drop=True)
    token_mean, token_std, token_stats_df = compute_token_numeric_stats(df_train_full, vocab_size=vocab_size)

    loaders, split_dfs = make_loaders(df, token_mean, token_std)
    model = make_model_zoo(vocab_size)[model_name]

    model, history_df = train_sequence_model(model, loaders)
    result_df, pred_df, topk_df = evaluate_model_with_calibration(task_name, version, model_name, model, loaders)

    exp_name = f"{task_name}__{version}__{model_name}"
    history_df.to_csv(RESULTS_DIR / f"{exp_name}__history.csv", index=False)
    pred_df.to_csv(RESULTS_DIR / f"{exp_name}__heldout_predictions.csv", index=False)
    topk_df.to_csv(RESULTS_DIR / f"{exp_name}__topk.csv", index=False)
    token_stats_df.to_csv(RESULTS_DIR / f"{exp_name}__token_numeric_stats.csv", index=False)

    if SAVE_MODEL_CHECKPOINTS:
        ckpt_path = CHECKPOINT_DIR / f"{exp_name}.pt"
        torch.save({
            "task": task_name,
            "version": version,
            "model_name": model_name,
            "vocab_size": vocab_size,
            "max_len": MAX_LEN,
            "model_config": getattr(model, "model_config", {}),
            "token_numeric_mean": token_mean,
            "token_numeric_std": token_std,
            "state_dict": model.state_dict(),
        }, ckpt_path)

    display(result_df[["task", "version", "model", "calibration", "heldout_auroc", "heldout_auprc", "heldout_brier", "heldout_logloss"]])
    display(topk_df[topk_df["calibration"] == "platt"] if "platt" in topk_df["calibration"].values else topk_df)
    return result_df, pred_df, topk_df, history_df

all_result_tables, all_prediction_tables, all_topk_tables, all_history_tables = [], [], [], []

for task_name in RUN_TASKS:
    for version in RUN_SEQUENCE_VERSIONS:
        for model_name in RUN_MODEL_NAMES:
            result_df, pred_df, topk_df, history_df = run_one_experiment(task_name, version, model_name)
            all_result_tables.append(result_df)
            all_prediction_tables.append(pred_df)
            all_topk_tables.append(topk_df)
            history_df = history_df.copy()
            history_df["task"] = task_name
            history_df["version"] = version
            history_df["model"] = model_name
            all_history_tables.append(history_df)

sequence_numeric_results_df = pd.concat(all_result_tables, ignore_index=True)
sequence_numeric_predictions_df = pd.concat(all_prediction_tables, ignore_index=True)
sequence_numeric_topk_df = pd.concat(all_topk_tables, ignore_index=True)
sequence_numeric_history_df = pd.concat(all_history_tables, ignore_index=True)

sequence_numeric_results_df.to_csv(RESULTS_DIR / "sequence_numeric_results.csv", index=False)
sequence_numeric_predictions_df.to_csv(RESULTS_DIR / "sequence_numeric_heldout_predictions.csv", index=False)
sequence_numeric_topk_df.to_csv(RESULTS_DIR / "sequence_numeric_topk_risk_stratification.csv", index=False)
sequence_numeric_history_df.to_csv(RESULTS_DIR / "sequence_numeric_training_history.csv", index=False)

display(sequence_numeric_results_df.sort_values(["task", "heldout_auprc"], ascending=[True, False]))

====================================================================================================
Experiment: guo_readmission | raw | GRU_1L_numeric

numeric stats:   0%|          | 0/2608 [00:00<?, ?it/s]

epoch 1:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 1, 'train_loss': 1.227457293649999, 'tuning_auroc': np.float64(0.6571613439940842), 'tuning_auprc': np.float64(0.24259363702284736), 'tuning_brier': np.float64(0.31054664393093645), 'tuning_logloss': 0.8183455709529407}

epoch 2:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 2, 'train_loss': 1.1096758798855106, 'tuning_auroc': np.float64(0.6975717520913252), 'tuning_auprc': np.float64(0.29606848921680967), 'tuning_brier': np.float64(0.25853122932538236), 'tuning_logloss': 0.7220422034981215}

epoch 3:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 3, 'train_loss': 1.0206512467163364, 'tuning_auroc': np.float64(0.7056375652816934), 'tuning_auprc': np.float64(0.3116810539532738), 'tuning_brier': np.float64(0.16168879543488876), 'tuning_logloss': 0.4986123585079139}

epoch 4:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 4, 'train_loss': 0.9098627029395685, 'tuning_auroc': np.float64(0.7035078800203355), 'tuning_auprc': np.float64(0.3083295986821202), 'tuning_brier': np.float64(0.13844107397784047), 'tuning_logloss': 0.43888861768215326}

epoch 5:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 5, 'train_loss': 0.8717696735771691, 'tuning_auroc': np.float64(0.7063437629985673), 'tuning_auprc': np.float64(0.30903762579485666), 'tuning_brier': np.float64(0.11507825544116232), 'tuning_logloss': 0.38007614289488995}

epoch 6:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 6, 'train_loss': 0.8248682854379096, 'tuning_auroc': np.float64(0.6999787401210888), 'tuning_auprc': np.float64(0.30745514532845225), 'tuning_brier': np.float64(0.1752843651490472), 'tuning_logloss': 0.5310183030690316}
Early stopping at epoch 6

,task,version,model,calibration,heldout_auroc,heldout_auprc,heldout_brier,heldout_logloss
0,guo_readmission,raw,GRU_1L_numeric,raw,0.687341,0.267068,0.170771,0.519469
1,guo_readmission,raw,GRU_1L_numeric,platt,0.687341,0.267068,0.097802,0.338444

,task,version,model,calibration,top_frac,top_k,events_in_top_k,top_k_event_rate,top_k_lift,event_capture,base_event_rate,n,n_positive
4,guo_readmission,raw,GRU_1L_numeric,platt,0.01,22,10,0.454545,3.826923,0.038462,0.118776,2189,260
5,guo_readmission,raw,GRU_1L_numeric,platt,0.05,110,40,0.363636,3.061538,0.153846,0.118776,2189,260
6,guo_readmission,raw,GRU_1L_numeric,platt,0.10,219,75,0.342466,2.883298,0.288462,0.118776,2189,260
7,guo_readmission,raw,GRU_1L_numeric,platt,0.20,438,122,0.278539,2.345083,0.469231,0.118776,2189,260

====================================================================================================
Experiment: guo_readmission | raw | GRU_2L_numeric

numeric stats:   0%|          | 0/2608 [00:00<?, ?it/s]

epoch 1:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 1, 'train_loss': 1.2261218239621419, 'tuning_auroc': np.float64(0.6813865138420298), 'tuning_auprc': np.float64(0.27970799101665184), 'tuning_brier': np.float64(0.2177298125256331), 'tuning_logloss': 0.6259335007318109}

epoch 2:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 2, 'train_loss': 1.117809360710586, 'tuning_auroc': np.float64(0.7049535517862919), 'tuning_auprc': np.float64(0.3193654505408764), 'tuning_brier': np.float64(0.2910722118056289), 'tuning_logloss': 0.7897769435162352}

epoch 3:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 3, 'train_loss': 1.0475467850522298, 'tuning_auroc': np.float64(0.7147238526597957), 'tuning_auprc': np.float64(0.30894187891844654), 'tuning_brier': np.float64(0.13371614676176527), 'tuning_logloss': 0.4294624528853608}

epoch 4:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 4, 'train_loss': 0.9722505884199608, 'tuning_auroc': np.float64(0.7214475204510792), 'tuning_auprc': np.float64(0.34114870741035824), 'tuning_brier': np.float64(0.11827738902453437), 'tuning_logloss': 0.3905330296415702}

epoch 5:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 5, 'train_loss': 0.867763497843975, 'tuning_auroc': np.float64(0.7308185053380782), 'tuning_auprc': np.float64(0.34905771147841774), 'tuning_brier': np.float64(0.11491401089883978), 'tuning_logloss': 0.3805221310476263}

epoch 6:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 6, 'train_loss': 0.8040512047889756, 'tuning_auroc': np.float64(0.7340296713962194), 'tuning_auprc': np.float64(0.35301142677833386), 'tuning_brier': np.float64(0.11635273762761715), 'tuning_logloss': 0.3857086279277308}

epoch 7:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 7, 'train_loss': 0.7593836771642289, 'tuning_auroc': np.float64(0.7216231455377362), 'tuning_auprc': np.float64(0.3416841234049274), 'tuning_brier': np.float64(0.11660119969337945), 'tuning_logloss': 0.38965401662821403}

epoch 8:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 8, 'train_loss': 0.6971844898127928, 'tuning_auroc': np.float64(0.7068835790543976), 'tuning_auprc': np.float64(0.3276662097241765), 'tuning_brier': np.float64(0.18454632856183334), 'tuning_logloss': 0.5606721576020112}

epoch 9:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 9, 'train_loss': 0.5938970286671709, 'tuning_auroc': np.float64(0.7094088829320147), 'tuning_auprc': np.float64(0.3329163893841265), 'tuning_brier': np.float64(0.1904563555195956), 'tuning_logloss': 0.6600382108149165}
Early stopping at epoch 9

,task,version,model,calibration,heldout_auroc,heldout_auprc,heldout_brier,heldout_logloss
0,guo_readmission,raw,GRU_2L_numeric,raw,0.744148,0.328227,0.107992,0.358488
1,guo_readmission,raw,GRU_2L_numeric,platt,0.744148,0.328227,0.092704,0.318963

,task,version,model,calibration,top_frac,top_k,events_in_top_k,top_k_event_rate,top_k_lift,event_capture,base_event_rate,n,n_positive
4,guo_readmission,raw,GRU_2L_numeric,platt,0.01,22,13,0.590909,4.975000,0.050000,0.118776,2189,260
5,guo_readmission,raw,GRU_2L_numeric,platt,0.05,110,49,0.445455,3.750385,0.188462,0.118776,2189,260
6,guo_readmission,raw,GRU_2L_numeric,platt,0.10,219,85,0.388128,3.267738,0.326923,0.118776,2189,260
7,guo_readmission,raw,GRU_2L_numeric,platt,0.20,438,134,0.305936,2.575746,0.515385,0.118776,2189,260

====================================================================================================
Experiment: guo_readmission | raw | LSTM_1L_numeric

numeric stats:   0%|          | 0/2608 [00:00<?, ?it/s]

epoch 1:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 1, 'train_loss': 1.1933868934468526, 'tuning_auroc': np.float64(0.6487036095577021), 'tuning_auprc': np.float64(0.21790773253206103), 'tuning_brier': np.float64(0.27325051718107113), 'tuning_logloss': 0.7471562837564556}

epoch 2:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 2, 'train_loss': 1.0828508371260108, 'tuning_auroc': np.float64(0.6814253362296068), 'tuning_auprc': np.float64(0.2644369331115048), 'tuning_brier': np.float64(0.23820242056565227), 'tuning_logloss': 0.6725480358496043}

epoch 3:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 3, 'train_loss': 1.0038359564978903, 'tuning_auroc': np.float64(0.6941331977630909), 'tuning_auprc': np.float64(0.28936204600617976), 'tuning_brier': np.float64(0.11866939703518144), 'tuning_logloss': 0.3978192582573313}

epoch 4:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 4, 'train_loss': 0.969362760098969, 'tuning_auroc': np.float64(0.6921957757544945), 'tuning_auprc': np.float64(0.2984871455289117), 'tuning_brier': np.float64(0.15145715292263473), 'tuning_logloss': 0.4748569307941865}

epoch 5:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 5, 'train_loss': 0.8876064648715462, 'tuning_auroc': np.float64(0.6947155335767435), 'tuning_auprc': np.float64(0.2996914451461955), 'tuning_brier': np.float64(0.14478061179807547), 'tuning_logloss': 0.4587372415404455}

epoch 6:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 6, 'train_loss': 0.8042734112681412, 'tuning_auroc': np.float64(0.7122632527614734), 'tuning_auprc': np.float64(0.32841988846877), 'tuning_brier': np.float64(0.1886875804615474), 'tuning_logloss': 0.5683449976432061}

epoch 7:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 7, 'train_loss': 0.7975446614550381, 'tuning_auroc': np.float64(0.716334057401673), 'tuning_auprc': np.float64(0.3112038026697198), 'tuning_brier': np.float64(0.1790707853271806), 'tuning_logloss': 0.5569415699859167}

epoch 8:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 8, 'train_loss': 0.6888817156233439, 'tuning_auroc': np.float64(0.6894153533299441), 'tuning_auprc': np.float64(0.2872821532543155), 'tuning_brier': np.float64(0.16107999429706454), 'tuning_logloss': 0.5001879714552919}

epoch 9:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 9, 'train_loss': 0.6827990948790457, 'tuning_auroc': np.float64(0.7112668114803347), 'tuning_auprc': np.float64(0.26900708158813413), 'tuning_brier': np.float64(0.2932121866785662), 'tuning_logloss': 0.8914951613031752}
Early stopping at epoch 9

,task,version,model,calibration,heldout_auroc,heldout_auprc,heldout_brier,heldout_logloss
0,guo_readmission,raw,LSTM_1L_numeric,raw,0.735385,0.291786,0.189810,0.571372
1,guo_readmission,raw,LSTM_1L_numeric,platt,0.735385,0.291786,0.095103,0.325617

,task,version,model,calibration,top_frac,top_k,events_in_top_k,top_k_event_rate,top_k_lift,event_capture,base_event_rate,n,n_positive
4,guo_readmission,raw,LSTM_1L_numeric,platt,0.01,22,10,0.454545,3.826923,0.038462,0.118776,2189,260
5,guo_readmission,raw,LSTM_1L_numeric,platt,0.05,110,43,0.390909,3.291154,0.165385,0.118776,2189,260
6,guo_readmission,raw,LSTM_1L_numeric,platt,0.10,219,82,0.374429,3.152406,0.315385,0.118776,2189,260
7,guo_readmission,raw,LSTM_1L_numeric,platt,0.20,438,131,0.299087,2.518080,0.503846,0.118776,2189,260

====================================================================================================
Experiment: guo_readmission | raw | LSTM_2L_numeric

numeric stats:   0%|          | 0/2608 [00:00<?, ?it/s]

epoch 1:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 1, 'train_loss': 1.201446155222451, 'tuning_auroc': np.float64(0.6525155982807228), 'tuning_auprc': np.float64(0.2589909515074653), 'tuning_brier': np.float64(0.2505534458590179), 'tuning_logloss': 0.6942883773863852}

epoch 2:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 2, 'train_loss': 1.1427580794183219, 'tuning_auroc': np.float64(0.6885852937098489), 'tuning_auprc': np.float64(0.2992740482189421), 'tuning_brier': np.float64(0.2052623191740872), 'tuning_logloss': 0.6014139418749093}

epoch 3:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 3, 'train_loss': 1.00783788612703, 'tuning_auroc': np.float64(0.6902491103202848), 'tuning_auprc': np.float64(0.2828232021499824), 'tuning_brier': np.float64(0.19489237197080245), 'tuning_logloss': 0.5793943249189238}

epoch 4:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 4, 'train_loss': 0.9462499760273027, 'tuning_auroc': np.float64(0.7144631880574941), 'tuning_auprc': np.float64(0.31214836137751), 'tuning_brier': np.float64(0.14941591553837288), 'tuning_logloss': 0.4706254985919671}

epoch 5:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 5, 'train_loss': 0.8979941337573819, 'tuning_auroc': np.float64(0.6974053704302815), 'tuning_auprc': np.float64(0.28680992517669635), 'tuning_brier': np.float64(0.14164633893403705), 'tuning_logloss': 0.456364758754716}

epoch 6:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 6, 'train_loss': 0.8301273253632755, 'tuning_auroc': np.float64(0.697597633683043), 'tuning_auprc': np.float64(0.29902252116052386), 'tuning_brier': np.float64(0.11668582457691673), 'tuning_logloss': 0.3881545005772642}

epoch 7:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 7, 'train_loss': 0.7983953832853131, 'tuning_auroc': np.float64(0.7124906410315665), 'tuning_auprc': np.float64(0.2941843654036307), 'tuning_brier': np.float64(0.1659446659758163), 'tuning_logloss': 0.5195272255495695}
Early stopping at epoch 7

,task,version,model,calibration,heldout_auroc,heldout_auprc,heldout_brier,heldout_logloss
0,guo_readmission,raw,LSTM_2L_numeric,raw,0.718854,0.301894,0.150720,0.472587
1,guo_readmission,raw,LSTM_2L_numeric,platt,0.718854,0.301894,0.095235,0.328380

,task,version,model,calibration,top_frac,top_k,events_in_top_k,top_k_event_rate,top_k_lift,event_capture,base_event_rate,n,n_positive
4,guo_readmission,raw,LSTM_2L_numeric,platt,0.01,22,12,0.545455,4.592308,0.046154,0.118776,2189,260
5,guo_readmission,raw,LSTM_2L_numeric,platt,0.05,110,44,0.400000,3.367692,0.169231,0.118776,2189,260
6,guo_readmission,raw,LSTM_2L_numeric,platt,0.10,219,79,0.360731,3.037074,0.303846,0.118776,2189,260
7,guo_readmission,raw,LSTM_2L_numeric,platt,0.20,438,127,0.289954,2.441192,0.488462,0.118776,2189,260

====================================================================================================
Experiment: guo_readmission | raw | RETAIN_lite_numeric

numeric stats:   0%|          | 0/2608 [00:00<?, ?it/s]

epoch 1:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 1, 'train_loss': 1.1126514389747526, 'tuning_auroc': np.float64(0.695480889217544), 'tuning_auprc': np.float64(0.23871026167139195), 'tuning_brier': np.float64(0.19292441174768798), 'tuning_logloss': 0.5621571899714649}

epoch 2:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 2, 'train_loss': 0.99800483119197, 'tuning_auroc': np.float64(0.7296501363405278), 'tuning_auprc': np.float64(0.3000265786344012), 'tuning_brier': np.float64(0.14969570258306933), 'tuning_logloss': 0.459622353115182}

epoch 3:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 3, 'train_loss': 0.9765837643204666, 'tuning_auroc': np.float64(0.7383019827147942), 'tuning_auprc': np.float64(0.3290129990242112), 'tuning_brier': np.float64(0.11077249169365008), 'tuning_logloss': 0.36545901674466447}

epoch 4:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 4, 'train_loss': 0.9349414179237877, 'tuning_auroc': np.float64(0.7427610112307621), 'tuning_auprc': np.float64(0.36672694320705274), 'tuning_brier': np.float64(0.1711604509938641), 'tuning_logloss': 0.5222164882457482}

epoch 5:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 5, 'train_loss': 0.8944851305426621, 'tuning_auroc': np.float64(0.7456985718907427), 'tuning_auprc': np.float64(0.3938193873563518), 'tuning_brier': np.float64(0.15679348840729274), 'tuning_logloss': 0.48352470914165685}

epoch 6:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 6, 'train_loss': 0.8542497052652079, 'tuning_auroc': np.float64(0.7510468179507325), 'tuning_auprc': np.float64(0.3900867146245419), 'tuning_brier': np.float64(0.17227293473656793), 'tuning_logloss': 0.5204150815937189}

epoch 7:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 7, 'train_loss': 0.8205206572282605, 'tuning_auroc': np.float64(0.7494033368766464), 'tuning_auprc': np.float64(0.41065567978642964), 'tuning_brier': np.float64(0.15367241501473541), 'tuning_logloss': 0.4749714150053448}

epoch 8:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 8, 'train_loss': 0.8130448356997676, 'tuning_auroc': np.float64(0.746861394832925), 'tuning_auprc': np.float64(0.3997583268400666), 'tuning_brier': np.float64(0.11350082965846073), 'tuning_logloss': 0.3745363040341102}

epoch 9:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 9, 'train_loss': 0.7043973407367381, 'tuning_auroc': np.float64(0.7468484540370661), 'tuning_auprc': np.float64(0.4082336755776263), 'tuning_brier': np.float64(0.12040087559138568), 'tuning_logloss': 0.3915836889144666}

epoch 10:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 10, 'train_loss': 0.6765652964027916, 'tuning_auroc': np.float64(0.7468669408882933), 'tuning_auprc': np.float64(0.4059972332832773), 'tuning_brier': np.float64(0.11226408380610883), 'tuning_logloss': 0.3698970104308212}
Early stopping at epoch 10

,task,version,model,calibration,heldout_auroc,heldout_auprc,heldout_brier,heldout_logloss
0,guo_readmission,raw,RETAIN_lite_numeric,raw,0.772471,0.380255,0.149253,0.464154
1,guo_readmission,raw,RETAIN_lite_numeric,platt,0.772471,0.380255,0.089038,0.307085

,task,version,model,calibration,top_frac,top_k,events_in_top_k,top_k_event_rate,top_k_lift,event_capture,base_event_rate,n,n_positive
4,guo_readmission,raw,RETAIN_lite_numeric,platt,0.01,22,14,0.636364,5.357692,0.053846,0.118776,2189,260
5,guo_readmission,raw,RETAIN_lite_numeric,platt,0.05,110,57,0.518182,4.362692,0.219231,0.118776,2189,260
6,guo_readmission,raw,RETAIN_lite_numeric,platt,0.10,219,94,0.429224,3.613734,0.361538,0.118776,2189,260
7,guo_readmission,raw,RETAIN_lite_numeric,platt,0.20,438,143,0.326484,2.748744,0.550000,0.118776,2189,260

====================================================================================================
Experiment: guo_readmission | compressed_dedup | GRU_1L_numeric

numeric stats:   0%|          | 0/2608 [00:00<?, ?it/s]

epoch 1:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 1, 'train_loss': 1.202364435283149, 'tuning_auroc': np.float64(0.6171557979387161), 'tuning_auprc': np.float64(0.2101977722539245), 'tuning_brier': np.float64(0.2795479766834193), 'tuning_logloss': 0.754547896258512}

epoch 2:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 2, 'train_loss': 1.0924139945972255, 'tuning_auroc': np.float64(0.6612302999491613), 'tuning_auprc': np.float64(0.24640878815673867), 'tuning_brier': np.float64(0.19722495999942866), 'tuning_logloss': 0.5803982142134575}

epoch 3:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 3, 'train_loss': 1.0194904753347722, 'tuning_auroc': np.float64(0.6816305402782272), 'tuning_auprc': np.float64(0.27349334912905526), 'tuning_brier': np.float64(0.1495241520450041), 'tuning_logloss': 0.47046899816047105}

epoch 4:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 4, 'train_loss': 0.9218405743197697, 'tuning_auroc': np.float64(0.6989490225077414), 'tuning_auprc': np.float64(0.27637819083299914), 'tuning_brier': np.float64(0.15463998355799596), 'tuning_logloss': 0.4827052642466017}

epoch 5:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 5, 'train_loss': 0.8591894007674078, 'tuning_auroc': np.float64(0.6960354947543559), 'tuning_auprc': np.float64(0.2789520174801031), 'tuning_brier': np.float64(0.126621653246302), 'tuning_logloss': 0.41185516904323255}

epoch 6:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 6, 'train_loss': 0.7546420671590944, 'tuning_auroc': np.float64(0.7140971484031982), 'tuning_auprc': np.float64(0.31025044821471126), 'tuning_brier': np.float64(0.13584034228926617), 'tuning_logloss': 0.464368459107161}

epoch 7:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 7, 'train_loss': 0.7426928694291812, 'tuning_auroc': np.float64(0.6913139529509637), 'tuning_auprc': np.float64(0.29559040589160673), 'tuning_brier': np.float64(0.12396186325087999), 'tuning_logloss': 0.41491980050100713}

epoch 8:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 8, 'train_loss': 0.6709452253289339, 'tuning_auroc': np.float64(0.6959966723667791), 'tuning_auprc': np.float64(0.2942150242910541), 'tuning_brier': np.float64(0.19321033763640777), 'tuning_logloss': 0.6175919519044125}

epoch 9:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 9, 'train_loss': 0.6360584951755477, 'tuning_auroc': np.float64(0.6861838517354532), 'tuning_auprc': np.float64(0.3075653827662113), 'tuning_brier': np.float64(0.11507570817378467), 'tuning_logloss': 0.4045240015992605}
Early stopping at epoch 9

,task,version,model,calibration,heldout_auroc,heldout_auprc,heldout_brier,heldout_logloss
0,guo_readmission,compressed_dedup,GRU_1L_numeric,raw,0.747741,0.313034,0.125569,0.427095
1,guo_readmission,compressed_dedup,GRU_1L_numeric,platt,0.747741,0.313034,0.092900,0.319456

,task,version,model,calibration,top_frac,top_k,events_in_top_k,top_k_event_rate,top_k_lift,event_capture,base_event_rate,n,n_positive
4,guo_readmission,compressed_dedup,GRU_1L_numeric,platt,0.01,22,10,0.454545,3.826923,0.038462,0.118776,2189,260
5,guo_readmission,compressed_dedup,GRU_1L_numeric,platt,0.05,110,46,0.418182,3.520769,0.176923,0.118776,2189,260
6,guo_readmission,compressed_dedup,GRU_1L_numeric,platt,0.10,219,91,0.415525,3.498402,0.350000,0.118776,2189,260
7,guo_readmission,compressed_dedup,GRU_1L_numeric,platt,0.20,438,131,0.299087,2.518080,0.503846,0.118776,2189,260

====================================================================================================
Experiment: guo_readmission | compressed_dedup | GRU_2L_numeric

numeric stats:   0%|          | 0/2608 [00:00<?, ?it/s]

epoch 1:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 1, 'train_loss': 1.2212497868188998, 'tuning_auroc': np.float64(0.6245653279105237), 'tuning_auprc': np.float64(0.2084227757217233), 'tuning_brier': np.float64(0.2476505248845804), 'tuning_logloss': 0.6883949742500145}

epoch 2:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 2, 'train_loss': 1.1292137503623962, 'tuning_auroc': np.float64(0.6652456440356797), 'tuning_auprc': np.float64(0.26419561949860065), 'tuning_brier': np.float64(0.22230441637137535), 'tuning_logloss': 0.6342187638273853}

epoch 3:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 3, 'train_loss': 1.0634876947577407, 'tuning_auroc': np.float64(0.6851264038452649), 'tuning_auprc': np.float64(0.2977845061076413), 'tuning_brier': np.float64(0.12619539718030076), 'tuning_logloss': 0.4200116979594899}

epoch 4:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 4, 'train_loss': 0.9793974735387941, 'tuning_auroc': np.float64(0.7121005684706752), 'tuning_auprc': np.float64(0.3144750376019331), 'tuning_brier': np.float64(0.15267089025884492), 'tuning_logloss': 0.47518773827932015}

epoch 5:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 5, 'train_loss': 0.8654441361020251, 'tuning_auroc': np.float64(0.7106049822064058), 'tuning_auprc': np.float64(0.31510098771274603), 'tuning_brier': np.float64(0.11315953911287621), 'tuning_logloss': 0.376148390611829}

epoch 6:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 6, 'train_loss': 0.8233086354121929, 'tuning_auroc': np.float64(0.7043416370106761), 'tuning_auprc': np.float64(0.3017506650409811), 'tuning_brier': np.float64(0.13163623882979353), 'tuning_logloss': 0.4258114556306232}

epoch 7:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 7, 'train_loss': 0.7037884138706254, 'tuning_auroc': np.float64(0.708789573415908), 'tuning_auprc': np.float64(0.32315736040170734), 'tuning_brier': np.float64(0.118193294833195), 'tuning_logloss': 0.4095109222390369}

epoch 8:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 8, 'train_loss': 0.6904768609419102, 'tuning_auroc': np.float64(0.6957766788371771), 'tuning_auprc': np.float64(0.3121278981339918), 'tuning_brier': np.float64(0.14304682293869553), 'tuning_logloss': 0.45914670705239446}

epoch 9:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 9, 'train_loss': 0.5812303974497609, 'tuning_auroc': np.float64(0.6943365531265887), 'tuning_auprc': np.float64(0.3069044511938237), 'tuning_brier': np.float64(0.1343312526343211), 'tuning_logloss': 0.4570402060311007}

epoch 10:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 10, 'train_loss': 0.5068548522980475, 'tuning_auroc': np.float64(0.7046078476683459), 'tuning_auprc': np.float64(0.2827001256808775), 'tuning_brier': np.float64(0.19577195518016544), 'tuning_logloss': 0.6499750263413259}
Early stopping at epoch 10

,task,version,model,calibration,heldout_auroc,heldout_auprc,heldout_brier,heldout_logloss
0,guo_readmission,compressed_dedup,GRU_2L_numeric,raw,0.698471,0.282117,0.119824,0.410408
1,guo_readmission,compressed_dedup,GRU_2L_numeric,platt,0.698471,0.282117,0.096733,0.334111

,task,version,model,calibration,top_frac,top_k,events_in_top_k,top_k_event_rate,top_k_lift,event_capture,base_event_rate,n,n_positive
4,guo_readmission,compressed_dedup,GRU_2L_numeric,platt,0.01,22,12,0.545455,4.592308,0.046154,0.118776,2189,260
5,guo_readmission,compressed_dedup,GRU_2L_numeric,platt,0.05,110,43,0.390909,3.291154,0.165385,0.118776,2189,260
6,guo_readmission,compressed_dedup,GRU_2L_numeric,platt,0.10,219,80,0.365297,3.075518,0.307692,0.118776,2189,260
7,guo_readmission,compressed_dedup,GRU_2L_numeric,platt,0.20,438,120,0.273973,2.306639,0.461538,0.118776,2189,260

====================================================================================================
Experiment: guo_readmission | compressed_dedup | LSTM_1L_numeric

numeric stats:   0%|          | 0/2608 [00:00<?, ?it/s]

epoch 1:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 1, 'train_loss': 1.1604092542718096, 'tuning_auroc': np.float64(0.6590543975597356), 'tuning_auprc': np.float64(0.23804779099499057), 'tuning_brier': np.float64(0.2092444874096781), 'tuning_logloss': 0.6090880920239691}

epoch 2:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 2, 'train_loss': 1.0726948714837796, 'tuning_auroc': np.float64(0.6771918472986088), 'tuning_auprc': np.float64(0.27574370432600953), 'tuning_brier': np.float64(0.1307011059205185), 'tuning_logloss': 0.4274234967311106}

epoch 3:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 3, 'train_loss': 1.0096102858461984, 'tuning_auroc': np.float64(0.6836622452280815), 'tuning_auprc': np.float64(0.2821310134638872), 'tuning_brier': np.float64(0.2897026478500502), 'tuning_logloss': 0.7954955490808504}

epoch 4:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 4, 'train_loss': 0.9642153022492804, 'tuning_auroc': np.float64(0.7003207468687896), 'tuning_auprc': np.float64(0.3035328237996557), 'tuning_brier': np.float64(0.21675216584780643), 'tuning_logloss': 0.6361331869486907}

epoch 5:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 5, 'train_loss': 0.8956755850373245, 'tuning_auroc': np.float64(0.7114997458057957), 'tuning_auprc': np.float64(0.31199374112996914), 'tuning_brier': np.float64(0.16334350482138746), 'tuning_logloss': 0.5120925310885567}

epoch 6:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 6, 'train_loss': 0.8276690179254951, 'tuning_auroc': np.float64(0.7154466885427739), 'tuning_auprc': np.float64(0.31142074169825734), 'tuning_brier': np.float64(0.1298693451179563), 'tuning_logloss': 0.4240369618997913}

epoch 7:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 7, 'train_loss': 0.8054539474045358, 'tuning_auroc': np.float64(0.6874095299718076), 'tuning_auprc': np.float64(0.2556732030253167), 'tuning_brier': np.float64(0.30223624579878805), 'tuning_logloss': 0.8627036814657723}

epoch 8:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 8, 'train_loss': 0.7621602899417644, 'tuning_auroc': np.float64(0.6801552895503074), 'tuning_auprc': np.float64(0.28208774020645505), 'tuning_brier': np.float64(0.10981706636165571), 'tuning_logloss': 0.37554418369197656}
Early stopping at epoch 8

,task,version,model,calibration,heldout_auroc,heldout_auprc,heldout_brier,heldout_logloss
0,guo_readmission,compressed_dedup,LSTM_1L_numeric,raw,0.703348,0.261853,0.165523,0.515394
1,guo_readmission,compressed_dedup,LSTM_1L_numeric,platt,0.703348,0.261853,0.097076,0.334172

,task,version,model,calibration,top_frac,top_k,events_in_top_k,top_k_event_rate,top_k_lift,event_capture,base_event_rate,n,n_positive
4,guo_readmission,compressed_dedup,LSTM_1L_numeric,platt,0.01,22,8,0.363636,3.061538,0.030769,0.118776,2189,260
5,guo_readmission,compressed_dedup,LSTM_1L_numeric,platt,0.05,110,40,0.363636,3.061538,0.153846,0.118776,2189,260
6,guo_readmission,compressed_dedup,LSTM_1L_numeric,platt,0.10,219,81,0.369863,3.113962,0.311538,0.118776,2189,260
7,guo_readmission,compressed_dedup,LSTM_1L_numeric,platt,0.20,438,117,0.267123,2.248973,0.450000,0.118776,2189,260

====================================================================================================
Experiment: guo_readmission | compressed_dedup | LSTM_2L_numeric

numeric stats:   0%|          | 0/2608 [00:00<?, ?it/s]

epoch 1:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 1, 'train_loss': 1.2092489890935945, 'tuning_auroc': np.float64(0.6652105190183482), 'tuning_auprc': np.float64(0.24648897587746077), 'tuning_brier': np.float64(0.17858182477724335), 'tuning_logloss': 0.5458527181409708}

epoch 2:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 2, 'train_loss': 1.0772166019532738, 'tuning_auroc': np.float64(0.6935638027452974), 'tuning_auprc': np.float64(0.2944240214442231), 'tuning_brier': np.float64(0.23765274582050427), 'tuning_logloss': 0.670586304443649}

epoch 3:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 3, 'train_loss': 0.9982544343645979, 'tuning_auroc': np.float64(0.7196801774737718), 'tuning_auprc': np.float64(0.3316472922116354), 'tuning_brier': np.float64(0.21244339293592057), 'tuning_logloss': 0.6194153337534721}

epoch 4:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 4, 'train_loss': 0.945582975701588, 'tuning_auroc': np.float64(0.7209169478208625), 'tuning_auprc': np.float64(0.3509488525479836), 'tuning_brier': np.float64(0.15050784919841403), 'tuning_logloss': 0.4831285568104093}

epoch 5:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 5, 'train_loss': 0.8583020069977132, 'tuning_auroc': np.float64(0.714067569441235), 'tuning_auprc': np.float64(0.32967228135749127), 'tuning_brier': np.float64(0.10395293889061172), 'tuning_logloss': 0.3525000732787609}

epoch 6:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 6, 'train_loss': 0.9225689396262169, 'tuning_auroc': np.float64(0.7180385450848084), 'tuning_auprc': np.float64(0.3317161310583403), 'tuning_brier': np.float64(0.21628890138258938), 'tuning_logloss': 0.6566519683058496}

epoch 7:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 7, 'train_loss': 0.7590636236638557, 'tuning_auroc': np.float64(0.7141267273651616), 'tuning_auprc': np.float64(0.35739680679842584), 'tuning_brier': np.float64(0.13793902054707632), 'tuning_logloss': 0.44487211788810743}

epoch 8:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 8, 'train_loss': 0.7135876562537217, 'tuning_auroc': np.float64(0.7066321578777095), 'tuning_auprc': np.float64(0.3428112920243297), 'tuning_brier': np.float64(0.24143703514303178), 'tuning_logloss': 0.736925919501238}

epoch 9:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 9, 'train_loss': 0.6824816120106999, 'tuning_auroc': np.float64(0.6995406017470074), 'tuning_auprc': np.float64(0.33889219481918775), 'tuning_brier': np.float64(0.13764196108523888), 'tuning_logloss': 0.4597350162865853}

epoch 10:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 10, 'train_loss': 0.650308515058785, 'tuning_auroc': np.float64(0.6939557239913111), 'tuning_auprc': np.float64(0.34694747270739157), 'tuning_brier': np.float64(0.12132162489979173), 'tuning_logloss': 0.43745325008020325}
Early stopping at epoch 10

,task,version,model,calibration,heldout_auroc,heldout_auprc,heldout_brier,heldout_logloss
0,guo_readmission,compressed_dedup,LSTM_2L_numeric,raw,0.702301,0.270608,0.146686,0.469933
1,guo_readmission,compressed_dedup,LSTM_2L_numeric,platt,0.702301,0.270608,0.097050,0.333394

,task,version,model,calibration,top_frac,top_k,events_in_top_k,top_k_event_rate,top_k_lift,event_capture,base_event_rate,n,n_positive
4,guo_readmission,compressed_dedup,LSTM_2L_numeric,platt,0.01,22,10,0.454545,3.826923,0.038462,0.118776,2189,260
5,guo_readmission,compressed_dedup,LSTM_2L_numeric,platt,0.05,110,42,0.381818,3.214615,0.161538,0.118776,2189,260
6,guo_readmission,compressed_dedup,LSTM_2L_numeric,platt,0.10,219,77,0.351598,2.960186,0.296154,0.118776,2189,260
7,guo_readmission,compressed_dedup,LSTM_2L_numeric,platt,0.20,438,123,0.280822,2.364305,0.473077,0.118776,2189,260

====================================================================================================
Experiment: guo_readmission | compressed_dedup | RETAIN_lite_numeric

numeric stats:   0%|          | 0/2608 [00:00<?, ?it/s]

epoch 1:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 1, 'train_loss': 1.1563462607744264, 'tuning_auroc': np.float64(0.6913158016360864), 'tuning_auprc': np.float64(0.2416507037847867), 'tuning_brier': np.float64(0.1491933048731842), 'tuning_logloss': 0.4672659764048459}

epoch 2:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 2, 'train_loss': 1.0615720414533847, 'tuning_auroc': np.float64(0.7184600452927854), 'tuning_auprc': np.float64(0.2839779519038164), 'tuning_brier': np.float64(0.24056892425419518), 'tuning_logloss': 0.6760821000272882}

epoch 3:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 3, 'train_loss': 0.9652636171114154, 'tuning_auroc': np.float64(0.7361075934741416), 'tuning_auprc': np.float64(0.3341898163447587), 'tuning_brier': np.float64(0.20643008313548272), 'tuning_logloss': 0.6044668477586673}

epoch 4:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 4, 'train_loss': 0.9404955553572353, 'tuning_auroc': np.float64(0.7454619401950362), 'tuning_auprc': np.float64(0.35462907998289), 'tuning_brier': np.float64(0.1587493193704835), 'tuning_logloss': 0.4850649891437996}

epoch 5:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 5, 'train_loss': 0.8390368255900174, 'tuning_auroc': np.float64(0.7473198687433563), 'tuning_auprc': np.float64(0.36837710590752903), 'tuning_brier': np.float64(0.1915888631516324), 'tuning_logloss': 0.5708541268657736}

epoch 6:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 6, 'train_loss': 0.816771285381259, 'tuning_auroc': np.float64(0.7390673383555947), 'tuning_auprc': np.float64(0.3347657188983725), 'tuning_brier': np.float64(0.14069969084141856), 'tuning_logloss': 0.45115422935365773}

epoch 7:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 7, 'train_loss': 0.7795772894126612, 'tuning_auroc': np.float64(0.7527808845958311), 'tuning_auprc': np.float64(0.3601801721170202), 'tuning_brier': np.float64(0.12778541614407454), 'tuning_logloss': 0.41290988553487407}

epoch 8:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 8, 'train_loss': 0.7134894459712796, 'tuning_auroc': np.float64(0.7607672043259232), 'tuning_auprc': np.float64(0.3848940505065722), 'tuning_brier': np.float64(0.11199547966775679), 'tuning_logloss': 0.3688461748323879}

epoch 9:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 9, 'train_loss': 0.642117350566678, 'tuning_auroc': np.float64(0.755849701899524), 'tuning_auprc': np.float64(0.3583336919306669), 'tuning_brier': np.float64(0.14605048896407968), 'tuning_logloss': 0.46206561741250374}

epoch 10:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 10, 'train_loss': 0.6371393476317568, 'tuning_auroc': np.float64(0.7597596709340482), 'tuning_auprc': np.float64(0.36247876815798147), 'tuning_brier': np.float64(0.15523083982614183), 'tuning_logloss': 0.4912862716920466}

epoch 11:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 11, 'train_loss': 0.5996563036630793, 'tuning_auroc': np.float64(0.7382483708462356), 'tuning_auprc': np.float64(0.35817661659989275), 'tuning_brier': np.float64(0.11274590949530014), 'tuning_logloss': 0.3895757827818192}
Early stopping at epoch 11

,task,version,model,calibration,heldout_auroc,heldout_auprc,heldout_brier,heldout_logloss
0,guo_readmission,compressed_dedup,RETAIN_lite_numeric,raw,0.776034,0.376194,0.104301,0.348370
1,guo_readmission,compressed_dedup,RETAIN_lite_numeric,platt,0.776034,0.376194,0.088144,0.304184

,task,version,model,calibration,top_frac,top_k,events_in_top_k,top_k_event_rate,top_k_lift,event_capture,base_event_rate,n,n_positive
4,guo_readmission,compressed_dedup,RETAIN_lite_numeric,platt,0.01,22,13,0.590909,4.975000,0.050000,0.118776,2189,260
5,guo_readmission,compressed_dedup,RETAIN_lite_numeric,platt,0.05,110,57,0.518182,4.362692,0.219231,0.118776,2189,260
6,guo_readmission,compressed_dedup,RETAIN_lite_numeric,platt,0.10,219,98,0.447489,3.767510,0.376923,0.118776,2189,260
7,guo_readmission,compressed_dedup,RETAIN_lite_numeric,platt,0.20,438,153,0.349315,2.940964,0.588462,0.118776,2189,260

====================================================================================================
Experiment: guo_readmission | compressed_first_last | GRU_1L_numeric

numeric stats:   0%|          | 0/2608 [00:00<?, ?it/s]

epoch 1:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 1, 'train_loss': 1.208308681482222, 'tuning_auroc': np.float64(0.6494190507001895), 'tuning_auprc': np.float64(0.26170908871294224), 'tuning_brier': np.float64(0.16510104346180848), 'tuning_logloss': 0.5151938940705657}

epoch 2:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 2, 'train_loss': 1.140429823863797, 'tuning_auroc': np.float64(0.6812534085131949), 'tuning_auprc': np.float64(0.3010369104913117), 'tuning_brier': np.float64(0.14944356746974433), 'tuning_logloss': 0.4743214977983163}

epoch 3:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 3, 'train_loss': 1.0277730371893905, 'tuning_auroc': np.float64(0.7044673475990203), 'tuning_auprc': np.float64(0.32332542851810553), 'tuning_brier': np.float64(0.15270446536793159), 'tuning_logloss': 0.4804974692721403}

epoch 4:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 4, 'train_loss': 0.9360670669049751, 'tuning_auroc': np.float64(0.7022156491195637), 'tuning_auprc': np.float64(0.32296085621257936), 'tuning_brier': np.float64(0.16209256957522988), 'tuning_logloss': 0.5014028129727239}

epoch 5:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 5, 'train_loss': 0.8667229068715397, 'tuning_auroc': np.float64(0.705167999260526), 'tuning_auprc': np.float64(0.3175619595534891), 'tuning_brier': np.float64(0.1300244931717456), 'tuning_logloss': 0.42018941559387724}

epoch 6:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 6, 'train_loss': 0.7773666777988759, 'tuning_auroc': np.float64(0.6930406248555714), 'tuning_auprc': np.float64(0.3125248146827886), 'tuning_brier': np.float64(0.11638153741800032), 'tuning_logloss': 0.38805244612461076}
Early stopping at epoch 6

,task,version,model,calibration,heldout_auroc,heldout_auprc,heldout_brier,heldout_logloss
0,guo_readmission,compressed_first_last,GRU_1L_numeric,raw,0.685202,0.281864,0.152635,0.479710
1,guo_readmission,compressed_first_last,GRU_1L_numeric,platt,0.685202,0.281864,0.096817,0.335953

,task,version,model,calibration,top_frac,top_k,events_in_top_k,top_k_event_rate,top_k_lift,event_capture,base_event_rate,n,n_positive
4,guo_readmission,compressed_first_last,GRU_1L_numeric,platt,0.01,22,13,0.590909,4.975000,0.050000,0.118776,2189,260
5,guo_readmission,compressed_first_last,GRU_1L_numeric,platt,0.05,110,47,0.427273,3.597308,0.180769,0.118776,2189,260
6,guo_readmission,compressed_first_last,GRU_1L_numeric,platt,0.10,219,78,0.356164,2.998630,0.300000,0.118776,2189,260
7,guo_readmission,compressed_first_last,GRU_1L_numeric,platt,0.20,438,117,0.267123,2.248973,0.450000,0.118776,2189,260

====================================================================================================
Experiment: guo_readmission | compressed_first_last | GRU_2L_numeric

numeric stats:   0%|          | 0/2608 [00:00<?, ?it/s]

epoch 1:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 1, 'train_loss': 1.2161931868006544, 'tuning_auroc': np.float64(0.6622526228220179), 'tuning_auprc': np.float64(0.24187369509013423), 'tuning_brier': np.float64(0.2649780571038717), 'tuning_logloss': 0.7261853986689161}

epoch 2:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 2, 'train_loss': 1.1048206076389406, 'tuning_auroc': np.float64(0.6967527845819661), 'tuning_auprc': np.float64(0.30178939765081375), 'tuning_brier': np.float64(0.1799068309122355), 'tuning_logloss': 0.5429684742749347}

epoch 3:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 3, 'train_loss': 1.0140135873381684, 'tuning_auroc': np.float64(0.6944567176595646), 'tuning_auprc': np.float64(0.3100995267389274), 'tuning_brier': np.float64(0.25944136493025777), 'tuning_logloss': 0.7336706757124354}

epoch 4:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 4, 'train_loss': 0.9322876152468891, 'tuning_auroc': np.float64(0.7082830336922865), 'tuning_auprc': np.float64(0.3359610787657449), 'tuning_brier': np.float64(0.1468166571066426), 'tuning_logloss': 0.46812620840439734}

epoch 5:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 5, 'train_loss': 0.8639827737721001, 'tuning_auroc': np.float64(0.700588806211582), 'tuning_auprc': np.float64(0.34272596077862166), 'tuning_brier': np.float64(0.12042597875355705), 'tuning_logloss': 0.39986122388790996}

epoch 6:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 6, 'train_loss': 0.7991286050982591, 'tuning_auroc': np.float64(0.7046873411286222), 'tuning_auprc': np.float64(0.3124367821632094), 'tuning_brier': np.float64(0.19798439039383417), 'tuning_logloss': 0.6220423155962582}

epoch 7:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 7, 'train_loss': 0.7748130098348711, 'tuning_auroc': np.float64(0.7077210334149836), 'tuning_auprc': np.float64(0.32977434959943674), 'tuning_brier': np.float64(0.10759702222426819), 'tuning_logloss': 0.3746069473523211}

epoch 8:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 8, 'train_loss': 0.6342226145107571, 'tuning_auroc': np.float64(0.7089356195406018), 'tuning_auprc': np.float64(0.3250110629622489), 'tuning_brier': np.float64(0.14350324177570964), 'tuning_logloss': 0.4979863503093267}
Early stopping at epoch 8

,task,version,model,calibration,heldout_auroc,heldout_auprc,heldout_brier,heldout_logloss
0,guo_readmission,compressed_first_last,GRU_2L_numeric,raw,0.744158,0.333801,0.115141,0.381840
1,guo_readmission,compressed_first_last,GRU_2L_numeric,platt,0.744158,0.333801,0.092864,0.320572

,task,version,model,calibration,top_frac,top_k,events_in_top_k,top_k_event_rate,top_k_lift,event_capture,base_event_rate,n,n_positive
4,guo_readmission,compressed_first_last,GRU_2L_numeric,platt,0.01,22,14,0.636364,5.357692,0.053846,0.118776,2189,260
5,guo_readmission,compressed_first_last,GRU_2L_numeric,platt,0.05,110,53,0.481818,4.056538,0.203846,0.118776,2189,260
6,guo_readmission,compressed_first_last,GRU_2L_numeric,platt,0.10,219,86,0.392694,3.306182,0.330769,0.118776,2189,260
7,guo_readmission,compressed_first_last,GRU_2L_numeric,platt,0.20,438,131,0.299087,2.518080,0.503846,0.118776,2189,260

====================================================================================================
Experiment: guo_readmission | compressed_first_last | LSTM_1L_numeric

numeric stats:   0%|          | 0/2608 [00:00<?, ?it/s]

epoch 1:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 1, 'train_loss': 1.2322920066554373, 'tuning_auroc': np.float64(0.6153403891482183), 'tuning_auprc': np.float64(0.195693968022141), 'tuning_brier': np.float64(0.16659673230345862), 'tuning_logloss': 0.5195716654592407}

epoch 2:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 2, 'train_loss': 1.1470709770191005, 'tuning_auroc': np.float64(0.6486647871701252), 'tuning_auprc': np.float64(0.24330098137334172), 'tuning_brier': np.float64(0.28709544019440153), 'tuning_logloss': 0.7745121470681887}

epoch 3:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 3, 'train_loss': 1.046003388558946, 'tuning_auroc': np.float64(0.6740176549429219), 'tuning_auprc': np.float64(0.2911745545811129), 'tuning_brier': np.float64(0.35260990693492583), 'tuning_logloss': 0.9359883761940326}

epoch 4:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 4, 'train_loss': 0.9865712000102531, 'tuning_auroc': np.float64(0.6848638905578408), 'tuning_auprc': np.float64(0.3067170170072396), 'tuning_brier': np.float64(0.19077630976761104), 'tuning_logloss': 0.5700945435580196}

epoch 5:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 5, 'train_loss': 0.8658449417207299, 'tuning_auroc': np.float64(0.70198086610898), 'tuning_auprc': np.float64(0.31054781996558395), 'tuning_brier': np.float64(0.19182444144783603), 'tuning_logloss': 0.5767666851298825}

epoch 6:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 6, 'train_loss': 0.8085595400231641, 'tuning_auroc': np.float64(0.6874317141932801), 'tuning_auprc': np.float64(0.32903688745285964), 'tuning_brier': np.float64(0.10666980527439877), 'tuning_logloss': 0.3675500044474498}

epoch 7:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 7, 'train_loss': 0.8280860803476194, 'tuning_auroc': np.float64(0.7007607339279938), 'tuning_auprc': np.float64(0.3169854482551845), 'tuning_brier': np.float64(0.25253156601360827), 'tuning_logloss': 0.7566677545971408}

epoch 8:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 8, 'train_loss': 0.7321758888116697, 'tuning_auroc': np.float64(0.6996903452419467), 'tuning_auprc': np.float64(0.3479893253282106), 'tuning_brier': np.float64(0.13146874644530168), 'tuning_logloss': 0.43700191586188847}

epoch 9:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 9, 'train_loss': 0.691558767927856, 'tuning_auroc': np.float64(0.7017294449322918), 'tuning_auprc': np.float64(0.29846084797190275), 'tuning_brier': np.float64(0.2596598944385037), 'tuning_logloss': 0.7799463147601604}

epoch 10:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 10, 'train_loss': 0.5895253687006671, 'tuning_auroc': np.float64(0.713928918057032), 'tuning_auprc': np.float64(0.3061602933037314), 'tuning_brier': np.float64(0.21063828401454404), 'tuning_logloss': 0.6603342490193661}

epoch 11:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 11, 'train_loss': 0.573789185503634, 'tuning_auroc': np.float64(0.7205897305541433), 'tuning_auprc': np.float64(0.3363659830680238), 'tuning_brier': np.float64(0.14898048250996315), 'tuning_logloss': 0.49973512131322745}
Early stopping at epoch 11

,task,version,model,calibration,heldout_auroc,heldout_auprc,heldout_brier,heldout_logloss
0,guo_readmission,compressed_first_last,LSTM_1L_numeric,raw,0.701814,0.293251,0.13301,0.439069
1,guo_readmission,compressed_first_last,LSTM_1L_numeric,platt,0.701814,0.293251,0.09521,0.330214

,task,version,model,calibration,top_frac,top_k,events_in_top_k,top_k_event_rate,top_k_lift,event_capture,base_event_rate,n,n_positive
4,guo_readmission,compressed_first_last,LSTM_1L_numeric,platt,0.01,22,11,0.500000,4.209615,0.042308,0.118776,2189,260
5,guo_readmission,compressed_first_last,LSTM_1L_numeric,platt,0.05,110,47,0.427273,3.597308,0.180769,0.118776,2189,260
6,guo_readmission,compressed_first_last,LSTM_1L_numeric,platt,0.10,219,84,0.383562,3.229294,0.323077,0.118776,2189,260
7,guo_readmission,compressed_first_last,LSTM_1L_numeric,platt,0.20,438,127,0.289954,2.441192,0.488462,0.118776,2189,260

====================================================================================================
Experiment: guo_readmission | compressed_first_last | LSTM_2L_numeric

numeric stats:   0%|          | 0/2608 [00:00<?, ?it/s]

epoch 1:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 1, 'train_loss': 1.2481539671013995, 'tuning_auroc': np.float64(0.6380570319360355), 'tuning_auprc': np.float64(0.19596234727735062), 'tuning_brier': np.float64(0.3221564565096756), 'tuning_logloss': 0.8417639044088419}

epoch 2:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 2, 'train_loss': 1.1305034909306504, 'tuning_auroc': np.float64(0.6773989000323519), 'tuning_auprc': np.float64(0.23268189417882015), 'tuning_brier': np.float64(0.21961679906636553), 'tuning_logloss': 0.6326809768143944}

epoch 3:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 3, 'train_loss': 1.0168725677379749, 'tuning_auroc': np.float64(0.6925248417063363), 'tuning_auprc': np.float64(0.25904073161129354), 'tuning_brier': np.float64(0.1920643256039364), 'tuning_logloss': 0.5763153818209847}

epoch 4:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 4, 'train_loss': 0.9299408906116718, 'tuning_auroc': np.float64(0.7091777972916763), 'tuning_auprc': np.float64(0.30148119781294425), 'tuning_brier': np.float64(0.17773137096415065), 'tuning_logloss': 0.5578722984850096}

epoch 5:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 5, 'train_loss': 0.8957608040513062, 'tuning_auroc': np.float64(0.6963571659657068), 'tuning_auprc': np.float64(0.2759320553295642), 'tuning_brier': np.float64(0.2785801414146359), 'tuning_logloss': 0.8160937727977872}

epoch 6:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 6, 'train_loss': 0.8397523753526734, 'tuning_auroc': np.float64(0.701193326246707), 'tuning_auprc': np.float64(0.29714532819128986), 'tuning_brier': np.float64(0.22087861285463012), 'tuning_logloss': 0.6749750029707116}

epoch 7:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 7, 'train_loss': 0.8535657950290819, 'tuning_auroc': np.float64(0.691940657207561), 'tuning_auprc': np.float64(0.303490119591799), 'tuning_brier': np.float64(0.11303661446345212), 'tuning_logloss': 0.38112336157565063}

epoch 8:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 8, 'train_loss': 0.7692417400639232, 'tuning_auroc': np.float64(0.6890604057863845), 'tuning_auprc': np.float64(0.3056388661188818), 'tuning_brier': np.float64(0.1391993262988541), 'tuning_logloss': 0.45101698034065596}

epoch 9:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 9, 'train_loss': 0.6891239196425532, 'tuning_auroc': np.float64(0.6932023848038084), 'tuning_auprc': np.float64(0.30940821374273564), 'tuning_brier': np.float64(0.12418914282375497), 'tuning_logloss': 0.43295296017386115}

epoch 10:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 10, 'train_loss': 0.6057390821416203, 'tuning_auroc': np.float64(0.6826269815593659), 'tuning_auprc': np.float64(0.3038395405933864), 'tuning_brier': np.float64(0.13508869516595276), 'tuning_logloss': 0.45610244161590136}

epoch 11:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 11, 'train_loss': 0.6034509035327086, 'tuning_auroc': np.float64(0.649276701945741), 'tuning_auprc': np.float64(0.30383088771396244), 'tuning_brier': np.float64(0.10989423230698805), 'tuning_logloss': 0.3873884627136608}

epoch 12:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 12, 'train_loss': 0.5235885277208758, 'tuning_auroc': np.float64(0.6561907843046633), 'tuning_auprc': np.float64(0.3012607859989034), 'tuning_brier': np.float64(0.11376949539426254), 'tuning_logloss': 0.46909166307809624}
Early stopping at epoch 12

,task,version,model,calibration,heldout_auroc,heldout_auprc,heldout_brier,heldout_logloss
0,guo_readmission,compressed_first_last,LSTM_2L_numeric,raw,0.717061,0.306284,0.121562,0.409080
1,guo_readmission,compressed_first_last,LSTM_2L_numeric,platt,0.717061,0.306284,0.094857,0.327911

,task,version,model,calibration,top_frac,top_k,events_in_top_k,top_k_event_rate,top_k_lift,event_capture,base_event_rate,n,n_positive
4,guo_readmission,compressed_first_last,LSTM_2L_numeric,platt,0.01,22,15,0.681818,5.740385,0.057692,0.118776,2189,260
5,guo_readmission,compressed_first_last,LSTM_2L_numeric,platt,0.05,110,45,0.409091,3.444231,0.173077,0.118776,2189,260
6,guo_readmission,compressed_first_last,LSTM_2L_numeric,platt,0.10,219,76,0.347032,2.921742,0.292308,0.118776,2189,260
7,guo_readmission,compressed_first_last,LSTM_2L_numeric,platt,0.20,438,129,0.294521,2.479636,0.496154,0.118776,2189,260

====================================================================================================
Experiment: guo_readmission | compressed_first_last | RETAIN_lite_numeric

numeric stats:   0%|          | 0/2608 [00:00<?, ?it/s]

epoch 1:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 1, 'train_loss': 1.1235971785173184, 'tuning_auroc': np.float64(0.7074936451448907), 'tuning_auprc': np.float64(0.2582086721967987), 'tuning_brier': np.float64(0.2596054089509389), 'tuning_logloss': 0.717482208178826}

epoch 2:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 2, 'train_loss': 1.0153200648179868, 'tuning_auroc': np.float64(0.7226972315940288), 'tuning_auprc': np.float64(0.3071186683665697), 'tuning_brier': np.float64(0.16308062688445757), 'tuning_logloss': 0.48929142269957826}

epoch 3:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 3, 'train_loss': 0.9868594357153264, 'tuning_auroc': np.float64(0.7306558210472802), 'tuning_auprc': np.float64(0.3136069345805436), 'tuning_brier': np.float64(0.16500763605436342), 'tuning_logloss': 0.506337770022822}

epoch 4:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 4, 'train_loss': 0.9305112203810273, 'tuning_auroc': np.float64(0.7382483708462355), 'tuning_auprc': np.float64(0.35478407518776417), 'tuning_brier': np.float64(0.16603800374352734), 'tuning_logloss': 0.5089079831077101}

epoch 5:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 5, 'train_loss': 0.8877754095124035, 'tuning_auroc': np.float64(0.7477986781901372), 'tuning_auprc': np.float64(0.37119143610341643), 'tuning_brier': np.float64(0.12040019512720622), 'tuning_logloss': 0.3962361161213865}

epoch 6:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 6, 'train_loss': 0.8126106124098708, 'tuning_auroc': np.float64(0.7427277348985534), 'tuning_auprc': np.float64(0.3558786933955437), 'tuning_brier': np.float64(0.12256133656097101), 'tuning_logloss': 0.3943197205172798}

epoch 7:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 7, 'train_loss': 0.8330927000540059, 'tuning_auroc': np.float64(0.75306003604936), 'tuning_auprc': np.float64(0.36151948011839263), 'tuning_brier': np.float64(0.1461096046709263), 'tuning_logloss': 0.466317647820914}

epoch 8:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 8, 'train_loss': 0.7655011070210759, 'tuning_auroc': np.float64(0.741439201368027), 'tuning_auprc': np.float64(0.35982816077249863), 'tuning_brier': np.float64(0.18240765717937815), 'tuning_logloss': 0.5682746067267963}
Early stopping at epoch 8

,task,version,model,calibration,heldout_auroc,heldout_auprc,heldout_brier,heldout_logloss
0,guo_readmission,compressed_first_last,RETAIN_lite_numeric,raw,0.771829,0.371733,0.115609,0.384210
1,guo_readmission,compressed_first_last,RETAIN_lite_numeric,platt,0.771829,0.371733,0.089774,0.308885

,task,version,model,calibration,top_frac,top_k,events_in_top_k,top_k_event_rate,top_k_lift,event_capture,base_event_rate,n,n_positive
4,guo_readmission,compressed_first_last,RETAIN_lite_numeric,platt,0.01,22,12,0.545455,4.592308,0.046154,0.118776,2189,260
5,guo_readmission,compressed_first_last,RETAIN_lite_numeric,platt,0.05,110,52,0.472727,3.980000,0.200000,0.118776,2189,260
6,guo_readmission,compressed_first_last,RETAIN_lite_numeric,platt,0.10,219,97,0.442922,3.729066,0.373077,0.118776,2189,260
7,guo_readmission,compressed_first_last,RETAIN_lite_numeric,platt,0.20,438,143,0.326484,2.748744,0.550000,0.118776,2189,260

====================================================================================================
Experiment: guo_readmission | compressed_condition_era | GRU_1L_numeric

numeric stats:   0%|          | 0/2608 [00:00<?, ?it/s]

epoch 1:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 1, 'train_loss': 1.2204509544663313, 'tuning_auroc': np.float64(0.6764135508619494), 'tuning_auprc': np.float64(0.24381188302580653), 'tuning_brier': np.float64(0.2064615347720498), 'tuning_logloss': 0.6033135862016825}

epoch 2:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 2, 'train_loss': 1.1193553609092062, 'tuning_auroc': np.float64(0.7015760040671073), 'tuning_auprc': np.float64(0.28515765748140937), 'tuning_brier': np.float64(0.2076483910683323), 'tuning_logloss': 0.6019790940568902}

epoch 3:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 3, 'train_loss': 1.038443040557024, 'tuning_auroc': np.float64(0.7134593520358645), 'tuning_auprc': np.float64(0.3213531026595282), 'tuning_brier': np.float64(0.22372762068054977), 'tuning_logloss': 0.6428113844884341}

epoch 4:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 4, 'train_loss': 0.9918627891598678, 'tuning_auroc': np.float64(0.7083551324120719), 'tuning_auprc': np.float64(0.31241493793055725), 'tuning_brier': np.float64(0.16387451680040413), 'tuning_logloss': 0.5025956922399494}

epoch 5:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 5, 'train_loss': 0.8783664939607062, 'tuning_auroc': np.float64(0.7169903406202338), 'tuning_auprc': np.float64(0.30296922548935173), 'tuning_brier': np.float64(0.17437923961522261), 'tuning_logloss': 0.5281625539032953}

epoch 6:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 6, 'train_loss': 0.7746309694357034, 'tuning_auroc': np.float64(0.7031455377362852), 'tuning_auprc': np.float64(0.2986250162218533), 'tuning_brier': np.float64(0.10963051488392196), 'tuning_logloss': 0.373470072770883}
Early stopping at epoch 6

,task,version,model,calibration,heldout_auroc,heldout_auprc,heldout_brier,heldout_logloss
0,guo_readmission,compressed_condition_era,GRU_1L_numeric,raw,0.684332,0.260262,0.230141,0.658154
1,guo_readmission,compressed_condition_era,GRU_1L_numeric,platt,0.684332,0.260262,0.098214,0.339242

,task,version,model,calibration,top_frac,top_k,events_in_top_k,top_k_event_rate,top_k_lift,event_capture,base_event_rate,n,n_positive
4,guo_readmission,compressed_condition_era,GRU_1L_numeric,platt,0.01,22,12,0.545455,4.592308,0.046154,0.118776,2189,260
5,guo_readmission,compressed_condition_era,GRU_1L_numeric,platt,0.05,110,42,0.381818,3.214615,0.161538,0.118776,2189,260
6,guo_readmission,compressed_condition_era,GRU_1L_numeric,platt,0.10,219,69,0.315068,2.652634,0.265385,0.118776,2189,260
7,guo_readmission,compressed_condition_era,GRU_1L_numeric,platt,0.20,438,109,0.248858,2.095197,0.419231,0.118776,2189,260

====================================================================================================
Experiment: guo_readmission | compressed_condition_era | GRU_2L_numeric

numeric stats:   0%|          | 0/2608 [00:00<?, ?it/s]

epoch 1:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 1, 'train_loss': 1.1821097142812682, 'tuning_auroc': np.float64(0.6846032259555391), 'tuning_auprc': np.float64(0.3102478952484826), 'tuning_brier': np.float64(0.3031203441806026), 'tuning_logloss': 0.804327477996231}

epoch 2:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 2, 'train_loss': 1.1239891288484014, 'tuning_auroc': np.float64(0.6860618385173545), 'tuning_auprc': np.float64(0.31174220302866296), 'tuning_brier': np.float64(0.2544175721422833), 'tuning_logloss': 0.7120214988823845}

epoch 3:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 3, 'train_loss': 1.0185658920828888, 'tuning_auroc': np.float64(0.6875722142626057), 'tuning_auprc': np.float64(0.32084086660849886), 'tuning_brier': np.float64(0.17083839113524157), 'tuning_logloss': 0.5191173834866034}

epoch 4:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 4, 'train_loss': 0.9541260051291164, 'tuning_auroc': np.float64(0.6995979109858113), 'tuning_auprc': np.float64(0.3150938140866942), 'tuning_brier': np.float64(0.3174079254129474), 'tuning_logloss': 0.8712693463928431}

epoch 5:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 5, 'train_loss': 0.8850029247199617, 'tuning_auroc': np.float64(0.6943883163100244), 'tuning_auprc': np.float64(0.310785100601665), 'tuning_brier': np.float64(0.14588598042864812), 'tuning_logloss': 0.46090285876879633}

epoch 6:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 6, 'train_loss': 0.7987606907036247, 'tuning_auroc': np.float64(0.7193252299302122), 'tuning_auprc': np.float64(0.326918681558395), 'tuning_brier': np.float64(0.1670482178513905), 'tuning_logloss': 0.5064045296329798}

epoch 7:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 7, 'train_loss': 0.7899423096238113, 'tuning_auroc': np.float64(0.7051014465961085), 'tuning_auprc': np.float64(0.33149928268297), 'tuning_brier': np.float64(0.14856968779284285), 'tuning_logloss': 0.502610085494709}

epoch 8:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 8, 'train_loss': 0.7182415018721324, 'tuning_auroc': np.float64(0.687727503812913), 'tuning_auprc': np.float64(0.31046411331733753), 'tuning_brier': np.float64(0.15956510540818844), 'tuning_logloss': 0.5355599654136884}

epoch 9:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 9, 'train_loss': 0.6647495523822017, 'tuning_auroc': np.float64(0.6880510237093866), 'tuning_auprc': np.float64(0.31030909721845845), 'tuning_brier': np.float64(0.12054555022439774), 'tuning_logloss': 0.41328919296182404}

epoch 10:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 10, 'train_loss': 0.5776936360066984, 'tuning_auroc': np.float64(0.6987086934417894), 'tuning_auprc': np.float64(0.33325378765300095), 'tuning_brier': np.float64(0.14172628954253008), 'tuning_logloss': 0.46714571548124284}

epoch 11:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 11, 'train_loss': 0.5273941406389562, 'tuning_auroc': np.float64(0.6828451264038453), 'tuning_auprc': np.float64(0.3372655459673819), 'tuning_brier': np.float64(0.1163585668109921), 'tuning_logloss': 0.4689779174190059}

epoch 12:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 12, 'train_loss': 0.465588196566919, 'tuning_auroc': np.float64(0.6760549059481443), 'tuning_auprc': np.float64(0.2948977058649421), 'tuning_brier': np.float64(0.1426716340818031), 'tuning_logloss': 0.5624261920272249}

,task,version,model,calibration,heldout_auroc,heldout_auprc,heldout_brier,heldout_logloss
0,guo_readmission,compressed_condition_era,GRU_2L_numeric,raw,0.710811,0.309747,0.116917,0.455420
1,guo_readmission,compressed_condition_era,GRU_2L_numeric,platt,0.710811,0.309747,0.095218,0.330248

,task,version,model,calibration,top_frac,top_k,events_in_top_k,top_k_event_rate,top_k_lift,event_capture,base_event_rate,n,n_positive
4,guo_readmission,compressed_condition_era,GRU_2L_numeric,platt,0.01,22,14,0.636364,5.357692,0.053846,0.118776,2189,260
5,guo_readmission,compressed_condition_era,GRU_2L_numeric,platt,0.05,110,52,0.472727,3.980000,0.200000,0.118776,2189,260
6,guo_readmission,compressed_condition_era,GRU_2L_numeric,platt,0.10,219,80,0.365297,3.075518,0.307692,0.118776,2189,260
7,guo_readmission,compressed_condition_era,GRU_2L_numeric,platt,0.20,438,122,0.278539,2.345083,0.469231,0.118776,2189,260

====================================================================================================
Experiment: guo_readmission | compressed_condition_era | LSTM_1L_numeric

numeric stats:   0%|          | 0/2608 [00:00<?, ?it/s]

epoch 1:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 1, 'train_loss': 1.26424025035486, 'tuning_auroc': np.float64(0.6293182973610021), 'tuning_auprc': np.float64(0.22739025841930927), 'tuning_brier': np.float64(0.2524680669353671), 'tuning_logloss': 0.6982007864974481}

epoch 2:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 2, 'train_loss': 1.144171243033758, 'tuning_auroc': np.float64(0.6615741553819845), 'tuning_auprc': np.float64(0.26094753810917415), 'tuning_brier': np.float64(0.27170679623095834), 'tuning_logloss': 0.7459969560541344}

epoch 3:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 3, 'train_loss': 1.0356110319858645, 'tuning_auroc': np.float64(0.6632693996395064), 'tuning_auprc': np.float64(0.2747176582287375), 'tuning_brier': np.float64(0.1684104115731017), 'tuning_logloss': 0.5181691111708744}

epoch 4:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 4, 'train_loss': 0.966862192241157, 'tuning_auroc': np.float64(0.6617775107454822), 'tuning_auprc': np.float64(0.29301462756982816), 'tuning_brier': np.float64(0.17360413573686365), 'tuning_logloss': 0.5309713148223737}

epoch 5:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 5, 'train_loss': 0.8906631309811662, 'tuning_auroc': np.float64(0.6730618847344826), 'tuning_auprc': np.float64(0.2933970602167188), 'tuning_brier': np.float64(0.17300230048337792), 'tuning_logloss': 0.5340055782916885}

epoch 6:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 6, 'train_loss': 0.8310017049676035, 'tuning_auroc': np.float64(0.6456495817349909), 'tuning_auprc': np.float64(0.27260343659184105), 'tuning_brier': np.float64(0.13926575401877586), 'tuning_logloss': 0.44901935330708126}

epoch 7:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 7, 'train_loss': 0.7570657904555158, 'tuning_auroc': np.float64(0.6723372001663817), 'tuning_auprc': np.float64(0.2804593365771072), 'tuning_brier': np.float64(0.20185063597796532), 'tuning_logloss': 0.6261396707070939}

epoch 8:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 8, 'train_loss': 0.7096073761945818, 'tuning_auroc': np.float64(0.675943984840782), 'tuning_auprc': np.float64(0.26482893439527305), 'tuning_brier': np.float64(0.21840453640954313), 'tuning_logloss': 0.6677175935073284}
Early stopping at epoch 8

,task,version,model,calibration,heldout_auroc,heldout_auprc,heldout_brier,heldout_logloss
0,guo_readmission,compressed_condition_era,LSTM_1L_numeric,raw,0.703802,0.279066,0.171485,0.529031
1,guo_readmission,compressed_condition_era,LSTM_1L_numeric,platt,0.703802,0.279066,0.096569,0.333536

,task,version,model,calibration,top_frac,top_k,events_in_top_k,top_k_event_rate,top_k_lift,event_capture,base_event_rate,n,n_positive
4,guo_readmission,compressed_condition_era,LSTM_1L_numeric,platt,0.01,22,10,0.454545,3.826923,0.038462,0.118776,2189,260
5,guo_readmission,compressed_condition_era,LSTM_1L_numeric,platt,0.05,110,46,0.418182,3.520769,0.176923,0.118776,2189,260
6,guo_readmission,compressed_condition_era,LSTM_1L_numeric,platt,0.10,219,75,0.342466,2.883298,0.288462,0.118776,2189,260
7,guo_readmission,compressed_condition_era,LSTM_1L_numeric,platt,0.20,438,125,0.285388,2.402749,0.480769,0.118776,2189,260

====================================================================================================
Experiment: guo_readmission | compressed_condition_era | LSTM_2L_numeric

numeric stats:   0%|          | 0/2608 [00:00<?, ?it/s]

epoch 1:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 1, 'train_loss': 1.2140573750181896, 'tuning_auroc': np.float64(0.6673457503350742), 'tuning_auprc': np.float64(0.2593502677561572), 'tuning_brier': np.float64(0.13140819446793092), 'tuning_logloss': 0.4385493416983587}

epoch 2:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 2, 'train_loss': 1.0979045091605768, 'tuning_auroc': np.float64(0.6842741600036972), 'tuning_auprc': np.float64(0.27660346812417014), 'tuning_brier': np.float64(0.18444031002563818), 'tuning_logloss': 0.5528451371065876}

epoch 3:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 3, 'train_loss': 1.0444256547020703, 'tuning_auroc': np.float64(0.6834126727365162), 'tuning_auprc': np.float64(0.26194359183890853), 'tuning_brier': np.float64(0.29156569041491465), 'tuning_logloss': 0.7979724364395944}

epoch 4:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 4, 'train_loss': 0.9663689071085395, 'tuning_auroc': np.float64(0.6908055645422194), 'tuning_auprc': np.float64(0.28395590605363663), 'tuning_brier': np.float64(0.1667845960321645), 'tuning_logloss': 0.5126473202059866}

epoch 5:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 5, 'train_loss': 0.9073565933035641, 'tuning_auroc': np.float64(0.7014965106068308), 'tuning_auprc': np.float64(0.28878921484940595), 'tuning_brier': np.float64(0.26537034251074926), 'tuning_logloss': 0.7708488296475475}

epoch 6:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 6, 'train_loss': 0.832588131471378, 'tuning_auroc': np.float64(0.6969764754818136), 'tuning_auprc': np.float64(0.3056228534077608), 'tuning_brier': np.float64(0.11177771442799281), 'tuning_logloss': 0.3745747403765172}

epoch 7:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 7, 'train_loss': 0.8532018803241777, 'tuning_auroc': np.float64(0.689504090215834), 'tuning_auprc': np.float64(0.276284542501086), 'tuning_brier': np.float64(0.16332949986927867), 'tuning_logloss': 0.5027644953338538}

epoch 8:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 8, 'train_loss': 0.7843787135874353, 'tuning_auroc': np.float64(0.6772565512779037), 'tuning_auprc': np.float64(0.291403304383571), 'tuning_brier': np.float64(0.12306651670189117), 'tuning_logloss': 0.41222034236637395}

epoch 9:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 9, 'train_loss': 0.7000481640783752, 'tuning_auroc': np.float64(0.6859564634653602), 'tuning_auprc': np.float64(0.270883927355574), 'tuning_brier': np.float64(0.21800307999047056), 'tuning_logloss': 0.6672668938684695}
Early stopping at epoch 9

,task,version,model,calibration,heldout_auroc,heldout_auprc,heldout_brier,heldout_logloss
0,guo_readmission,compressed_condition_era,LSTM_2L_numeric,raw,0.743797,0.317975,0.103751,0.347096
1,guo_readmission,compressed_condition_era,LSTM_2L_numeric,platt,0.743797,0.317975,0.093595,0.323116

,task,version,model,calibration,top_frac,top_k,events_in_top_k,top_k_event_rate,top_k_lift,event_capture,base_event_rate,n,n_positive
4,guo_readmission,compressed_condition_era,LSTM_2L_numeric,platt,0.01,22,10,0.454545,3.826923,0.038462,0.118776,2189,260
5,guo_readmission,compressed_condition_era,LSTM_2L_numeric,platt,0.05,110,53,0.481818,4.056538,0.203846,0.118776,2189,260
6,guo_readmission,compressed_condition_era,LSTM_2L_numeric,platt,0.10,219,88,0.401826,3.383070,0.338462,0.118776,2189,260
7,guo_readmission,compressed_condition_era,LSTM_2L_numeric,platt,0.20,438,131,0.299087,2.518080,0.503846,0.118776,2189,260

====================================================================================================
Experiment: guo_readmission | compressed_condition_era | RETAIN_lite_numeric

numeric stats:   0%|          | 0/2608 [00:00<?, ?it/s]

epoch 1:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 1, 'train_loss': 1.1370531589519688, 'tuning_auroc': np.float64(0.7084882377409069), 'tuning_auprc': np.float64(0.27376755524492563), 'tuning_brier': np.float64(0.1303124796756225), 'tuning_logloss': 0.41703955944283483}

epoch 2:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 2, 'train_loss': 1.0078605769610987, 'tuning_auroc': np.float64(0.719489762906133), 'tuning_auprc': np.float64(0.30880151905044945), 'tuning_brier': np.float64(0.15569757755707594), 'tuning_logloss': 0.4821049840145639}

epoch 3:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 3, 'train_loss': 0.9820296742567202, 'tuning_auroc': np.float64(0.734769145445302), 'tuning_auprc': np.float64(0.3626226880755167), 'tuning_brier': np.float64(0.12321211156999229), 'tuning_logloss': 0.3947905222691918}

epoch 4:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 4, 'train_loss': 0.8865685026820113, 'tuning_auroc': np.float64(0.7363091001525165), 'tuning_auprc': np.float64(0.37923395969293666), 'tuning_brier': np.float64(0.15288180131426363), 'tuning_logloss': 0.4714057280341672}

epoch 5:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 5, 'train_loss': 0.9252302722959984, 'tuning_auroc': np.float64(0.7346841059296576), 'tuning_auprc': np.float64(0.37276081066539946), 'tuning_brier': np.float64(0.11339912495425833), 'tuning_logloss': 0.38042146147874356}

epoch 6:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 6, 'train_loss': 0.8436286529389824, 'tuning_auroc': np.float64(0.7445302028931923), 'tuning_auprc': np.float64(0.3718300484280387), 'tuning_brier': np.float64(0.1590754612099167), 'tuning_logloss': 0.48642184454177745}

epoch 7:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 7, 'train_loss': 0.7620626299119577, 'tuning_auroc': np.float64(0.7462698155936591), 'tuning_auprc': np.float64(0.3858403358946203), 'tuning_brier': np.float64(0.14146030940991447), 'tuning_logloss': 0.4448314668839909}

epoch 8:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 8, 'train_loss': 0.7231497373886224, 'tuning_auroc': np.float64(0.7451606045200351), 'tuning_auprc': np.float64(0.39812289870805473), 'tuning_brier': np.float64(0.27925260843908606), 'tuning_logloss': 0.8338078752397717}

epoch 9:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 9, 'train_loss': 0.6907941942534795, 'tuning_auroc': np.float64(0.7412099644128113), 'tuning_auprc': np.float64(0.3937748337008284), 'tuning_brier': np.float64(0.12828819369116887), 'tuning_logloss': 0.41285991019159785}

epoch 10:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 10, 'train_loss': 0.6139348421881838, 'tuning_auroc': np.float64(0.7448481767342977), 'tuning_auprc': np.float64(0.401068753871936), 'tuning_brier': np.float64(0.13879880042998582), 'tuning_logloss': 0.4555312561280738}

epoch 11:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 11, 'train_loss': 0.5801043339618822, 'tuning_auroc': np.float64(0.7490335998521052), 'tuning_auprc': np.float64(0.39309333728061524), 'tuning_brier': np.float64(0.1369229177183083), 'tuning_logloss': 0.459508753374722}

epoch 12:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 12, 'train_loss': 0.562195029791172, 'tuning_auroc': np.float64(0.7349798955492906), 'tuning_auprc': np.float64(0.3851232867672352), 'tuning_brier': np.float64(0.2061144506275407), 'tuning_logloss': 0.6424427711034917}

,task,version,model,calibration,heldout_auroc,heldout_auprc,heldout_brier,heldout_logloss
0,guo_readmission,compressed_condition_era,RETAIN_lite_numeric,raw,0.754528,0.345361,0.138544,0.450953
1,guo_readmission,compressed_condition_era,RETAIN_lite_numeric,platt,0.754528,0.345361,0.091972,0.316718

,task,version,model,calibration,top_frac,top_k,events_in_top_k,top_k_event_rate,top_k_lift,event_capture,base_event_rate,n,n_positive
4,guo_readmission,compressed_condition_era,RETAIN_lite_numeric,platt,0.01,22,13,0.590909,4.975000,0.050000,0.118776,2189,260
5,guo_readmission,compressed_condition_era,RETAIN_lite_numeric,platt,0.05,110,58,0.527273,4.439231,0.223077,0.118776,2189,260
6,guo_readmission,compressed_condition_era,RETAIN_lite_numeric,platt,0.10,219,89,0.406393,3.421514,0.342308,0.118776,2189,260
7,guo_readmission,compressed_condition_era,RETAIN_lite_numeric,platt,0.20,438,134,0.305936,2.575746,0.515385,0.118776,2189,260

====================================================================================================
Experiment: guo_readmission | compressed_hybrid | GRU_1L_numeric

numeric stats:   0%|          | 0/2608 [00:00<?, ?it/s]

epoch 1:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 1, 'train_loss': 1.1863575461434155, 'tuning_auroc': np.float64(0.6504580117391505), 'tuning_auprc': np.float64(0.2567163917941422), 'tuning_brier': np.float64(0.2698513384449262), 'tuning_logloss': 0.735166528730676}

epoch 2:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 2, 'train_loss': 1.0951769809897354, 'tuning_auroc': np.float64(0.6706456532791052), 'tuning_auprc': np.float64(0.2759452818083996), 'tuning_brier': np.float64(0.14699933791477993), 'tuning_logloss': 0.46209445807393534}

epoch 3:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 3, 'train_loss': 1.0254364584277316, 'tuning_auroc': np.float64(0.6811018163331332), 'tuning_auprc': np.float64(0.2953447021061259), 'tuning_brier': np.float64(0.20525573375198225), 'tuning_logloss': 0.6011962550557364}

epoch 4:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 4, 'train_loss': 0.9524270092568746, 'tuning_auroc': np.float64(0.681373573046171), 'tuning_auprc': np.float64(0.314210052403964), 'tuning_brier': np.float64(0.13802922772120216), 'tuning_logloss': 0.4397461312413434}

epoch 5:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 5, 'train_loss': 0.8849681339612822, 'tuning_auroc': np.float64(0.6880769053011047), 'tuning_auprc': np.float64(0.3382729138915305), 'tuning_brier': np.float64(0.14897035535851263), 'tuning_logloss': 0.46810047538287763}

epoch 6:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 6, 'train_loss': 0.8091389302436899, 'tuning_auroc': np.float64(0.6853075749872903), 'tuning_auprc': np.float64(0.31913976976500413), 'tuning_brier': np.float64(0.11130672031458715), 'tuning_logloss': 0.38816471354596443}

epoch 7:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 7, 'train_loss': 0.7543556781076803, 'tuning_auroc': np.float64(0.6967620280075796), 'tuning_auprc': np.float64(0.3325076005596831), 'tuning_brier': np.float64(0.11209109138614998), 'tuning_logloss': 0.38789848243105396}

epoch 8:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 8, 'train_loss': 0.6655435814726643, 'tuning_auroc': np.float64(0.6976845218838101), 'tuning_auprc': np.float64(0.33926488005974514), 'tuning_brier': np.float64(0.13366800183021657), 'tuning_logloss': 0.44978241250692336}

epoch 9:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 9, 'train_loss': 0.5669067755523252, 'tuning_auroc': np.float64(0.7039940842076073), 'tuning_auprc': np.float64(0.3471336968949809), 'tuning_brier': np.float64(0.12354573394672658), 'tuning_logloss': 0.46652536232795805}

epoch 10:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 10, 'train_loss': 0.487794041270163, 'tuning_auroc': np.float64(0.7107787586079402), 'tuning_auprc': np.float64(0.34139011817459053), 'tuning_brier': np.float64(0.19190103991368967), 'tuning_logloss': 0.7208694625916137}

epoch 11:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 11, 'train_loss': 0.4962814741926949, 'tuning_auroc': np.float64(0.6825400933585987), 'tuning_auprc': np.float64(0.3183834188600343), 'tuning_brier': np.float64(0.14461996453599515), 'tuning_logloss': 0.5240281142561016}

epoch 12:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 12, 'train_loss': 0.40520061688815673, 'tuning_auroc': np.float64(0.6875851550584647), 'tuning_auprc': np.float64(0.3191929779995146), 'tuning_brier': np.float64(0.128957786490766), 'tuning_logloss': 0.559961497282458}
Early stopping at epoch 12

,task,version,model,calibration,heldout_auroc,heldout_auprc,heldout_brier,heldout_logloss
0,guo_readmission,compressed_hybrid,GRU_1L_numeric,raw,0.712462,0.284516,0.123639,0.448130
1,guo_readmission,compressed_hybrid,GRU_1L_numeric,platt,0.712462,0.284516,0.096198,0.331419

,task,version,model,calibration,top_frac,top_k,events_in_top_k,top_k_event_rate,top_k_lift,event_capture,base_event_rate,n,n_positive
4,guo_readmission,compressed_hybrid,GRU_1L_numeric,platt,0.01,22,12,0.545455,4.592308,0.046154,0.118776,2189,260
5,guo_readmission,compressed_hybrid,GRU_1L_numeric,platt,0.05,110,45,0.409091,3.444231,0.173077,0.118776,2189,260
6,guo_readmission,compressed_hybrid,GRU_1L_numeric,platt,0.10,219,79,0.360731,3.037074,0.303846,0.118776,2189,260
7,guo_readmission,compressed_hybrid,GRU_1L_numeric,platt,0.20,438,116,0.264840,2.229751,0.446154,0.118776,2189,260

====================================================================================================
Experiment: guo_readmission | compressed_hybrid | GRU_2L_numeric

numeric stats:   0%|          | 0/2608 [00:00<?, ?it/s]

epoch 1:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 1, 'train_loss': 1.18396255155889, 'tuning_auroc': np.float64(0.6771733604473816), 'tuning_auprc': np.float64(0.2327496885461831), 'tuning_brier': np.float64(0.19664403264067176), 'tuning_logloss': 0.5772703608178732}

epoch 2:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 2, 'train_loss': 1.1166598913146228, 'tuning_auroc': np.float64(0.7111484956324814), 'tuning_auprc': np.float64(0.28715870922987063), 'tuning_brier': np.float64(0.2176307725466391), 'tuning_logloss': 0.6288751756673288}

epoch 3:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 3, 'train_loss': 1.0155937940609165, 'tuning_auroc': np.float64(0.7251264038452652), 'tuning_auprc': np.float64(0.31783872831614324), 'tuning_brier': np.float64(0.2190814161815867), 'tuning_logloss': 0.6554844115434506}

epoch 4:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 4, 'train_loss': 0.9818886031464833, 'tuning_auroc': np.float64(0.7116365485048759), 'tuning_auprc': np.float64(0.3013465907714269), 'tuning_brier': np.float64(0.1859019049007956), 'tuning_logloss': 0.5582605798100845}

epoch 5:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 5, 'train_loss': 0.8965385338155235, 'tuning_auroc': np.float64(0.7243037389656606), 'tuning_auprc': np.float64(0.3184935449193664), 'tuning_brier': np.float64(0.14954796230043774), 'tuning_logloss': 0.4664492342926179}

epoch 6:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 6, 'train_loss': 0.8119935411505583, 'tuning_auroc': np.float64(0.7054157230669685), 'tuning_auprc': np.float64(0.3101421698239228), 'tuning_brier': np.float64(0.12882117230908582), 'tuning_logloss': 0.4211601313199426}

epoch 7:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 7, 'train_loss': 0.7439323574668024, 'tuning_auroc': np.float64(0.7098414752507279), 'tuning_auprc': np.float64(0.30455985562904236), 'tuning_brier': np.float64(0.1777083107987134), 'tuning_logloss': 0.5462148349236754}

epoch 8:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 8, 'train_loss': 0.7103963883184805, 'tuning_auroc': np.float64(0.7196127004667929), 'tuning_auprc': np.float64(0.3238882808987207), 'tuning_brier': np.float64(0.12967150328227922), 'tuning_logloss': 0.42213433646032456}

epoch 9:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 9, 'train_loss': 0.6194077650221382, 'tuning_auroc': np.float64(0.7159846559134815), 'tuning_auprc': np.float64(0.3275125580662692), 'tuning_brier': np.float64(0.13356443107195), 'tuning_logloss': 0.4502635900600824}

epoch 10:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 10, 'train_loss': 0.543568331475665, 'tuning_auroc': np.float64(0.689988445717983), 'tuning_auprc': np.float64(0.30881238346445), 'tuning_brier': np.float64(0.14018997238329614), 'tuning_logloss': 0.5816806511164764}

epoch 11:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 11, 'train_loss': 0.466924755584176, 'tuning_auroc': np.float64(0.6983944169709294), 'tuning_auprc': np.float64(0.31447149694591936), 'tuning_brier': np.float64(0.14289397955609157), 'tuning_logloss': 0.5430725662292966}

epoch 12:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 12, 'train_loss': 0.42308816350087886, 'tuning_auroc': np.float64(0.7046744003327634), 'tuning_auprc': np.float64(0.3254457479255836), 'tuning_brier': np.float64(0.21950228225612037), 'tuning_logloss': 0.7829346893902136}
Early stopping at epoch 12

,task,version,model,calibration,heldout_auroc,heldout_auprc,heldout_brier,heldout_logloss
0,guo_readmission,compressed_hybrid,GRU_2L_numeric,raw,0.735951,0.322428,0.1275,0.422621
1,guo_readmission,compressed_hybrid,GRU_2L_numeric,platt,0.735951,0.322428,0.0941,0.324251

,task,version,model,calibration,top_frac,top_k,events_in_top_k,top_k_event_rate,top_k_lift,event_capture,base_event_rate,n,n_positive
4,guo_readmission,compressed_hybrid,GRU_2L_numeric,platt,0.01,22,17,0.772727,6.505769,0.065385,0.118776,2189,260
5,guo_readmission,compressed_hybrid,GRU_2L_numeric,platt,0.05,110,51,0.463636,3.903462,0.196154,0.118776,2189,260
6,guo_readmission,compressed_hybrid,GRU_2L_numeric,platt,0.10,219,78,0.356164,2.998630,0.300000,0.118776,2189,260
7,guo_readmission,compressed_hybrid,GRU_2L_numeric,platt,0.20,438,124,0.283105,2.383527,0.476923,0.118776,2189,260

====================================================================================================
Experiment: guo_readmission | compressed_hybrid | LSTM_1L_numeric

numeric stats:   0%|          | 0/2608 [00:00<?, ?it/s]

epoch 1:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 1, 'train_loss': 1.2128726353005665, 'tuning_auroc': np.float64(0.6341285760502842), 'tuning_auprc': np.float64(0.23809184848716444), 'tuning_brier': np.float64(0.15408359789563195), 'tuning_logloss': 0.48932853863038334}

epoch 2:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 2, 'train_loss': 1.1195967669894056, 'tuning_auroc': np.float64(0.6782252622822018), 'tuning_auprc': np.float64(0.2720413144407905), 'tuning_brier': np.float64(0.22380178833930245), 'tuning_logloss': 0.6402221580794272}

epoch 3:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 3, 'train_loss': 1.0087574909373027, 'tuning_auroc': np.float64(0.6847437260248649), 'tuning_auprc': np.float64(0.26859183568512274), 'tuning_brier': np.float64(0.2103391791675232), 'tuning_logloss': 0.6097799360971193}

epoch 4:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 4, 'train_loss': 0.9251368947145415, 'tuning_auroc': np.float64(0.6944936913620188), 'tuning_auprc': np.float64(0.2800228266017566), 'tuning_brier': np.float64(0.1423346209523244), 'tuning_logloss': 0.45428002887273033}

epoch 5:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 5, 'train_loss': 0.90161911598066, 'tuning_auroc': np.float64(0.7017294449322918), 'tuning_auprc': np.float64(0.29657087823769135), 'tuning_brier': np.float64(0.1624913264423681), 'tuning_logloss': 0.5011963351811232}

epoch 6:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 6, 'train_loss': 0.8205691939446984, 'tuning_auroc': np.float64(0.7080316125155983), 'tuning_auprc': np.float64(0.29029468028229055), 'tuning_brier': np.float64(0.17920279538398828), 'tuning_logloss': 0.550036677412233}

epoch 7:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 7, 'train_loss': 0.7625018467263478, 'tuning_auroc': np.float64(0.6924878680038822), 'tuning_auprc': np.float64(0.2807656446695939), 'tuning_brier': np.float64(0.13478720236038405), 'tuning_logloss': 0.43677455176025565}

epoch 8:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 8, 'train_loss': 0.7414131733339008, 'tuning_auroc': np.float64(0.6947284743726025), 'tuning_auprc': np.float64(0.25995395599562376), 'tuning_brier': np.float64(0.34228017043237996), 'tuning_logloss': 1.0145599062184156}
Early stopping at epoch 8

,task,version,model,calibration,heldout_auroc,heldout_auprc,heldout_brier,heldout_logloss
0,guo_readmission,compressed_hybrid,LSTM_1L_numeric,raw,0.691161,0.26799,0.166392,0.510372
1,guo_readmission,compressed_hybrid,LSTM_1L_numeric,platt,0.691161,0.26799,0.097389,0.336644

,task,version,model,calibration,top_frac,top_k,events_in_top_k,top_k_event_rate,top_k_lift,event_capture,base_event_rate,n,n_positive
4,guo_readmission,compressed_hybrid,LSTM_1L_numeric,platt,0.01,22,12,0.545455,4.592308,0.046154,0.118776,2189,260
5,guo_readmission,compressed_hybrid,LSTM_1L_numeric,platt,0.05,110,45,0.409091,3.444231,0.173077,0.118776,2189,260
6,guo_readmission,compressed_hybrid,LSTM_1L_numeric,platt,0.10,219,75,0.342466,2.883298,0.288462,0.118776,2189,260
7,guo_readmission,compressed_hybrid,LSTM_1L_numeric,platt,0.20,438,116,0.264840,2.229751,0.446154,0.118776,2189,260

====================================================================================================
Experiment: guo_readmission | compressed_hybrid | LSTM_2L_numeric

numeric stats:   0%|          | 0/2608 [00:00<?, ?it/s]

epoch 1:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 1, 'train_loss': 1.2092698717989572, 'tuning_auroc': np.float64(0.6533761612053427), 'tuning_auprc': np.float64(0.2622343390205047), 'tuning_brier': np.float64(0.3033937867892192), 'tuning_logloss': 0.8088767203498608}

epoch 2:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 2, 'train_loss': 1.1422439173954289, 'tuning_auroc': np.float64(0.6786855848777558), 'tuning_auprc': np.float64(0.28118442071200467), 'tuning_brier': np.float64(0.2069117935379199), 'tuning_logloss': 0.6058383137763599}

epoch 3:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 3, 'train_loss': 1.0387423641797973, 'tuning_auroc': np.float64(0.68290983038314), 'tuning_auprc': np.float64(0.29217899868912217), 'tuning_brier': np.float64(0.128911177136261), 'tuning_logloss': 0.4242642986885867}

epoch 4:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 4, 'train_loss': 0.9642421468728926, 'tuning_auroc': np.float64(0.6906243934001941), 'tuning_auprc': np.float64(0.28590680649421735), 'tuning_brier': np.float64(0.20294558190483142), 'tuning_logloss': 0.6019858589575088}

epoch 5:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 5, 'train_loss': 0.884354070555873, 'tuning_auroc': np.float64(0.7024079123723251), 'tuning_auprc': np.float64(0.28154628514061014), 'tuning_brier': np.float64(0.19011869736670833), 'tuning_logloss': 0.570869357507986}

epoch 6:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 6, 'train_loss': 0.8502894805335417, 'tuning_auroc': np.float64(0.6926302167583307), 'tuning_auprc': np.float64(0.2927526934394272), 'tuning_brier': np.float64(0.14499156187106874), 'tuning_logloss': 0.4603974942290949}

epoch 7:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 7, 'train_loss': 0.7959713168987413, 'tuning_auroc': np.float64(0.6859731016314645), 'tuning_auprc': np.float64(0.28992184229966467), 'tuning_brier': np.float64(0.15229985065646728), 'tuning_logloss': 0.4782858095019321}

epoch 8:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 8, 'train_loss': 0.7124182839946049, 'tuning_auroc': np.float64(0.7005869575264593), 'tuning_auprc': np.float64(0.29034236121248447), 'tuning_brier': np.float64(0.1766021988512075), 'tuning_logloss': 0.5580906051597053}

epoch 9:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 9, 'train_loss': 0.7349290942273489, 'tuning_auroc': np.float64(0.6860729306280907), 'tuning_auprc': np.float64(0.2934613341821099), 'tuning_brier': np.float64(0.14431794295976408), 'tuning_logloss': 0.4662201174229225}

epoch 10:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 10, 'train_loss': 0.6400513367318525, 'tuning_auroc': np.float64(0.6662402366316956), 'tuning_auprc': np.float64(0.2860274165264949), 'tuning_brier': np.float64(0.13656828933722023), 'tuning_logloss': 0.4610788556255565}

epoch 11:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 11, 'train_loss': 0.5838595119918265, 'tuning_auroc': np.float64(0.6516947820862413), 'tuning_auprc': np.float64(0.2760181524424925), 'tuning_brier': np.float64(0.11577595324176138), 'tuning_logloss': 0.4274888802593367}

epoch 12:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 12, 'train_loss': 0.571277394981646, 'tuning_auroc': np.float64(0.6636890511623608), 'tuning_auprc': np.float64(0.26588540432503077), 'tuning_brier': np.float64(0.13313477939492457), 'tuning_logloss': 0.464999192487175}
Early stopping at epoch 12

,task,version,model,calibration,heldout_auroc,heldout_auprc,heldout_brier,heldout_logloss
0,guo_readmission,compressed_hybrid,LSTM_2L_numeric,raw,0.725083,0.30976,0.136248,0.434730
1,guo_readmission,compressed_hybrid,LSTM_2L_numeric,platt,0.725083,0.30976,0.094550,0.326209

,task,version,model,calibration,top_frac,top_k,events_in_top_k,top_k_event_rate,top_k_lift,event_capture,base_event_rate,n,n_positive
4,guo_readmission,compressed_hybrid,LSTM_2L_numeric,platt,0.01,22,13,0.590909,4.975000,0.050000,0.118776,2189,260
5,guo_readmission,compressed_hybrid,LSTM_2L_numeric,platt,0.05,110,48,0.436364,3.673846,0.184615,0.118776,2189,260
6,guo_readmission,compressed_hybrid,LSTM_2L_numeric,platt,0.10,219,80,0.365297,3.075518,0.307692,0.118776,2189,260
7,guo_readmission,compressed_hybrid,LSTM_2L_numeric,platt,0.20,438,123,0.280822,2.364305,0.473077,0.118776,2189,260

====================================================================================================
Experiment: guo_readmission | compressed_hybrid | RETAIN_lite_numeric

numeric stats:   0%|          | 0/2608 [00:00<?, ?it/s]

epoch 1:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 1, 'train_loss': 1.139774502414029, 'tuning_auroc': np.float64(0.7081480796783287), 'tuning_auprc': np.float64(0.26453922734921054), 'tuning_brier': np.float64(0.13276859707684507), 'tuning_logloss': 0.4310164080270485}

epoch 2:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 2, 'train_loss': 1.0024049834507267, 'tuning_auroc': np.float64(0.7257124370291631), 'tuning_auprc': np.float64(0.287540014233291), 'tuning_brier': np.float64(0.17974936098290742), 'tuning_logloss': 0.5393212293539402}

epoch 3:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 3, 'train_loss': 0.9634962314512672, 'tuning_auroc': np.float64(0.709192586772658), 'tuning_auprc': np.float64(0.29993969782289087), 'tuning_brier': np.float64(0.15965210155858764), 'tuning_logloss': 0.4944746428064291}

epoch 4:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 4, 'train_loss': 0.9191422113558141, 'tuning_auroc': np.float64(0.7418070897074456), 'tuning_auprc': np.float64(0.33512943981805743), 'tuning_brier': np.float64(0.21311598206090032), 'tuning_logloss': 0.631747311206021}

epoch 5:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 5, 'train_loss': 0.8851365050891551, 'tuning_auroc': np.float64(0.7372759624716919), 'tuning_auprc': np.float64(0.36428755542265795), 'tuning_brier': np.float64(0.15556593911432676), 'tuning_logloss': 0.4840516964386282}

epoch 6:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 6, 'train_loss': 0.8680842729603372, 'tuning_auroc': np.float64(0.7448056569764755), 'tuning_auprc': np.float64(0.3709027596065209), 'tuning_brier': np.float64(0.16555347392067896), 'tuning_logloss': 0.5139634488467943}

epoch 7:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 7, 'train_loss': 0.809757992443515, 'tuning_auroc': np.float64(0.7425428663862828), 'tuning_auprc': np.float64(0.35874267666425663), 'tuning_brier': np.float64(0.10252863131509629), 'tuning_logloss': 0.34805614522542466}

epoch 8:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 8, 'train_loss': 0.7624323262674052, 'tuning_auroc': np.float64(0.7525091278827933), 'tuning_auprc': np.float64(0.3754605547434313), 'tuning_brier': np.float64(0.1490759236385983), 'tuning_logloss': 0.4729727853834536}

epoch 9:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 9, 'train_loss': 0.7052131813110375, 'tuning_auroc': np.float64(0.7511041271895365), 'tuning_auprc': np.float64(0.3798282841423029), 'tuning_brier': np.float64(0.12078542330227943), 'tuning_logloss': 0.39414145137227263}

epoch 10:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 10, 'train_loss': 0.6499491188584304, 'tuning_auroc': np.float64(0.7339705134722928), 'tuning_auprc': np.float64(0.3667829171865475), 'tuning_brier': np.float64(0.1236149921341947), 'tuning_logloss': 0.4095983001176109}

epoch 11:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 11, 'train_loss': 0.5911594313092348, 'tuning_auroc': np.float64(0.7425502611267736), 'tuning_auprc': np.float64(0.37773305548207853), 'tuning_brier': np.float64(0.100846035343353), 'tuning_logloss': 0.35247395990139324}

epoch 12:   0%|          | 0/82 [00:00<?, ?it/s]

{'epoch': 12, 'train_loss': 0.5663784008200575, 'tuning_auroc': np.float64(0.7509358968433701), 'tuning_auprc': np.float64(0.38235645186459877), 'tuning_brier': np.float64(0.1485840289323279), 'tuning_logloss': 0.5009142125182785}

,task,version,model,calibration,heldout_auroc,heldout_auprc,heldout_brier,heldout_logloss
0,guo_readmission,compressed_hybrid,RETAIN_lite_numeric,raw,0.777451,0.364969,0.143386,0.485297
1,guo_readmission,compressed_hybrid,RETAIN_lite_numeric,platt,0.777451,0.364969,0.091712,0.313266

,task,version,model,calibration,top_frac,top_k,events_in_top_k,top_k_event_rate,top_k_lift,event_capture,base_event_rate,n,n_positive
4,guo_readmission,compressed_hybrid,RETAIN_lite_numeric,platt,0.01,22,15,0.681818,5.740385,0.057692,0.118776,2189,260
5,guo_readmission,compressed_hybrid,RETAIN_lite_numeric,platt,0.05,110,56,0.509091,4.286154,0.215385,0.118776,2189,260
6,guo_readmission,compressed_hybrid,RETAIN_lite_numeric,platt,0.10,219,83,0.378995,3.190850,0.319231,0.118776,2189,260
7,guo_readmission,compressed_hybrid,RETAIN_lite_numeric,platt,0.20,438,137,0.312785,2.633412,0.526923,0.118776,2189,260

====================================================================================================
Experiment: guo_icu | raw | GRU_1L_numeric

numeric stats:   0%|          | 0/2402 [00:00<?, ?it/s]

epoch 1:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 1, 'train_loss': 1.6679464186492718, 'tuning_auroc': np.float64(0.5541537267080745), 'tuning_auprc': np.float64(0.08000956259853065), 'tuning_brier': np.float64(0.0668855177780699), 'tuning_logloss': 0.28263393111293006}

epoch 2:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 2, 'train_loss': 1.4648750500851555, 'tuning_auroc': np.float64(0.5515916149068323), 'tuning_auprc': np.float64(0.08269516238240103), 'tuning_brier': np.float64(0.28267421111471885), 'tuning_logloss': 0.7601233292196692}

epoch 3:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 3, 'train_loss': 1.3316805535241176, 'tuning_auroc': np.float64(0.5797526619343389), 'tuning_auprc': np.float64(0.08906643600367448), 'tuning_brier': np.float64(0.3259809480478821), 'tuning_logloss': 0.8508315239069794}

epoch 4:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 4, 'train_loss': 1.3213465900013321, 'tuning_auroc': np.float64(0.6115295031055901), 'tuning_auprc': np.float64(0.08681547645202782), 'tuning_brier': np.float64(0.160388971103916), 'tuning_logloss': 0.5069641616398834}

epoch 5:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 5, 'train_loss': 1.2650214892468954, 'tuning_auroc': np.float64(0.5865073203194321), 'tuning_auprc': np.float64(0.08779267848361834), 'tuning_brier': np.float64(0.1878800446788332), 'tuning_logloss': 0.5627863182431558}

epoch 6:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 6, 'train_loss': 1.5001638633640189, 'tuning_auroc': np.float64(0.6145075421472938), 'tuning_auprc': np.float64(0.09264431628687711), 'tuning_brier': np.float64(0.11412696080937161), 'tuning_logloss': 0.3942560235651619}

epoch 7:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 7, 'train_loss': 1.2339974167315584, 'tuning_auroc': np.float64(0.6235442546583851), 'tuning_auprc': np.float64(0.0868776502095252), 'tuning_brier': np.float64(0.17233399744253092), 'tuning_logloss': 0.5197215890178604}

epoch 8:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 8, 'train_loss': 1.1871464097578275, 'tuning_auroc': np.float64(0.6787655279503104), 'tuning_auprc': np.float64(0.09940262051827017), 'tuning_brier': np.float64(0.08787222370105335), 'tuning_logloss': 0.31495237724927333}

epoch 9:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 9, 'train_loss': 1.1081837858808667, 'tuning_auroc': np.float64(0.6737189440993788), 'tuning_auprc': np.float64(0.12222747294332431), 'tuning_brier': np.float64(0.043328497254711246), 'tuning_logloss': 0.18333329658930014}

epoch 10:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 10, 'train_loss': 1.0602728161764772, 'tuning_auroc': np.float64(0.7051907719609584), 'tuning_auprc': np.float64(0.16483002633999613), 'tuning_brier': np.float64(0.09562326343591772), 'tuning_logloss': 0.32833341558527424}

epoch 11:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 11, 'train_loss': 0.7877401559564629, 'tuning_auroc': np.float64(0.7428072315882874), 'tuning_auprc': np.float64(0.22631815999937174), 'tuning_brier': np.float64(0.05522513053406974), 'tuning_logloss': 0.21831010839176052}

epoch 12:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 12, 'train_loss': 0.9340010403998589, 'tuning_auroc': np.float64(0.7765084294587401), 'tuning_auprc': np.float64(0.23892555039103808), 'tuning_brier': np.float64(0.07503524448446276), 'tuning_logloss': 0.2735274456417815}

,task,version,model,calibration,heldout_auroc,heldout_auprc,heldout_brier,heldout_logloss
0,guo_icu,raw,GRU_1L_numeric,raw,0.724602,0.180168,0.079329,0.289808
1,guo_icu,raw,GRU_1L_numeric,platt,0.724602,0.180168,0.037878,0.156879

,task,version,model,calibration,top_frac,top_k,events_in_top_k,top_k_event_rate,top_k_lift,event_capture,base_event_rate,n,n_positive
4,guo_icu,raw,GRU_1L_numeric,platt,0.01,21,7,0.333333,7.988235,0.082353,0.041728,2037,85
5,guo_icu,raw,GRU_1L_numeric,platt,0.05,102,21,0.205882,4.933910,0.247059,0.041728,2037,85
6,guo_icu,raw,GRU_1L_numeric,platt,0.10,204,33,0.161765,3.876644,0.388235,0.041728,2037,85
7,guo_icu,raw,GRU_1L_numeric,platt,0.20,408,44,0.107843,2.584429,0.517647,0.041728,2037,85

====================================================================================================
Experiment: guo_icu | raw | GRU_2L_numeric

numeric stats:   0%|          | 0/2402 [00:00<?, ?it/s]

epoch 1:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 1, 'train_loss': 1.401425245168962, 'tuning_auroc': np.float64(0.6056011535048802), 'tuning_auprc': np.float64(0.07592487781359153), 'tuning_brier': np.float64(0.09375285815333079), 'tuning_logloss': 0.3585391756543657}

epoch 2:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 2, 'train_loss': 1.358194826464904, 'tuning_auroc': np.float64(0.6397182786157942), 'tuning_auprc': np.float64(0.07644235309843724), 'tuning_brier': np.float64(0.11776952940378183), 'tuning_logloss': 0.41708984270183286}

epoch 3:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 3, 'train_loss': 1.3702082390847958, 'tuning_auroc': np.float64(0.648147737355812), 'tuning_auprc': np.float64(0.0845012988029526), 'tuning_brier': np.float64(0.19591497939605487), 'tuning_logloss': 0.5842672961652418}

epoch 4:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 4, 'train_loss': 1.3495271296093339, 'tuning_auroc': np.float64(0.6572648624667257), 'tuning_auprc': np.float64(0.08613794472565023), 'tuning_brier': np.float64(0.19120898758146798), 'tuning_logloss': 0.5744464884474905}

epoch 5:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 5, 'train_loss': 1.2924837085761522, 'tuning_auroc': np.float64(0.6343777728482696), 'tuning_auprc': np.float64(0.10396661874477642), 'tuning_brier': np.float64(0.11321472630453552), 'tuning_logloss': 0.4065219488071404}

epoch 6:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 6, 'train_loss': 1.321836217845741, 'tuning_auroc': np.float64(0.7370674356699202), 'tuning_auprc': np.float64(0.21170776001694375), 'tuning_brier': np.float64(0.22856492663745284), 'tuning_logloss': 0.6485451751349544}

epoch 7:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 7, 'train_loss': 1.2304905786326057, 'tuning_auroc': np.float64(0.7490073203194321), 'tuning_auprc': np.float64(0.20553367012260537), 'tuning_brier': np.float64(0.21277791783848515), 'tuning_logloss': 0.6213971161636812}

epoch 8:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 8, 'train_loss': 1.1030871843625056, 'tuning_auroc': np.float64(0.7654225820763088), 'tuning_auprc': np.float64(0.2272689928671227), 'tuning_brier': np.float64(0.11778607668697168), 'tuning_logloss': 0.38623045392001754}

epoch 9:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 9, 'train_loss': 1.043180109246781, 'tuning_auroc': np.float64(0.7166537267080745), 'tuning_auprc': np.float64(0.19284357600040228), 'tuning_brier': np.float64(0.043120414544293814), 'tuning_logloss': 0.17510605635691795}

epoch 10:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 10, 'train_loss': 0.9373677549883723, 'tuning_auroc': np.float64(0.7510370452528838), 'tuning_auprc': np.float64(0.2416692538272892), 'tuning_brier': np.float64(0.050822929105783426), 'tuning_logloss': 0.1996736426109623}

epoch 11:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 11, 'train_loss': 0.958808890641912, 'tuning_auroc': np.float64(0.7737355811889974), 'tuning_auprc': np.float64(0.2269821373789367), 'tuning_brier': np.float64(0.09254623845707377), 'tuning_logloss': 0.31674283737106124}

epoch 12:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 12, 'train_loss': 0.8005701722822299, 'tuning_auroc': np.float64(0.7838564773735582), 'tuning_auprc': np.float64(0.24235323761986735), 'tuning_brier': np.float64(0.06433738362052471), 'tuning_logloss': 0.2532527873409978}

,task,version,model,calibration,heldout_auroc,heldout_auprc,heldout_brier,heldout_logloss
0,guo_icu,raw,GRU_2L_numeric,raw,0.741062,0.164759,0.064093,0.267920
1,guo_icu,raw,GRU_2L_numeric,platt,0.741062,0.164759,0.038312,0.158995

,task,version,model,calibration,top_frac,top_k,events_in_top_k,top_k_event_rate,top_k_lift,event_capture,base_event_rate,n,n_positive
4,guo_icu,raw,GRU_2L_numeric,platt,0.01,21,6,0.285714,6.847059,0.070588,0.041728,2037,85
5,guo_icu,raw,GRU_2L_numeric,platt,0.05,102,23,0.225490,5.403806,0.270588,0.041728,2037,85
6,guo_icu,raw,GRU_2L_numeric,platt,0.10,204,31,0.151961,3.641696,0.364706,0.041728,2037,85
7,guo_icu,raw,GRU_2L_numeric,platt,0.20,408,45,0.110294,2.643166,0.529412,0.041728,2037,85

====================================================================================================
Experiment: guo_icu | raw | LSTM_1L_numeric

numeric stats:   0%|          | 0/2402 [00:00<?, ?it/s]

epoch 1:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 1, 'train_loss': 1.5481492453499843, 'tuning_auroc': np.float64(0.5547249334516415), 'tuning_auprc': np.float64(0.08196427287616984), 'tuning_brier': np.float64(0.14081800897818658), 'tuning_logloss': 0.46692820737522384}

epoch 2:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 2, 'train_loss': 1.3481390684058792, 'tuning_auroc': np.float64(0.5719276841171251), 'tuning_auprc': np.float64(0.07191353248728094), 'tuning_brier': np.float64(0.16676231761916194), 'tuning_logloss': 0.521356575978511}

epoch 3:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 3, 'train_loss': 1.3250577563517971, 'tuning_auroc': np.float64(0.5622116237799467), 'tuning_auprc': np.float64(0.07280243233774805), 'tuning_brier': np.float64(0.15967345748792924), 'tuning_logloss': 0.5075850006122278}

epoch 4:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 4, 'train_loss': 1.3701268312962431, 'tuning_auroc': np.float64(0.5703360692102928), 'tuning_auprc': np.float64(0.0777294277472727), 'tuning_brier': np.float64(0.11524736212779978), 'tuning_logloss': 0.40861190707806966}
Early stopping at epoch 4

,task,version,model,calibration,heldout_auroc,heldout_auprc,heldout_brier,heldout_logloss
0,guo_icu,raw,LSTM_1L_numeric,raw,0.583149,0.066752,0.139346,0.463885
1,guo_icu,raw,LSTM_1L_numeric,platt,0.583149,0.066752,0.039799,0.171497

,task,version,model,calibration,top_frac,top_k,events_in_top_k,top_k_event_rate,top_k_lift,event_capture,base_event_rate,n,n_positive
4,guo_icu,raw,LSTM_1L_numeric,platt,0.01,21,1,0.047619,1.141176,0.011765,0.041728,2037,85
5,guo_icu,raw,LSTM_1L_numeric,platt,0.05,102,10,0.098039,2.349481,0.117647,0.041728,2037,85
6,guo_icu,raw,LSTM_1L_numeric,platt,0.10,204,18,0.088235,2.114533,0.211765,0.041728,2037,85
7,guo_icu,raw,LSTM_1L_numeric,platt,0.20,408,30,0.073529,1.762111,0.352941,0.041728,2037,85

====================================================================================================
Experiment: guo_icu | raw | LSTM_2L_numeric

numeric stats:   0%|          | 0/2402 [00:00<?, ?it/s]

epoch 1:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 1, 'train_loss': 1.4681619056745578, 'tuning_auroc': np.float64(0.5862633096716947), 'tuning_auprc': np.float64(0.06480814378101514), 'tuning_brier': np.float64(0.07994496904521711), 'tuning_logloss': 0.32227830415714753}

epoch 2:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 2, 'train_loss': 1.359649373904655, 'tuning_auroc': np.float64(0.5887366903283052), 'tuning_auprc': np.float64(0.07404988991264226), 'tuning_brier': np.float64(0.15288827416761663), 'tuning_logloss': 0.49505893978026416}

epoch 3:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 3, 'train_loss': 1.3507046530905522, 'tuning_auroc': np.float64(0.5880767524401065), 'tuning_auprc': np.float64(0.07587736402269035), 'tuning_brier': np.float64(0.228908626739284), 'tuning_logloss': 0.6509046939528794}

epoch 4:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 4, 'train_loss': 1.360259138439831, 'tuning_auroc': np.float64(0.5872116237799468), 'tuning_auprc': np.float64(0.07395673862162788), 'tuning_brier': np.float64(0.27078725903041956), 'tuning_logloss': 0.7349338393928271}

epoch 5:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 5, 'train_loss': 1.339624240210182, 'tuning_auroc': np.float64(0.6028504880212954), 'tuning_auprc': np.float64(0.07803104288643338), 'tuning_brier': np.float64(0.2502665217693107), 'tuning_logloss': 0.6939253118983323}

epoch 6:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 6, 'train_loss': 1.433535902907974, 'tuning_auroc': np.float64(0.5767191659272405), 'tuning_auprc': np.float64(0.07595863132728572), 'tuning_brier': np.float64(0.24712047987383945), 'tuning_logloss': 0.6875247015927861}

epoch 7:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 7, 'train_loss': 1.3174948429590778, 'tuning_auroc': np.float64(0.5462511091393079), 'tuning_auprc': np.float64(0.07537507364005822), 'tuning_brier': np.float64(0.1736110456767971), 'tuning_logloss': 0.5365538818570971}

epoch 8:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 8, 'train_loss': 1.3314023743334569, 'tuning_auroc': np.float64(0.5679015084294587), 'tuning_auprc': np.float64(0.08250375879397794), 'tuning_brier': np.float64(0.16336434114542095), 'tuning_logloss': 0.511852888313707}

epoch 9:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 9, 'train_loss': 1.4296776918988479, 'tuning_auroc': np.float64(0.5132985803016858), 'tuning_auprc': np.float64(0.0765423459465383), 'tuning_brier': np.float64(0.1041486573326252), 'tuning_logloss': 0.3743531650175713}

epoch 10:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 10, 'train_loss': 1.2121822743823654, 'tuning_auroc': np.float64(0.6388864241348713), 'tuning_auprc': np.float64(0.08462162467313489), 'tuning_brier': np.float64(0.08894569091925965), 'tuning_logloss': 0.31540541662694843}

epoch 11:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 11, 'train_loss': 1.2035611230683954, 'tuning_auroc': np.float64(0.6580967169476487), 'tuning_auprc': np.float64(0.10461603113160714), 'tuning_brier': np.float64(0.12819339434207788), 'tuning_logloss': 0.4075560061503398}

epoch 12:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 12, 'train_loss': 1.1250917489983534, 'tuning_auroc': np.float64(0.6576752440106478), 'tuning_auprc': np.float64(0.12742282864457366), 'tuning_brier': np.float64(0.0998757903964422), 'tuning_logloss': 0.34531109528080806}

,task,version,model,calibration,heldout_auroc,heldout_auprc,heldout_brier,heldout_logloss
0,guo_icu,raw,LSTM_2L_numeric,raw,0.662994,0.098314,0.104092,0.355118
1,guo_icu,raw,LSTM_2L_numeric,platt,0.662994,0.098314,0.039247,0.166122

,task,version,model,calibration,top_frac,top_k,events_in_top_k,top_k_event_rate,top_k_lift,event_capture,base_event_rate,n,n_positive
4,guo_icu,raw,LSTM_2L_numeric,platt,0.01,21,4,0.190476,4.564706,0.047059,0.041728,2037,85
5,guo_icu,raw,LSTM_2L_numeric,platt,0.05,102,14,0.137255,3.289273,0.164706,0.041728,2037,85
6,guo_icu,raw,LSTM_2L_numeric,platt,0.10,204,20,0.098039,2.349481,0.235294,0.041728,2037,85
7,guo_icu,raw,LSTM_2L_numeric,platt,0.20,408,32,0.078431,1.879585,0.376471,0.041728,2037,85

====================================================================================================
Experiment: guo_icu | raw | RETAIN_lite_numeric

numeric stats:   0%|          | 0/2402 [00:00<?, ?it/s]

epoch 1:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 1, 'train_loss': 1.4819033332169056, 'tuning_auroc': np.float64(0.6454303460514641), 'tuning_auprc': np.float64(0.07400089340926956), 'tuning_brier': np.float64(0.2154815944513454), 'tuning_logloss': 0.6171561670913503}

epoch 2:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 2, 'train_loss': 1.277691719171248, 'tuning_auroc': np.float64(0.714407719609583), 'tuning_auprc': np.float64(0.1322243415638786), 'tuning_brier': np.float64(0.14619109739121444), 'tuning_logloss': 0.46845851923578713}

epoch 3:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 3, 'train_loss': 1.3583404194367559, 'tuning_auroc': np.float64(0.7291149068322982), 'tuning_auprc': np.float64(0.12875128082202644), 'tuning_brier': np.float64(0.18953541896549864), 'tuning_logloss': 0.5485705446486682}

epoch 4:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 4, 'train_loss': 1.3286748995122157, 'tuning_auroc': np.float64(0.7374944543034605), 'tuning_auprc': np.float64(0.10785294515756884), 'tuning_brier': np.float64(0.14030160407046316), 'tuning_logloss': 0.43575071154100453}

epoch 5:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 5, 'train_loss': 1.3597795302538496, 'tuning_auroc': np.float64(0.7273791038154392), 'tuning_auprc': np.float64(0.10491431169224884), 'tuning_brier': np.float64(0.17272261741770026), 'tuning_logloss': 0.5150132771288142}
Early stopping at epoch 5

,task,version,model,calibration,heldout_auroc,heldout_auprc,heldout_brier,heldout_logloss
0,guo_icu,raw,RETAIN_lite_numeric,raw,0.689308,0.098505,0.149916,0.477209
1,guo_icu,raw,RETAIN_lite_numeric,platt,0.689308,0.098505,0.039121,0.164322

,task,version,model,calibration,top_frac,top_k,events_in_top_k,top_k_event_rate,top_k_lift,event_capture,base_event_rate,n,n_positive
4,guo_icu,raw,RETAIN_lite_numeric,platt,0.01,21,4,0.190476,4.564706,0.047059,0.041728,2037,85
5,guo_icu,raw,RETAIN_lite_numeric,platt,0.05,102,14,0.137255,3.289273,0.164706,0.041728,2037,85
6,guo_icu,raw,RETAIN_lite_numeric,platt,0.10,204,21,0.102941,2.466955,0.247059,0.041728,2037,85
7,guo_icu,raw,RETAIN_lite_numeric,platt,0.20,408,35,0.085784,2.055796,0.411765,0.041728,2037,85

====================================================================================================
Experiment: guo_icu | compressed_dedup | GRU_1L_numeric

numeric stats:   0%|          | 0/2402 [00:00<?, ?it/s]

epoch 1:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 1, 'train_loss': 1.472261207472337, 'tuning_auroc': np.float64(0.5752384649511979), 'tuning_auprc': np.float64(0.053611812097100135), 'tuning_brier': np.float64(0.2742212735871357), 'tuning_logloss': 0.7419642359924002}

epoch 2:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 2, 'train_loss': 1.327909901346031, 'tuning_auroc': np.float64(0.6002939219165927), 'tuning_auprc': np.float64(0.07336478149336623), 'tuning_brier': np.float64(0.2031028742679097), 'tuning_logloss': 0.598002643454024}

epoch 3:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 3, 'train_loss': 1.4648431382681195, 'tuning_auroc': np.float64(0.5808340727595386), 'tuning_auprc': np.float64(0.07033006805338693), 'tuning_brier': np.float64(0.18879370629400097), 'tuning_logloss': 0.5681020266960126}

epoch 4:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 4, 'train_loss': 1.3237692541197728, 'tuning_auroc': np.float64(0.5928793256433008), 'tuning_auprc': np.float64(0.07797290350758561), 'tuning_brier': np.float64(0.21337866616267737), 'tuning_logloss': 0.6180141658866092}

epoch 5:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 5, 'train_loss': 1.3168859473968808, 'tuning_auroc': np.float64(0.5914374445430346), 'tuning_auprc': np.float64(0.06573903129319392), 'tuning_brier': np.float64(0.2604367133575766), 'tuning_logloss': 0.7135942661473537}

epoch 6:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 6, 'train_loss': 1.3307064301089238, 'tuning_auroc': np.float64(0.5860192990239574), 'tuning_auprc': np.float64(0.06485504949747688), 'tuning_brier': np.float64(0.25967134191958835), 'tuning_logloss': 0.7115854051650751}

epoch 7:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 7, 'train_loss': 1.3126287793642597, 'tuning_auroc': np.float64(0.6317213842058563), 'tuning_auprc': np.float64(0.09438807419283404), 'tuning_brier': np.float64(0.2090681860523808), 'tuning_logloss': 0.6049206878001944}

epoch 8:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 8, 'train_loss': 1.1858476229796284, 'tuning_auroc': np.float64(0.7231588287488908), 'tuning_auprc': np.float64(0.12631271360252178), 'tuning_brier': np.float64(0.19616379970849637), 'tuning_logloss': 0.5732590785053355}

epoch 9:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 9, 'train_loss': 1.0084833461595208, 'tuning_auroc': np.float64(0.7542424578527063), 'tuning_auprc': np.float64(0.18540318621943602), 'tuning_brier': np.float64(0.059584002545089984), 'tuning_logloss': 0.213791313510404}

epoch 10:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 10, 'train_loss': 1.1200367953922403, 'tuning_auroc': np.float64(0.7426075865128661), 'tuning_auprc': np.float64(0.187559610931822), 'tuning_brier': np.float64(0.05322482599683185), 'tuning_logloss': 0.1994507892622724}

epoch 11:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 11, 'train_loss': 0.903722731298522, 'tuning_auroc': np.float64(0.722565439219166), 'tuning_auprc': np.float64(0.1902416101748133), 'tuning_brier': np.float64(0.04146482087859622), 'tuning_logloss': 0.16886013980098497}

epoch 12:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 12, 'train_loss': 0.9424764851206228, 'tuning_auroc': np.float64(0.7291038154392191), 'tuning_auprc': np.float64(0.18985660927412773), 'tuning_brier': np.float64(0.04694298302891901), 'tuning_logloss': 0.18532521717551648}

,task,version,model,calibration,heldout_auroc,heldout_auprc,heldout_brier,heldout_logloss
0,guo_icu,compressed_dedup,GRU_1L_numeric,raw,0.69636,0.140302,0.042288,0.172889
1,guo_icu,compressed_dedup,GRU_1L_numeric,platt,0.69636,0.140302,0.039085,0.161568

,task,version,model,calibration,top_frac,top_k,events_in_top_k,top_k_event_rate,top_k_lift,event_capture,base_event_rate,n,n_positive
4,guo_icu,compressed_dedup,GRU_1L_numeric,platt,0.01,21,6,0.285714,6.847059,0.070588,0.041728,2037,85
5,guo_icu,compressed_dedup,GRU_1L_numeric,platt,0.05,102,23,0.225490,5.403806,0.270588,0.041728,2037,85
6,guo_icu,compressed_dedup,GRU_1L_numeric,platt,0.10,204,28,0.137255,3.289273,0.329412,0.041728,2037,85
7,guo_icu,compressed_dedup,GRU_1L_numeric,platt,0.20,408,43,0.105392,2.525692,0.505882,0.041728,2037,85

====================================================================================================
Experiment: guo_icu | compressed_dedup | GRU_2L_numeric

numeric stats:   0%|          | 0/2402 [00:00<?, ?it/s]

epoch 1:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 1, 'train_loss': 1.6540705870444838, 'tuning_auroc': np.float64(0.5835791925465837), 'tuning_auprc': np.float64(0.07105558213320072), 'tuning_brier': np.float64(0.1405283627132642), 'tuning_logloss': 0.46835821231254676}

epoch 2:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 2, 'train_loss': 1.356931457001912, 'tuning_auroc': np.float64(0.5819043921916593), 'tuning_auprc': np.float64(0.0767551952466203), 'tuning_brier': np.float64(0.16462003686871346), 'tuning_logloss': 0.5195102868056422}

epoch 3:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 3, 'train_loss': 1.3631390933143466, 'tuning_auroc': np.float64(0.6238464951197871), 'tuning_auprc': np.float64(0.07960215997507555), 'tuning_brier': np.float64(0.18454437046712271), 'tuning_logloss': 0.5604382141634889}

epoch 4:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 4, 'train_loss': 1.3409841350818936, 'tuning_auroc': np.float64(0.6557897071872227), 'tuning_auprc': np.float64(0.08329496797609359), 'tuning_brier': np.float64(0.27474103611233847), 'tuning_logloss': 0.7442484017993566}

epoch 5:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 5, 'train_loss': 1.3207593552376096, 'tuning_auroc': np.float64(0.6333684560780833), 'tuning_auprc': np.float64(0.08180688145734999), 'tuning_brier': np.float64(0.21753980874340886), 'tuning_logloss': 0.6257095004929772}

epoch 6:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 6, 'train_loss': 1.2704903079490912, 'tuning_auroc': np.float64(0.7189940106477374), 'tuning_auprc': np.float64(0.1322620757973297), 'tuning_brier': np.float64(0.07417776969822863), 'tuning_logloss': 0.2734765749987447}

epoch 7:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 7, 'train_loss': 1.2654580093528096, 'tuning_auroc': np.float64(0.661368677905945), 'tuning_auprc': np.float64(0.11314967295582254), 'tuning_brier': np.float64(0.1334401205618887), 'tuning_logloss': 0.44577174850861895}

epoch 8:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 8, 'train_loss': 1.1268520603250516, 'tuning_auroc': np.float64(0.7584627329192547), 'tuning_auprc': np.float64(0.15710923632898832), 'tuning_brier': np.float64(0.1355459198183665), 'tuning_logloss': 0.44167566007978004}

epoch 9:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 9, 'train_loss': 0.9197164054861978, 'tuning_auroc': np.float64(0.7733640195208518), 'tuning_auprc': np.float64(0.20642244436470056), 'tuning_brier': np.float64(0.08216462474424631), 'tuning_logloss': 0.2964268242647089}

epoch 10:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 10, 'train_loss': 0.8680118423837581, 'tuning_auroc': np.float64(0.7372448979591836), 'tuning_auprc': np.float64(0.1516303745023431), 'tuning_brier': np.float64(0.07803064071801155), 'tuning_logloss': 0.2865663082648436}

epoch 11:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 11, 'train_loss': 0.8040410102786202, 'tuning_auroc': np.float64(0.7080856255545696), 'tuning_auprc': np.float64(0.18002592012661778), 'tuning_brier': np.float64(0.05139671474949739), 'tuning_logloss': 0.20223274608392522}

epoch 12:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 12, 'train_loss': 0.5139378564138162, 'tuning_auroc': np.float64(0.7778227595385979), 'tuning_auprc': np.float64(0.20360714450002584), 'tuning_brier': np.float64(0.05365707581948578), 'tuning_logloss': 0.20921920765255747}
Early stopping at epoch 12

,task,version,model,calibration,heldout_auroc,heldout_auprc,heldout_brier,heldout_logloss
0,guo_icu,compressed_dedup,GRU_2L_numeric,raw,0.727465,0.150785,0.082923,0.292765
1,guo_icu,compressed_dedup,GRU_2L_numeric,platt,0.727465,0.150785,0.038147,0.158410

,task,version,model,calibration,top_frac,top_k,events_in_top_k,top_k_event_rate,top_k_lift,event_capture,base_event_rate,n,n_positive
4,guo_icu,compressed_dedup,GRU_2L_numeric,platt,0.01,21,8,0.380952,9.129412,0.094118,0.041728,2037,85
5,guo_icu,compressed_dedup,GRU_2L_numeric,platt,0.05,102,21,0.205882,4.933910,0.247059,0.041728,2037,85
6,guo_icu,compressed_dedup,GRU_2L_numeric,platt,0.10,204,29,0.142157,3.406747,0.341176,0.041728,2037,85
7,guo_icu,compressed_dedup,GRU_2L_numeric,platt,0.20,408,42,0.102941,2.466955,0.494118,0.041728,2037,85

====================================================================================================
Experiment: guo_icu | compressed_dedup | LSTM_1L_numeric

numeric stats:   0%|          | 0/2402 [00:00<?, ?it/s]

epoch 1:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 1, 'train_loss': 1.6589883030637314, 'tuning_auroc': np.float64(0.6139363354037267), 'tuning_auprc': np.float64(0.0800530632086105), 'tuning_brier': np.float64(0.22632017194323467), 'tuning_logloss': 0.6455314830970065}

epoch 2:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 2, 'train_loss': 1.3462708913966228, 'tuning_auroc': np.float64(0.6094886867790594), 'tuning_auprc': np.float64(0.07548822102583629), 'tuning_brier': np.float64(0.2385521208884498), 'tuning_logloss': 0.6707565362352041}

epoch 3:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 3, 'train_loss': 1.3329617741860842, 'tuning_auroc': np.float64(0.5912211623779947), 'tuning_auprc': np.float64(0.07268578075274655), 'tuning_brier': np.float64(0.1933858155096787), 'tuning_logloss': 0.5775289873261658}

epoch 4:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 4, 'train_loss': 1.3135985928146463, 'tuning_auroc': np.float64(0.5459239130434783), 'tuning_auprc': np.float64(0.06380238902552421), 'tuning_brier': np.float64(0.18141051989435963), 'tuning_logloss': 0.5534628868949946}
Early stopping at epoch 4

,task,version,model,calibration,heldout_auroc,heldout_auprc,heldout_brier,heldout_logloss
0,guo_icu,compressed_dedup,LSTM_1L_numeric,raw,0.617008,0.067798,0.225200,0.643284
1,guo_icu,compressed_dedup,LSTM_1L_numeric,platt,0.617008,0.067798,0.039738,0.170608

,task,version,model,calibration,top_frac,top_k,events_in_top_k,top_k_event_rate,top_k_lift,event_capture,base_event_rate,n,n_positive
4,guo_icu,compressed_dedup,LSTM_1L_numeric,platt,0.01,21,2,0.095238,2.282353,0.023529,0.041728,2037,85
5,guo_icu,compressed_dedup,LSTM_1L_numeric,platt,0.05,102,11,0.107843,2.584429,0.129412,0.041728,2037,85
6,guo_icu,compressed_dedup,LSTM_1L_numeric,platt,0.10,204,16,0.078431,1.879585,0.188235,0.041728,2037,85
7,guo_icu,compressed_dedup,LSTM_1L_numeric,platt,0.20,408,29,0.071078,1.703374,0.341176,0.041728,2037,85

====================================================================================================
Experiment: guo_icu | compressed_dedup | LSTM_2L_numeric

numeric stats:   0%|          | 0/2402 [00:00<?, ?it/s]

epoch 1:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 1, 'train_loss': 1.5334332487300824, 'tuning_auroc': np.float64(0.4714507542147293), 'tuning_auprc': np.float64(0.04276206449010585), 'tuning_brier': np.float64(0.19760520848968413), 'tuning_logloss': 0.5878284838429504}

epoch 2:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 2, 'train_loss': 1.3590676902156127, 'tuning_auroc': np.float64(0.6030889529724933), 'tuning_auprc': np.float64(0.07093537479908978), 'tuning_brier': np.float64(0.16572991677379156), 'tuning_logloss': 0.5219112359836839}

epoch 3:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 3, 'train_loss': 1.3352418153693801, 'tuning_auroc': np.float64(0.5994010647737356), 'tuning_auprc': np.float64(0.07062275082772189), 'tuning_brier': np.float64(0.11207808760434414), 'tuning_logloss': 0.40293621166965915}

epoch 4:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 4, 'train_loss': 1.381723811359782, 'tuning_auroc': np.float64(0.6125887311446317), 'tuning_auprc': np.float64(0.07201262763680204), 'tuning_brier': np.float64(0.18909211119183245), 'tuning_logloss': 0.5693691536460378}

epoch 5:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 5, 'train_loss': 1.3101288009631007, 'tuning_auroc': np.float64(0.5882264862466726), 'tuning_auprc': np.float64(0.08159525999684641), 'tuning_brier': np.float64(0.31798589598317395), 'tuning_logloss': 0.8305159956026228}

epoch 6:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 6, 'train_loss': 1.3705771628179049, 'tuning_auroc': np.float64(0.5907608695652175), 'tuning_auprc': np.float64(0.0763209690771191), 'tuning_brier': np.float64(0.2355743151754448), 'tuning_logloss': 0.6641300057954853}

epoch 7:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 7, 'train_loss': 1.3210757704157579, 'tuning_auroc': np.float64(0.6158939662821651), 'tuning_auprc': np.float64(0.0799225973626842), 'tuning_brier': np.float64(0.2588837340192928), 'tuning_logloss': 0.7116363601051069}

epoch 8:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 8, 'train_loss': 1.3178060929241933, 'tuning_auroc': np.float64(0.5949478704525288), 'tuning_auprc': np.float64(0.07164553379852563), 'tuning_brier': np.float64(0.301772594010232), 'tuning_logloss': 0.8007156421682168}
Early stopping at epoch 8

,task,version,model,calibration,heldout_auroc,heldout_auprc,heldout_brier,heldout_logloss
0,guo_icu,compressed_dedup,LSTM_2L_numeric,raw,0.573385,0.071409,0.318471,0.831485
1,guo_icu,compressed_dedup,LSTM_2L_numeric,platt,0.573385,0.071409,0.039846,0.171950

,task,version,model,calibration,top_frac,top_k,events_in_top_k,top_k_event_rate,top_k_lift,event_capture,base_event_rate,n,n_positive
4,guo_icu,compressed_dedup,LSTM_2L_numeric,platt,0.01,21,2,0.095238,2.282353,0.023529,0.041728,2037,85
5,guo_icu,compressed_dedup,LSTM_2L_numeric,platt,0.05,102,13,0.127451,3.054325,0.152941,0.041728,2037,85
6,guo_icu,compressed_dedup,LSTM_2L_numeric,platt,0.10,204,20,0.098039,2.349481,0.235294,0.041728,2037,85
7,guo_icu,compressed_dedup,LSTM_2L_numeric,platt,0.20,408,28,0.068627,1.644637,0.329412,0.041728,2037,85

====================================================================================================
Experiment: guo_icu | compressed_dedup | RETAIN_lite_numeric

numeric stats:   0%|          | 0/2402 [00:00<?, ?it/s]

epoch 1:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 1, 'train_loss': 1.4043808253972154, 'tuning_auroc': np.float64(0.6707131765749778), 'tuning_auprc': np.float64(0.10169661087559724), 'tuning_brier': np.float64(0.17626515210023516), 'tuning_logloss': 0.5271390151764135}

epoch 2:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 2, 'train_loss': 1.3201262150940143, 'tuning_auroc': np.float64(0.7232531055900621), 'tuning_auprc': np.float64(0.1592941277790989), 'tuning_brier': np.float64(0.1978469766999765), 'tuning_logloss': 0.5808323888542484}

epoch 3:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 3, 'train_loss': 1.258700397845946, 'tuning_auroc': np.float64(0.7519077196095829), 'tuning_auprc': np.float64(0.17657521613053812), 'tuning_brier': np.float64(0.3082641413616915), 'tuning_logloss': 0.8170162653326043}

epoch 4:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 4, 'train_loss': 1.184419839789993, 'tuning_auroc': np.float64(0.7835514640638864), 'tuning_auprc': np.float64(0.18682265487073396), 'tuning_brier': np.float64(0.1610424551913899), 'tuning_logloss': 0.489740476139298}

epoch 5:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 5, 'train_loss': 1.1555777313677889, 'tuning_auroc': np.float64(0.7757264862466726), 'tuning_auprc': np.float64(0.24105134557760272), 'tuning_brier': np.float64(0.12976728371003654), 'tuning_logloss': 0.4173443415647823}

epoch 6:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 6, 'train_loss': 1.0436343876154799, 'tuning_auroc': np.float64(0.7665483584738243), 'tuning_auprc': np.float64(0.22396243577744895), 'tuning_brier': np.float64(0.044234658717957405), 'tuning_logloss': 0.18786440478300767}

epoch 7:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 7, 'train_loss': 1.1111210748847378, 'tuning_auroc': np.float64(0.7711013753327418), 'tuning_auprc': np.float64(0.2009262164182042), 'tuning_brier': np.float64(0.09735629680473327), 'tuning_logloss': 0.3301002389161425}

epoch 8:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 8, 'train_loss': 0.9833766561197607, 'tuning_auroc': np.float64(0.7708573646850045), 'tuning_auprc': np.float64(0.20699777587282323), 'tuning_brier': np.float64(0.08915119906901399), 'tuning_logloss': 0.30506036324284636}
Early stopping at epoch 8

,task,version,model,calibration,heldout_auroc,heldout_auprc,heldout_brier,heldout_logloss
0,guo_icu,compressed_dedup,RETAIN_lite_numeric,raw,0.753236,0.158373,0.133065,0.425860
1,guo_icu,compressed_dedup,RETAIN_lite_numeric,platt,0.753236,0.158373,0.038032,0.155685

,task,version,model,calibration,top_frac,top_k,events_in_top_k,top_k_event_rate,top_k_lift,event_capture,base_event_rate,n,n_positive
4,guo_icu,compressed_dedup,RETAIN_lite_numeric,platt,0.01,21,7,0.333333,7.988235,0.082353,0.041728,2037,85
5,guo_icu,compressed_dedup,RETAIN_lite_numeric,platt,0.05,102,20,0.196078,4.698962,0.235294,0.041728,2037,85
6,guo_icu,compressed_dedup,RETAIN_lite_numeric,platt,0.10,204,32,0.156863,3.759170,0.376471,0.041728,2037,85
7,guo_icu,compressed_dedup,RETAIN_lite_numeric,platt,0.20,408,47,0.115196,2.760640,0.552941,0.041728,2037,85

====================================================================================================
Experiment: guo_icu | compressed_first_last | GRU_1L_numeric

numeric stats:   0%|          | 0/2402 [00:00<?, ?it/s]

epoch 1:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 1, 'train_loss': 1.405200708853571, 'tuning_auroc': np.float64(0.6027395740905058), 'tuning_auprc': np.float64(0.07667776928114153), 'tuning_brier': np.float64(0.14667190982733416), 'tuning_logloss': 0.48121532230696784}

epoch 2:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 2, 'train_loss': 1.3770932735581147, 'tuning_auroc': np.float64(0.6079081632653062), 'tuning_auprc': np.float64(0.07937303555748106), 'tuning_brier': np.float64(0.3433319022649715), 'tuning_logloss': 0.8863247744026209}

epoch 3:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 3, 'train_loss': 1.382904514670372, 'tuning_auroc': np.float64(0.6203637976929902), 'tuning_auprc': np.float64(0.08266051213026578), 'tuning_brier': np.float64(0.2432106839772995), 'tuning_logloss': 0.680032896992612}

epoch 4:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 4, 'train_loss': 1.4483446800395061, 'tuning_auroc': np.float64(0.6051242236024845), 'tuning_auprc': np.float64(0.0848297033102085), 'tuning_brier': np.float64(0.1615109491301615), 'tuning_logloss': 0.5113679397283164}

epoch 5:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 5, 'train_loss': 1.3135129099613743, 'tuning_auroc': np.float64(0.5826308784383318), 'tuning_auprc': np.float64(0.10140873701406151), 'tuning_brier': np.float64(0.1367143255556613), 'tuning_logloss': 0.4575229547268187}

epoch 6:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 6, 'train_loss': 1.3047326497341458, 'tuning_auroc': np.float64(0.6247670807453416), 'tuning_auprc': np.float64(0.1164083167968598), 'tuning_brier': np.float64(0.18480364374429878), 'tuning_logloss': 0.556839761331828}

epoch 7:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 7, 'train_loss': 1.2613875082644976, 'tuning_auroc': np.float64(0.6976652617568767), 'tuning_auprc': np.float64(0.17437131832781377), 'tuning_brier': np.float64(0.24331604614692), 'tuning_logloss': 0.6822574999817729}

epoch 8:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 8, 'train_loss': 1.0814992426649521, 'tuning_auroc': np.float64(0.7240073203194322), 'tuning_auprc': np.float64(0.20730156396892493), 'tuning_brier': np.float64(0.056611279440330155), 'tuning_logloss': 0.218038561785231}

epoch 9:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 9, 'train_loss': 1.0741121861103333, 'tuning_auroc': np.float64(0.7721716947648624), 'tuning_auprc': np.float64(0.23705899304619873), 'tuning_brier': np.float64(0.11563743300038352), 'tuning_logloss': 0.3924296896896046}

epoch 10:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 10, 'train_loss': 0.8908078629327448, 'tuning_auroc': np.float64(0.7517468944099379), 'tuning_auprc': np.float64(0.2557560572906812), 'tuning_brier': np.float64(0.042171285638580386), 'tuning_logloss': 0.16706162485346526}

epoch 11:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 11, 'train_loss': 0.7516520235099291, 'tuning_auroc': np.float64(0.7716892191659273), 'tuning_auprc': np.float64(0.24261881329620122), 'tuning_brier': np.float64(0.0487364177692048), 'tuning_logloss': 0.18619989564267503}

epoch 12:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 12, 'train_loss': 0.9203836009592602, 'tuning_auroc': np.float64(0.7671084738243124), 'tuning_auprc': np.float64(0.2403486652100506), 'tuning_brier': np.float64(0.04145615883029288), 'tuning_logloss': 0.16762887548604263}

,task,version,model,calibration,heldout_auroc,heldout_auprc,heldout_brier,heldout_logloss
0,guo_icu,compressed_first_last,GRU_1L_numeric,raw,0.71341,0.177232,0.042135,0.169255
1,guo_icu,compressed_first_last,GRU_1L_numeric,platt,0.71341,0.177232,0.037622,0.155315

,task,version,model,calibration,top_frac,top_k,events_in_top_k,top_k_event_rate,top_k_lift,event_capture,base_event_rate,n,n_positive
4,guo_icu,compressed_first_last,GRU_1L_numeric,platt,0.01,21,8,0.380952,9.129412,0.094118,0.041728,2037,85
5,guo_icu,compressed_first_last,GRU_1L_numeric,platt,0.05,102,26,0.254902,6.108651,0.305882,0.041728,2037,85
6,guo_icu,compressed_first_last,GRU_1L_numeric,platt,0.10,204,37,0.181373,4.346540,0.435294,0.041728,2037,85
7,guo_icu,compressed_first_last,GRU_1L_numeric,platt,0.20,408,46,0.112745,2.701903,0.541176,0.041728,2037,85

====================================================================================================
Experiment: guo_icu | compressed_first_last | GRU_2L_numeric

numeric stats:   0%|          | 0/2402 [00:00<?, ?it/s]

epoch 1:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 1, 'train_loss': 1.4130832498010837, 'tuning_auroc': np.float64(0.570291703637977), 'tuning_auprc': np.float64(0.08574933870460012), 'tuning_brier': np.float64(0.23632510649332217), 'tuning_logloss': 0.6657630302443485}

epoch 2:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 2, 'train_loss': 1.4607597950257754, 'tuning_auroc': np.float64(0.6087233806566105), 'tuning_auprc': np.float64(0.07924545989495373), 'tuning_brier': np.float64(0.13423684327659383), 'tuning_logloss': 0.4527212325670909}

epoch 3:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 3, 'train_loss': 1.35824574216416, 'tuning_auroc': np.float64(0.6025343833185448), 'tuning_auprc': np.float64(0.08900735298639013), 'tuning_brier': np.float64(0.16174467852765814), 'tuning_logloss': 0.5128113393202236}

epoch 4:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 4, 'train_loss': 1.3391241925327402, 'tuning_auroc': np.float64(0.6521129103815441), 'tuning_auprc': np.float64(0.09118754003003306), 'tuning_brier': np.float64(0.15547771795327553), 'tuning_logloss': 0.4972929567429926}

epoch 5:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 5, 'train_loss': 1.3609788237433684, 'tuning_auroc': np.float64(0.6783274179236913), 'tuning_auprc': np.float64(0.1035614625472819), 'tuning_brier': np.float64(0.13036015544806143), 'tuning_logloss': 0.4432481680332379}

epoch 6:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 6, 'train_loss': 1.3913407647296, 'tuning_auroc': np.float64(0.6956188997338065), 'tuning_auprc': np.float64(0.11046619659580033), 'tuning_brier': np.float64(0.12341287283805986), 'tuning_logloss': 0.4242272775742482}

epoch 7:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 7, 'train_loss': 1.3096081876244985, 'tuning_auroc': np.float64(0.7063054569653948), 'tuning_auprc': np.float64(0.13768216829836433), 'tuning_brier': np.float64(0.37525015941654727), 'tuning_logloss': 0.9582915441169608}

epoch 8:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 8, 'train_loss': 1.1441541003847593, 'tuning_auroc': np.float64(0.7516359804791483), 'tuning_auprc': np.float64(0.17773317046926504), 'tuning_brier': np.float64(0.2044677195030769), 'tuning_logloss': 0.597348712147463}

epoch 9:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 9, 'train_loss': 0.9663603913627172, 'tuning_auroc': np.float64(0.7884483141082521), 'tuning_auprc': np.float64(0.23400956176113474), 'tuning_brier': np.float64(0.07270651362666841), 'tuning_logloss': 0.2522709524286848}

epoch 10:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 10, 'train_loss': 0.8149910143233443, 'tuning_auroc': np.float64(0.7912322537710736), 'tuning_auprc': np.float64(0.22546796742958516), 'tuning_brier': np.float64(0.045355938952365865), 'tuning_logloss': 0.1837559094462873}

epoch 11:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 11, 'train_loss': 0.8917569508285899, 'tuning_auroc': np.float64(0.793888642413487), 'tuning_auprc': np.float64(0.21755925895682773), 'tuning_brier': np.float64(0.05422002250001002), 'tuning_logloss': 0.20308182367637262}

epoch 12:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 12, 'train_loss': 0.7772572605233443, 'tuning_auroc': np.float64(0.7842834960070986), 'tuning_auprc': np.float64(0.22123902905878617), 'tuning_brier': np.float64(0.05527301374493631), 'tuning_logloss': 0.22277146209087798}
Early stopping at epoch 12

,task,version,model,calibration,heldout_auroc,heldout_auprc,heldout_brier,heldout_logloss
0,guo_icu,compressed_first_last,GRU_2L_numeric,raw,0.74375,0.155687,0.074026,0.256715
1,guo_icu,compressed_first_last,GRU_2L_numeric,platt,0.74375,0.155687,0.037928,0.156059

,task,version,model,calibration,top_frac,top_k,events_in_top_k,top_k_event_rate,top_k_lift,event_capture,base_event_rate,n,n_positive
4,guo_icu,compressed_first_last,GRU_2L_numeric,platt,0.01,21,8,0.380952,9.129412,0.094118,0.041728,2037,85
5,guo_icu,compressed_first_last,GRU_2L_numeric,platt,0.05,102,22,0.215686,5.168858,0.258824,0.041728,2037,85
6,guo_icu,compressed_first_last,GRU_2L_numeric,platt,0.10,204,34,0.166667,3.994118,0.400000,0.041728,2037,85
7,guo_icu,compressed_first_last,GRU_2L_numeric,platt,0.20,408,46,0.112745,2.701903,0.541176,0.041728,2037,85

====================================================================================================
Experiment: guo_icu | compressed_first_last | LSTM_1L_numeric

numeric stats:   0%|          | 0/2402 [00:00<?, ?it/s]

epoch 1:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 1, 'train_loss': 1.3858291365598376, 'tuning_auroc': np.float64(0.6023985137533273), 'tuning_auprc': np.float64(0.0760598738375836), 'tuning_brier': np.float64(0.1650722349585478), 'tuning_logloss': 0.5189151598622592}

epoch 2:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 2, 'train_loss': 1.3426520702870268, 'tuning_auroc': np.float64(0.6011645962732919), 'tuning_auprc': np.float64(0.07691182205277426), 'tuning_brier': np.float64(0.2005717417335916), 'tuning_logloss': 0.5932289469888775}

epoch 3:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 3, 'train_loss': 1.3686653806975013, 'tuning_auroc': np.float64(0.5886146850044366), 'tuning_auprc': np.float64(0.07504275148033078), 'tuning_brier': np.float64(0.33848878704369545), 'tuning_logloss': 0.8734584189905688}

epoch 4:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 4, 'train_loss': 1.471678025628391, 'tuning_auroc': np.float64(0.5682287045252884), 'tuning_auprc': np.float64(0.07624121352462282), 'tuning_brier': np.float64(0.16091768678220264), 'tuning_logloss': 0.5092520776004203}

epoch 5:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 5, 'train_loss': 1.3020924929725497, 'tuning_auroc': np.float64(0.610581188997338), 'tuning_auprc': np.float64(0.0795854222180874), 'tuning_brier': np.float64(0.12710008880326587), 'tuning_logloss': 0.4347098363445268}

epoch 6:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 6, 'train_loss': 1.3859616023929495, 'tuning_auroc': np.float64(0.5862910381543921), 'tuning_auprc': np.float64(0.08438891958692782), 'tuning_brier': np.float64(0.20928376188063816), 'tuning_logloss': 0.6092734008479572}

epoch 7:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 7, 'train_loss': 1.2354888653284626, 'tuning_auroc': np.float64(0.5670530168589175), 'tuning_auprc': np.float64(0.08130095792719604), 'tuning_brier': np.float64(0.0767206148695606), 'tuning_logloss': 0.30715775787230976}

epoch 8:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 8, 'train_loss': 1.2768499972788911, 'tuning_auroc': np.float64(0.6198591393078972), 'tuning_auprc': np.float64(0.09108596796849802), 'tuning_brier': np.float64(0.18284130626005077), 'tuning_logloss': 0.5500250823705276}

epoch 9:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 9, 'train_loss': 1.2179018639420207, 'tuning_auroc': np.float64(0.6508706743566991), 'tuning_auprc': np.float64(0.11926989506964757), 'tuning_brier': np.float64(0.20587052933567437), 'tuning_logloss': 0.6000098328022339}

epoch 10:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 10, 'train_loss': 1.1965239646011276, 'tuning_auroc': np.float64(0.5877440106477373), 'tuning_auprc': np.float64(0.10575452570229328), 'tuning_brier': np.float64(0.1931698314692761), 'tuning_logloss': 0.5656167958563642}

epoch 11:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 11, 'train_loss': 1.134332298840347, 'tuning_auroc': np.float64(0.6133207630878439), 'tuning_auprc': np.float64(0.13396915445293214), 'tuning_brier': np.float64(0.1127939538588261), 'tuning_logloss': 0.3826873196749598}

epoch 12:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 12, 'train_loss': 1.330642344430089, 'tuning_auroc': np.float64(0.5857087400177463), 'tuning_auprc': np.float64(0.11613899249284178), 'tuning_brier': np.float64(0.11432468337578784), 'tuning_logloss': 0.3880736716243473}

,task,version,model,calibration,heldout_auroc,heldout_auprc,heldout_brier,heldout_logloss
0,guo_icu,compressed_first_last,LSTM_1L_numeric,raw,0.552592,0.05326,0.119075,0.400009
1,guo_icu,compressed_first_last,LSTM_1L_numeric,platt,0.552592,0.05326,0.040091,0.174630

,task,version,model,calibration,top_frac,top_k,events_in_top_k,top_k_event_rate,top_k_lift,event_capture,base_event_rate,n,n_positive
4,guo_icu,compressed_first_last,LSTM_1L_numeric,platt,0.01,21,0,0.000000,0.000000,0.000000,0.041728,2037,85
5,guo_icu,compressed_first_last,LSTM_1L_numeric,platt,0.05,102,6,0.058824,1.409689,0.070588,0.041728,2037,85
6,guo_icu,compressed_first_last,LSTM_1L_numeric,platt,0.10,204,12,0.058824,1.409689,0.141176,0.041728,2037,85
7,guo_icu,compressed_first_last,LSTM_1L_numeric,platt,0.20,408,27,0.066176,1.585900,0.317647,0.041728,2037,85

====================================================================================================
Experiment: guo_icu | compressed_first_last | LSTM_2L_numeric

numeric stats:   0%|          | 0/2402 [00:00<?, ?it/s]

epoch 1:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 1, 'train_loss': 1.5969422224320864, 'tuning_auroc': np.float64(0.6336623779946761), 'tuning_auprc': np.float64(0.06681151643002797), 'tuning_brier': np.float64(0.1476436623575192), 'tuning_logloss': 0.483793489610389}

epoch 2:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 2, 'train_loss': 1.32694594718908, 'tuning_auroc': np.float64(0.6354425465838509), 'tuning_auprc': np.float64(0.07103752083066235), 'tuning_brier': np.float64(0.1391733859899843), 'tuning_logloss': 0.46495556914998637}

epoch 3:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 3, 'train_loss': 1.3239094387543828, 'tuning_auroc': np.float64(0.6442269299023958), 'tuning_auprc': np.float64(0.0730771539739056), 'tuning_brier': np.float64(0.09811788694461533), 'tuning_logloss': 0.36921082143623085}

epoch 4:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 4, 'train_loss': 1.3888396695256233, 'tuning_auroc': np.float64(0.630742568766637), 'tuning_auprc': np.float64(0.07354844246551383), 'tuning_brier': np.float64(0.15765505039005448), 'tuning_logloss': 0.5043085231532553}

epoch 5:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 5, 'train_loss': 1.3351238585616414, 'tuning_auroc': np.float64(0.6347049689440994), 'tuning_auprc': np.float64(0.07289213195606026), 'tuning_brier': np.float64(0.2249803913662377), 'tuning_logloss': 0.6430022990098423}

epoch 6:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 6, 'train_loss': 1.368198247332322, 'tuning_auroc': np.float64(0.6354813664596273), 'tuning_auprc': np.float64(0.07887837036564609), 'tuning_brier': np.float64(0.25355669385166335), 'tuning_logloss': 0.7008747324545046}

epoch 7:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 7, 'train_loss': 1.3576075097447948, 'tuning_auroc': np.float64(0.5977650842945874), 'tuning_auprc': np.float64(0.09227914806189205), 'tuning_brier': np.float64(0.17853716537769124), 'tuning_logloss': 0.5407770905188215}

epoch 8:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 8, 'train_loss': 1.3748818914356984, 'tuning_auroc': np.float64(0.6668700088731145), 'tuning_auprc': np.float64(0.09090509065206806), 'tuning_brier': np.float64(0.2547860478054869), 'tuning_logloss': 0.7093757658146645}

epoch 9:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 9, 'train_loss': 1.3201451411372738, 'tuning_auroc': np.float64(0.6417147293700087), 'tuning_auprc': np.float64(0.08853226064895955), 'tuning_brier': np.float64(0.21005384000237906), 'tuning_logloss': 0.6104918121142386}

epoch 10:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 10, 'train_loss': 1.2273834202634661, 'tuning_auroc': np.float64(0.6135370452528838), 'tuning_auprc': np.float64(0.10147450365711921), 'tuning_brier': np.float64(0.10279005287969661), 'tuning_logloss': 0.35807533114791856}

epoch 11:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 11, 'train_loss': 1.183724168491991, 'tuning_auroc': np.float64(0.6167147293700089), 'tuning_auprc': np.float64(0.108821812361599), 'tuning_brier': np.float64(0.22071333855101102), 'tuning_logloss': 0.6362852885422212}

epoch 12:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 12, 'train_loss': 1.1439390466793586, 'tuning_auroc': np.float64(0.6569709405501332), 'tuning_auprc': np.float64(0.138968792630011), 'tuning_brier': np.float64(0.14156695408966793), 'tuning_logloss': 0.44849136605742096}

,task,version,model,calibration,heldout_auroc,heldout_auprc,heldout_brier,heldout_logloss
0,guo_icu,compressed_first_last,LSTM_2L_numeric,raw,0.597077,0.075946,0.137363,0.439000
1,guo_icu,compressed_first_last,LSTM_2L_numeric,platt,0.597077,0.075946,0.039749,0.171494

,task,version,model,calibration,top_frac,top_k,events_in_top_k,top_k_event_rate,top_k_lift,event_capture,base_event_rate,n,n_positive
4,guo_icu,compressed_first_last,LSTM_2L_numeric,platt,0.01,21,3,0.142857,3.423529,0.035294,0.041728,2037,85
5,guo_icu,compressed_first_last,LSTM_2L_numeric,platt,0.05,102,10,0.098039,2.349481,0.117647,0.041728,2037,85
6,guo_icu,compressed_first_last,LSTM_2L_numeric,platt,0.10,204,17,0.083333,1.997059,0.200000,0.041728,2037,85
7,guo_icu,compressed_first_last,LSTM_2L_numeric,platt,0.20,408,32,0.078431,1.879585,0.376471,0.041728,2037,85

====================================================================================================
Experiment: guo_icu | compressed_first_last | RETAIN_lite_numeric

numeric stats:   0%|          | 0/2402 [00:00<?, ?it/s]

epoch 1:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 1, 'train_loss': 1.3464972427801083, 'tuning_auroc': np.float64(0.7309671694764861), 'tuning_auprc': np.float64(0.1387672942826647), 'tuning_brier': np.float64(0.19677098216587732), 'tuning_logloss': 0.5829053887096868}

epoch 2:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 2, 'train_loss': 1.273805836705785, 'tuning_auroc': np.float64(0.7675854037267081), 'tuning_auprc': np.float64(0.20193984207570914), 'tuning_brier': np.float64(0.1104216470626052), 'tuning_logloss': 0.37513399343813697}

epoch 3:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 3, 'train_loss': 1.2331653429489386, 'tuning_auroc': np.float64(0.7725044365572316), 'tuning_auprc': np.float64(0.1873862783913029), 'tuning_brier': np.float64(0.3249901351927414), 'tuning_logloss': 0.8899855359158498}

epoch 4:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 4, 'train_loss': 1.146272459704625, 'tuning_auroc': np.float64(0.7880434782608696), 'tuning_auprc': np.float64(0.2077557396740076), 'tuning_brier': np.float64(0.1364570465237438), 'tuning_logloss': 0.4361491984126529}

epoch 5:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 5, 'train_loss': 1.2438598402628773, 'tuning_auroc': np.float64(0.7926741348713398), 'tuning_auprc': np.float64(0.2502635503144196), 'tuning_brier': np.float64(0.1303245543394263), 'tuning_logloss': 0.4285365825516055}

epoch 6:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 6, 'train_loss': 0.966780794000155, 'tuning_auroc': np.float64(0.7832353593611358), 'tuning_auprc': np.float64(0.23646025540806123), 'tuning_brier': np.float64(0.1339343128485519), 'tuning_logloss': 0.41694980075253174}

epoch 7:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 7, 'train_loss': 1.037865739511816, 'tuning_auroc': np.float64(0.7687555456965395), 'tuning_auprc': np.float64(0.2623004359338229), 'tuning_brier': np.float64(0.10730889224657743), 'tuning_logloss': 0.3667350464494602}

epoch 8:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 8, 'train_loss': 0.9937456972700985, 'tuning_auroc': np.float64(0.7815771960958298), 'tuning_auprc': np.float64(0.24432916765574506), 'tuning_brier': np.float64(0.18114922745819909), 'tuning_logloss': 0.5488545872104773}

epoch 9:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 9, 'train_loss': 0.9109197306985918, 'tuning_auroc': np.float64(0.7236579414374446), 'tuning_auprc': np.float64(0.1713781405566952), 'tuning_brier': np.float64(0.06168504402509725), 'tuning_logloss': 0.23547386625138203}

epoch 10:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 10, 'train_loss': 1.0486864446123179, 'tuning_auroc': np.float64(0.7757209405501332), 'tuning_auprc': np.float64(0.22969387118565923), 'tuning_brier': np.float64(0.07656702802341304), 'tuning_logloss': 0.2705015811185344}
Early stopping at epoch 10

,task,version,model,calibration,heldout_auroc,heldout_auprc,heldout_brier,heldout_logloss
0,guo_icu,compressed_first_last,RETAIN_lite_numeric,raw,0.712596,0.135566,0.104471,0.368158
1,guo_icu,compressed_first_last,RETAIN_lite_numeric,platt,0.712596,0.135566,0.038859,0.161048

,task,version,model,calibration,top_frac,top_k,events_in_top_k,top_k_event_rate,top_k_lift,event_capture,base_event_rate,n,n_positive
4,guo_icu,compressed_first_last,RETAIN_lite_numeric,platt,0.01,21,6,0.285714,6.847059,0.070588,0.041728,2037,85
5,guo_icu,compressed_first_last,RETAIN_lite_numeric,platt,0.05,102,22,0.215686,5.168858,0.258824,0.041728,2037,85
6,guo_icu,compressed_first_last,RETAIN_lite_numeric,platt,0.10,204,28,0.137255,3.289273,0.329412,0.041728,2037,85
7,guo_icu,compressed_first_last,RETAIN_lite_numeric,platt,0.20,408,41,0.100490,2.408218,0.482353,0.041728,2037,85

====================================================================================================
Experiment: guo_icu | compressed_condition_era | GRU_1L_numeric

numeric stats:   0%|          | 0/2402 [00:00<?, ?it/s]

epoch 1:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 1, 'train_loss': 1.6186201631238586, 'tuning_auroc': np.float64(0.6264196983141083), 'tuning_auprc': np.float64(0.07145571500711975), 'tuning_brier': np.float64(0.17047331794546583), 'tuning_logloss': 0.5301797236096013}

epoch 2:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 2, 'train_loss': 1.4075111072314412, 'tuning_auroc': np.float64(0.5997892635314995), 'tuning_auprc': np.float64(0.080073652112563), 'tuning_brier': np.float64(0.31172826877486604), 'tuning_logloss': 0.8205862567535124}

epoch 3:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 3, 'train_loss': 1.475247811722128, 'tuning_auroc': np.float64(0.57920363797693), 'tuning_auprc': np.float64(0.08147430720765844), 'tuning_brier': np.float64(0.24061171205853385), 'tuning_logloss': 0.6744470178025723}

epoch 4:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 4, 'train_loss': 1.318270145278228, 'tuning_auroc': np.float64(0.6416537267080745), 'tuning_auprc': np.float64(0.08991018379490354), 'tuning_brier': np.float64(0.17266467125682444), 'tuning_logloss': 0.5343251308491086}

epoch 5:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 5, 'train_loss': 1.3282211493504674, 'tuning_auroc': np.float64(0.6631155723158829), 'tuning_auprc': np.float64(0.10518121725541202), 'tuning_brier': np.float64(0.1292492123095473), 'tuning_logloss': 0.4375951564615697}

epoch 6:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 6, 'train_loss': 1.2305625604563637, 'tuning_auroc': np.float64(0.739818101153505), 'tuning_auprc': np.float64(0.18032875818942107), 'tuning_brier': np.float64(0.10027640456145386), 'tuning_logloss': 0.35434556101731757}

epoch 7:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 7, 'train_loss': 1.1637214562414508, 'tuning_auroc': np.float64(0.7756599378881988), 'tuning_auprc': np.float64(0.20670895481057625), 'tuning_brier': np.float64(0.08288122507173708), 'tuning_logloss': 0.28687012020218866}

epoch 8:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 8, 'train_loss': 1.0285199988437326, 'tuning_auroc': np.float64(0.7678515971606032), 'tuning_auprc': np.float64(0.21779967521454122), 'tuning_brier': np.float64(0.039668647923691756), 'tuning_logloss': 0.15921730931383093}

epoch 9:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 9, 'train_loss': 0.898449736304189, 'tuning_auroc': np.float64(0.7958407275953859), 'tuning_auprc': np.float64(0.24614615217340227), 'tuning_brier': np.float64(0.05503294611967182), 'tuning_logloss': 0.21608873348197494}

epoch 10:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 10, 'train_loss': 1.1067857847941156, 'tuning_auroc': np.float64(0.781649290150843), 'tuning_auprc': np.float64(0.24765878524249582), 'tuning_brier': np.float64(0.06983341088471273), 'tuning_logloss': 0.2604105149310838}

epoch 11:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 11, 'train_loss': 0.7635539703953423, 'tuning_auroc': np.float64(0.7416149068322981), 'tuning_auprc': np.float64(0.22818553544595968), 'tuning_brier': np.float64(0.04510674744601024), 'tuning_logloss': 0.1929048303228098}

epoch 12:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 12, 'train_loss': 0.6316171577445379, 'tuning_auroc': np.float64(0.7708795474711624), 'tuning_auprc': np.float64(0.25284787523475744), 'tuning_brier': np.float64(0.04812433992283242), 'tuning_logloss': 0.19336638181972837}

,task,version,model,calibration,heldout_auroc,heldout_auprc,heldout_brier,heldout_logloss
0,guo_icu,compressed_condition_era,GRU_1L_numeric,raw,0.717267,0.168888,0.05247,0.215143
1,guo_icu,compressed_condition_era,GRU_1L_numeric,platt,0.717267,0.168888,0.03828,0.158281

,task,version,model,calibration,top_frac,top_k,events_in_top_k,top_k_event_rate,top_k_lift,event_capture,base_event_rate,n,n_positive
4,guo_icu,compressed_condition_era,GRU_1L_numeric,platt,0.01,21,10,0.476190,11.411765,0.117647,0.041728,2037,85
5,guo_icu,compressed_condition_era,GRU_1L_numeric,platt,0.05,102,24,0.235294,5.638754,0.282353,0.041728,2037,85
6,guo_icu,compressed_condition_era,GRU_1L_numeric,platt,0.10,204,32,0.156863,3.759170,0.376471,0.041728,2037,85
7,guo_icu,compressed_condition_era,GRU_1L_numeric,platt,0.20,408,41,0.100490,2.408218,0.482353,0.041728,2037,85

====================================================================================================
Experiment: guo_icu | compressed_condition_era | GRU_2L_numeric

numeric stats:   0%|          | 0/2402 [00:00<?, ?it/s]

epoch 1:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 1, 'train_loss': 1.5956255303401696, 'tuning_auroc': np.float64(0.6446650399290151), 'tuning_auprc': np.float64(0.08434168011227286), 'tuning_brier': np.float64(0.3045359272171093), 'tuning_logloss': 0.8027764604744476}

epoch 2:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 2, 'train_loss': 1.3719576087437177, 'tuning_auroc': np.float64(0.6407885980479149), 'tuning_auprc': np.float64(0.08446606259379053), 'tuning_brier': np.float64(0.15014896944791176), 'tuning_logloss': 0.4889722249928134}

epoch 3:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 3, 'train_loss': 1.3631619379708642, 'tuning_auroc': np.float64(0.6578416149068324), 'tuning_auprc': np.float64(0.08742468909414397), 'tuning_brier': np.float64(0.19284587761465252), 'tuning_logloss': 0.5779337702480032}

epoch 4:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 4, 'train_loss': 1.3350115594895262, 'tuning_auroc': np.float64(0.6500443655723159), 'tuning_auprc': np.float64(0.08641915593645441), 'tuning_brier': np.float64(0.15287892882593432), 'tuning_logloss': 0.4931151753420877}

epoch 5:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 5, 'train_loss': 1.3277428840336047, 'tuning_auroc': np.float64(0.6869232475598935), 'tuning_auprc': np.float64(0.10759431319434117), 'tuning_brier': np.float64(0.24440120455817008), 'tuning_logloss': 0.6821400257192534}

epoch 6:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 6, 'train_loss': 1.3733625270818408, 'tuning_auroc': np.float64(0.7183895297249335), 'tuning_auprc': np.float64(0.12471178970750126), 'tuning_brier': np.float64(0.1699266530435842), 'tuning_logloss': 0.529802122525913}

epoch 7:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 7, 'train_loss': 1.2600808800443222, 'tuning_auroc': np.float64(0.713481588287489), 'tuning_auprc': np.float64(0.17494960775233823), 'tuning_brier': np.float64(0.23751153916804227), 'tuning_logloss': 0.66427212777837}

epoch 8:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 8, 'train_loss': 1.3502778282977248, 'tuning_auroc': np.float64(0.6181066992014197), 'tuning_auprc': np.float64(0.09155374133087013), 'tuning_brier': np.float64(0.17408573000960204), 'tuning_logloss': 0.5140439216720545}

epoch 9:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 9, 'train_loss': 1.1623172146807377, 'tuning_auroc': np.float64(0.7288598047914818), 'tuning_auprc': np.float64(0.19825804494303959), 'tuning_brier': np.float64(0.14435415011578617), 'tuning_logloss': 0.43588547334549244}

epoch 10:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 10, 'train_loss': 0.9275843647651767, 'tuning_auroc': np.float64(0.7604259094942324), 'tuning_auprc': np.float64(0.15673423209108528), 'tuning_brier': np.float64(0.08483809933195337), 'tuning_logloss': 0.2921751321978665}

epoch 11:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 11, 'train_loss': 0.8407387533960374, 'tuning_auroc': np.float64(0.7682841614906831), 'tuning_auprc': np.float64(0.21565188030146948), 'tuning_brier': np.float64(0.07241058414517348), 'tuning_logloss': 0.24861182882479557}

epoch 12:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 12, 'train_loss': 0.7586658057805739, 'tuning_auroc': np.float64(0.7933285270629992), 'tuning_auprc': np.float64(0.24611577654877054), 'tuning_brier': np.float64(0.047150717737360515), 'tuning_logloss': 0.18735289262038712}

,task,version,model,calibration,heldout_auroc,heldout_auprc,heldout_brier,heldout_logloss
0,guo_icu,compressed_condition_era,GRU_2L_numeric,raw,0.770287,0.170596,0.047520,0.194652
1,guo_icu,compressed_condition_era,GRU_2L_numeric,platt,0.770287,0.170596,0.038209,0.158038

,task,version,model,calibration,top_frac,top_k,events_in_top_k,top_k_event_rate,top_k_lift,event_capture,base_event_rate,n,n_positive
4,guo_icu,compressed_condition_era,GRU_2L_numeric,platt,0.01,21,7,0.333333,7.988235,0.082353,0.041728,2037,85
5,guo_icu,compressed_condition_era,GRU_2L_numeric,platt,0.05,102,22,0.215686,5.168858,0.258824,0.041728,2037,85
6,guo_icu,compressed_condition_era,GRU_2L_numeric,platt,0.10,204,27,0.132353,3.171799,0.317647,0.041728,2037,85
7,guo_icu,compressed_condition_era,GRU_2L_numeric,platt,0.20,408,49,0.120098,2.878114,0.576471,0.041728,2037,85

====================================================================================================
Experiment: guo_icu | compressed_condition_era | LSTM_1L_numeric

numeric stats:   0%|          | 0/2402 [00:00<?, ?it/s]

epoch 1:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 1, 'train_loss': 1.710516693168565, 'tuning_auroc': np.float64(0.6031111357586514), 'tuning_auprc': np.float64(0.06961791315009826), 'tuning_brier': np.float64(0.13006231144218916), 'tuning_logloss': 0.44217423178544213}

epoch 2:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 2, 'train_loss': 1.3669506585911702, 'tuning_auroc': np.float64(0.6300770851818989), 'tuning_auprc': np.float64(0.08075002096390621), 'tuning_brier': np.float64(0.16035442376350453), 'tuning_logloss': 0.5089427009833601}

epoch 3:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 3, 'train_loss': 1.318588413690266, 'tuning_auroc': np.float64(0.5799689440993788), 'tuning_auprc': np.float64(0.06910813757297862), 'tuning_brier': np.float64(0.11610985193054725), 'tuning_logloss': 0.41305419522569076}

epoch 4:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 4, 'train_loss': 1.3512286312485997, 'tuning_auroc': np.float64(0.5731588287488909), 'tuning_auprc': np.float64(0.0748035217587755), 'tuning_brier': np.float64(0.28481260972235406), 'tuning_logloss': 0.7641566568271493}

epoch 5:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 5, 'train_loss': 1.3383514575268094, 'tuning_auroc': np.float64(0.578050133096717), 'tuning_auprc': np.float64(0.06493602053452635), 'tuning_brier': np.float64(0.2464686170359149), 'tuning_logloss': 0.686211856239363}
Early stopping at epoch 5

,task,version,model,calibration,heldout_auroc,heldout_auprc,heldout_brier,heldout_logloss
0,guo_icu,compressed_condition_era,LSTM_1L_numeric,raw,0.584878,0.053845,0.158229,0.504619
1,guo_icu,compressed_condition_era,LSTM_1L_numeric,platt,0.584878,0.053845,0.039892,0.172230

,task,version,model,calibration,top_frac,top_k,events_in_top_k,top_k_event_rate,top_k_lift,event_capture,base_event_rate,n,n_positive
4,guo_icu,compressed_condition_era,LSTM_1L_numeric,platt,0.01,21,0,0.000000,0.000000,0.000000,0.041728,2037,85
5,guo_icu,compressed_condition_era,LSTM_1L_numeric,platt,0.05,102,3,0.029412,0.704844,0.035294,0.041728,2037,85
6,guo_icu,compressed_condition_era,LSTM_1L_numeric,platt,0.10,204,11,0.053922,1.292215,0.129412,0.041728,2037,85
7,guo_icu,compressed_condition_era,LSTM_1L_numeric,platt,0.20,408,29,0.071078,1.703374,0.341176,0.041728,2037,85

====================================================================================================
Experiment: guo_icu | compressed_condition_era | LSTM_2L_numeric

numeric stats:   0%|          | 0/2402 [00:00<?, ?it/s]

epoch 1:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 1, 'train_loss': 1.4276981255725811, 'tuning_auroc': np.float64(0.5781111357586513), 'tuning_auprc': np.float64(0.06815637760487375), 'tuning_brier': np.float64(0.2060687082428527), 'tuning_logloss': 0.604954439573369}

epoch 2:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 2, 'train_loss': 1.350276385090853, 'tuning_auroc': np.float64(0.5870341614906833), 'tuning_auprc': np.float64(0.0746224711740773), 'tuning_brier': np.float64(0.2026398513069207), 'tuning_logloss': 0.5978977061100968}

epoch 3:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 3, 'train_loss': 1.3204317755605046, 'tuning_auroc': np.float64(0.5518356255545697), 'tuning_auprc': np.float64(0.06780700599372547), 'tuning_brier': np.float64(0.2031944567641823), 'tuning_logloss': 0.5989618753392238}

epoch 4:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 4, 'train_loss': 1.3726797723456432, 'tuning_auroc': np.float64(0.6093722271517302), 'tuning_auprc': np.float64(0.07149241446199188), 'tuning_brier': np.float64(0.1931993105055478), 'tuning_logloss': 0.5783596489407844}

epoch 5:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 5, 'train_loss': 1.3568235086767297, 'tuning_auroc': np.float64(0.5889696095829636), 'tuning_auprc': np.float64(0.07133589014308009), 'tuning_brier': np.float64(0.13279284389913074), 'tuning_logloss': 0.45031970143239536}
Early stopping at epoch 5

,task,version,model,calibration,heldout_auroc,heldout_auprc,heldout_brier,heldout_logloss
0,guo_icu,compressed_condition_era,LSTM_2L_numeric,raw,0.537325,0.056024,0.201857,0.596326
1,guo_icu,compressed_condition_era,LSTM_2L_numeric,platt,0.537325,0.056024,0.039919,0.172676

,task,version,model,calibration,top_frac,top_k,events_in_top_k,top_k_event_rate,top_k_lift,event_capture,base_event_rate,n,n_positive
4,guo_icu,compressed_condition_era,LSTM_2L_numeric,platt,0.01,21,0,0.000000,0.000000,0.000000,0.041728,2037,85
5,guo_icu,compressed_condition_era,LSTM_2L_numeric,platt,0.05,102,9,0.088235,2.114533,0.105882,0.041728,2037,85
6,guo_icu,compressed_condition_era,LSTM_2L_numeric,platt,0.10,204,15,0.073529,1.762111,0.176471,0.041728,2037,85
7,guo_icu,compressed_condition_era,LSTM_2L_numeric,platt,0.20,408,28,0.068627,1.644637,0.329412,0.041728,2037,85

====================================================================================================
Experiment: guo_icu | compressed_condition_era | RETAIN_lite_numeric

numeric stats:   0%|          | 0/2402 [00:00<?, ?it/s]

epoch 1:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 1, 'train_loss': 1.4660145483518903, 'tuning_auroc': np.float64(0.6682342502218279), 'tuning_auprc': np.float64(0.09046259513205901), 'tuning_brier': np.float64(0.2411801874917538), 'tuning_logloss': 0.6740827122570697}

epoch 2:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 2, 'train_loss': 1.3006620097317194, 'tuning_auroc': np.float64(0.6531721384205855), 'tuning_auprc': np.float64(0.0797605981094763), 'tuning_brier': np.float64(0.1277551848021902), 'tuning_logloss': 0.41138472826700345}

epoch 3:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 3, 'train_loss': 1.3236068408740194, 'tuning_auroc': np.float64(0.692413487133984), 'tuning_auprc': np.float64(0.10202202548942094), 'tuning_brier': np.float64(0.18779009516441825), 'tuning_logloss': 0.5526310503038481}

epoch 4:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 4, 'train_loss': 1.2984973231428547, 'tuning_auroc': np.float64(0.6779281277728483), 'tuning_auprc': np.float64(0.09219755927802376), 'tuning_brier': np.float64(0.25795468828076124), 'tuning_logloss': 0.6990542920202063}

epoch 5:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 5, 'train_loss': 1.2858992850309925, 'tuning_auroc': np.float64(0.6606588287488908), 'tuning_auprc': np.float64(0.07935668405797884), 'tuning_brier': np.float64(0.19242776931841424), 'tuning_logloss': 0.561010678203724}

epoch 6:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 6, 'train_loss': 1.2829709386355, 'tuning_auroc': np.float64(0.706283274179237), 'tuning_auprc': np.float64(0.10509976124612527), 'tuning_brier': np.float64(0.18091558071944341), 'tuning_logloss': 0.5360122840636294}

epoch 7:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 7, 'train_loss': 1.2646058876263468, 'tuning_auroc': np.float64(0.7627828305235138), 'tuning_auprc': np.float64(0.17791432074166086), 'tuning_brier': np.float64(0.10406313965223493), 'tuning_logloss': 0.3737417934102844}

epoch 8:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 8, 'train_loss': 1.2206081595075757, 'tuning_auroc': np.float64(0.7640361579414374), 'tuning_auprc': np.float64(0.16718127603031568), 'tuning_brier': np.float64(0.213796027293332), 'tuning_logloss': 0.6054567965952121}

epoch 9:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 9, 'train_loss': 1.2018248638824414, 'tuning_auroc': np.float64(0.7378881987577639), 'tuning_auprc': np.float64(0.1590671827578583), 'tuning_brier': np.float64(0.24635073607975191), 'tuning_logloss': 0.6938624874283177}

epoch 10:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 10, 'train_loss': 1.0980856309791929, 'tuning_auroc': np.float64(0.7557786157941437), 'tuning_auprc': np.float64(0.19377417012287967), 'tuning_brier': np.float64(0.061627359507557475), 'tuning_logloss': 0.2329504375526844}

epoch 11:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 11, 'train_loss': 1.1508429464148848, 'tuning_auroc': np.float64(0.7654447648624667), 'tuning_auprc': np.float64(0.21729259343423157), 'tuning_brier': np.float64(0.10965478455620448), 'tuning_logloss': 0.3641045946070688}

epoch 12:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 12, 'train_loss': 1.058794547656649, 'tuning_auroc': np.float64(0.755906166814552), 'tuning_auprc': np.float64(0.21785207882478178), 'tuning_brier': np.float64(0.16393060729579512), 'tuning_logloss': 0.4987398930457862}

,task,version,model,calibration,heldout_auroc,heldout_auprc,heldout_brier,heldout_logloss
0,guo_icu,compressed_condition_era,RETAIN_lite_numeric,raw,0.711795,0.157656,0.157053,0.480672
1,guo_icu,compressed_condition_era,RETAIN_lite_numeric,platt,0.711795,0.157656,0.038212,0.160026

,task,version,model,calibration,top_frac,top_k,events_in_top_k,top_k_event_rate,top_k_lift,event_capture,base_event_rate,n,n_positive
4,guo_icu,compressed_condition_era,RETAIN_lite_numeric,platt,0.01,21,5,0.238095,5.705882,0.058824,0.041728,2037,85
5,guo_icu,compressed_condition_era,RETAIN_lite_numeric,platt,0.05,102,22,0.215686,5.168858,0.258824,0.041728,2037,85
6,guo_icu,compressed_condition_era,RETAIN_lite_numeric,platt,0.10,204,28,0.137255,3.289273,0.329412,0.041728,2037,85
7,guo_icu,compressed_condition_era,RETAIN_lite_numeric,platt,0.20,408,43,0.105392,2.525692,0.505882,0.041728,2037,85

====================================================================================================
Experiment: guo_icu | compressed_hybrid | GRU_1L_numeric

numeric stats:   0%|          | 0/2402 [00:00<?, ?it/s]

epoch 1:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 1, 'train_loss': 1.492651971939363, 'tuning_auroc': np.float64(0.5771683673469388), 'tuning_auprc': np.float64(0.07709635486465118), 'tuning_brier': np.float64(0.08273290625743308), 'tuning_logloss': 0.3301100157603753}

epoch 2:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 2, 'train_loss': 1.4175859250520404, 'tuning_auroc': np.float64(0.6025399290150844), 'tuning_auprc': np.float64(0.072995129408899), 'tuning_brier': np.float64(0.20436634097535394), 'tuning_logloss': 0.6006767927702057}

epoch 3:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 3, 'train_loss': 1.3752405976778583, 'tuning_auroc': np.float64(0.6091393078970718), 'tuning_auprc': np.float64(0.08107345625156084), 'tuning_brier': np.float64(0.16335078545413476), 'tuning_logloss': 0.5146143401050552}

epoch 4:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 4, 'train_loss': 1.4109640490067632, 'tuning_auroc': np.float64(0.623447204968944), 'tuning_auprc': np.float64(0.08993053899869113), 'tuning_brier': np.float64(0.12383079782035232), 'tuning_logloss': 0.42685461244775613}

epoch 5:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 5, 'train_loss': 1.3425125016977912, 'tuning_auroc': np.float64(0.6363742236024845), 'tuning_auprc': np.float64(0.11670409903252191), 'tuning_brier': np.float64(0.24164644555015177), 'tuning_logloss': 0.676310217532321}

epoch 6:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 6, 'train_loss': 1.2878360277728031, 'tuning_auroc': np.float64(0.6643300798580303), 'tuning_auprc': np.float64(0.13688353182019372), 'tuning_brier': np.float64(0.11726156413345601), 'tuning_logloss': 0.4126021483755669}

epoch 7:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 7, 'train_loss': 1.2973232175174512, 'tuning_auroc': np.float64(0.5483473824312334), 'tuning_auprc': np.float64(0.09224991672626723), 'tuning_brier': np.float64(0.09736538246210914), 'tuning_logloss': 0.3570660922833312}

epoch 8:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 8, 'train_loss': 1.2340821808106022, 'tuning_auroc': np.float64(0.6847437888198759), 'tuning_auprc': np.float64(0.14531123988355676), 'tuning_brier': np.float64(0.0823384067294037), 'tuning_logloss': 0.3017558766829812}

epoch 9:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 9, 'train_loss': 1.0083119760414487, 'tuning_auroc': np.float64(0.7624889086069212), 'tuning_auprc': np.float64(0.17660771413881562), 'tuning_brier': np.float64(0.2196625250689336), 'tuning_logloss': 0.6733148844485527}

epoch 10:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 10, 'train_loss': 1.0069305354141092, 'tuning_auroc': np.float64(0.7917757320319432), 'tuning_auprc': np.float64(0.22625251494408405), 'tuning_brier': np.float64(0.10168106075706182), 'tuning_logloss': 0.3319566188426493}

epoch 11:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 11, 'train_loss': 0.8791708115880427, 'tuning_auroc': np.float64(0.7834627329192547), 'tuning_auprc': np.float64(0.21460968644173653), 'tuning_brier': np.float64(0.04965337794530265), 'tuning_logloss': 0.18794688469235804}

epoch 12:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 12, 'train_loss': 0.7542834322115308, 'tuning_auroc': np.float64(0.7866293256433008), 'tuning_auprc': np.float64(0.240089138128988), 'tuning_brier': np.float64(0.03964765436551492), 'tuning_logloss': 0.16929990677995946}

,task,version,model,calibration,heldout_auroc,heldout_auprc,heldout_brier,heldout_logloss
0,guo_icu,compressed_hybrid,GRU_1L_numeric,raw,0.752622,0.169747,0.043150,0.184075
1,guo_icu,compressed_hybrid,GRU_1L_numeric,platt,0.752622,0.169747,0.039449,0.159204

,task,version,model,calibration,top_frac,top_k,events_in_top_k,top_k_event_rate,top_k_lift,event_capture,base_event_rate,n,n_positive
4,guo_icu,compressed_hybrid,GRU_1L_numeric,platt,0.01,21,6,0.285714,6.847059,0.070588,0.041728,2037,85
5,guo_icu,compressed_hybrid,GRU_1L_numeric,platt,0.05,102,20,0.196078,4.698962,0.235294,0.041728,2037,85
6,guo_icu,compressed_hybrid,GRU_1L_numeric,platt,0.10,204,31,0.151961,3.641696,0.364706,0.041728,2037,85
7,guo_icu,compressed_hybrid,GRU_1L_numeric,platt,0.20,408,49,0.120098,2.878114,0.576471,0.041728,2037,85

====================================================================================================
Experiment: guo_icu | compressed_hybrid | GRU_2L_numeric

numeric stats:   0%|          | 0/2402 [00:00<?, ?it/s]

epoch 1:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 1, 'train_loss': 1.4890841904439425, 'tuning_auroc': np.float64(0.6109915705412599), 'tuning_auprc': np.float64(0.07820256872701363), 'tuning_brier': np.float64(0.10967674486533907), 'tuning_logloss': 0.3979375952648013}

epoch 2:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 2, 'train_loss': 1.3495969740968001, 'tuning_auroc': np.float64(0.6098824312333628), 'tuning_auprc': np.float64(0.07624042862655334), 'tuning_brier': np.float64(0.10532206959171315), 'tuning_logloss': 0.387263429780199}

epoch 3:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 3, 'train_loss': 1.3516401844589334, 'tuning_auroc': np.float64(0.6134926796805679), 'tuning_auprc': np.float64(0.07671457861248317), 'tuning_brier': np.float64(0.17709999660174897), 'tuning_logloss': 0.5440608163315896}

epoch 4:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 4, 'train_loss': 1.39950595443186, 'tuning_auroc': np.float64(0.6167757320319431), 'tuning_auprc': np.float64(0.08196097643050343), 'tuning_brier': np.float64(0.15287164594639457), 'tuning_logloss': 0.49457335437878236}

epoch 5:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 5, 'train_loss': 1.3369743678914874, 'tuning_auroc': np.float64(0.6372282608695652), 'tuning_auprc': np.float64(0.08999671113439667), 'tuning_brier': np.float64(0.2526104055692663), 'tuning_logloss': 0.6986557083952121}

epoch 6:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 6, 'train_loss': 1.3885574885889103, 'tuning_auroc': np.float64(0.6488298580301686), 'tuning_auprc': np.float64(0.09435421870184482), 'tuning_brier': np.float64(0.08609469740099608), 'tuning_logloss': 0.33475143899586135}

epoch 7:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 7, 'train_loss': 1.2981149418965767, 'tuning_auroc': np.float64(0.7236191215616682), 'tuning_auprc': np.float64(0.1405393766633183), 'tuning_brier': np.float64(0.04394218932461256), 'tuning_logloss': 0.19148861655093294}

epoch 8:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 8, 'train_loss': 1.09399076453165, 'tuning_auroc': np.float64(0.7803405057675245), 'tuning_auprc': np.float64(0.2263276195352446), 'tuning_brier': np.float64(0.04138205213634377), 'tuning_logloss': 0.16436179901518483}

epoch 9:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 9, 'train_loss': 1.22757298430722, 'tuning_auroc': np.float64(0.80571206743567), 'tuning_auprc': np.float64(0.23737094884282348), 'tuning_brier': np.float64(0.24662942961223464), 'tuning_logloss': 0.8016740478029762}

epoch 10:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 10, 'train_loss': 1.2310298459702416, 'tuning_auroc': np.float64(0.7982697426796805), 'tuning_auprc': np.float64(0.23052189858533761), 'tuning_brier': np.float64(0.12882685718341463), 'tuning_logloss': 0.46778445867526536}

epoch 11:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 11, 'train_loss': 0.8533552874761977, 'tuning_auroc': np.float64(0.8067712954747116), 'tuning_auprc': np.float64(0.258402086393915), 'tuning_brier': np.float64(0.07089441463527346), 'tuning_logloss': 0.2676009450917565}

epoch 12:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 12, 'train_loss': 0.7506033171115345, 'tuning_auroc': np.float64(0.8004991126885537), 'tuning_auprc': np.float64(0.2691781234731421), 'tuning_brier': np.float64(0.05500697895632965), 'tuning_logloss': 0.22874166921387665}

,task,version,model,calibration,heldout_auroc,heldout_auprc,heldout_brier,heldout_logloss
0,guo_icu,compressed_hybrid,GRU_2L_numeric,raw,0.793605,0.215872,0.056325,0.236349
1,guo_icu,compressed_hybrid,GRU_2L_numeric,platt,0.793605,0.215872,0.038011,0.158068

,task,version,model,calibration,top_frac,top_k,events_in_top_k,top_k_event_rate,top_k_lift,event_capture,base_event_rate,n,n_positive
4,guo_icu,compressed_hybrid,GRU_2L_numeric,platt,0.01,21,9,0.428571,10.270588,0.105882,0.041728,2037,85
5,guo_icu,compressed_hybrid,GRU_2L_numeric,platt,0.05,102,19,0.186275,4.464014,0.223529,0.041728,2037,85
6,guo_icu,compressed_hybrid,GRU_2L_numeric,platt,0.10,204,35,0.171569,4.111592,0.411765,0.041728,2037,85
7,guo_icu,compressed_hybrid,GRU_2L_numeric,platt,0.20,408,53,0.129902,3.113062,0.623529,0.041728,2037,85

====================================================================================================
Experiment: guo_icu | compressed_hybrid | LSTM_1L_numeric

numeric stats:   0%|          | 0/2402 [00:00<?, ?it/s]

epoch 1:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 1, 'train_loss': 1.464486543677355, 'tuning_auroc': np.float64(0.5884372227151731), 'tuning_auprc': np.float64(0.08525478667772587), 'tuning_brier': np.float64(0.11706693693758004), 'tuning_logloss': 0.41570666026408615}

epoch 2:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 2, 'train_loss': 1.3761901016298093, 'tuning_auroc': np.float64(0.626896628216504), 'tuning_auprc': np.float64(0.08209466236198251), 'tuning_brier': np.float64(0.1685042879886941), 'tuning_logloss': 0.5268830675939392}

epoch 3:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 3, 'train_loss': 1.3427078990559829, 'tuning_auroc': np.float64(0.5430512422360247), 'tuning_auprc': np.float64(0.08040536915039381), 'tuning_brier': np.float64(0.11326820550838543), 'tuning_logloss': 0.403674173386908}

epoch 4:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 4, 'train_loss': 1.3066986218879098, 'tuning_auroc': np.float64(0.6023735581188998), 'tuning_auprc': np.float64(0.08656736560620171), 'tuning_brier': np.float64(0.15252893264755454), 'tuning_logloss': 0.490169401046606}

epoch 5:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 5, 'train_loss': 1.3722119225483191, 'tuning_auroc': np.float64(0.5914485359361136), 'tuning_auprc': np.float64(0.0973842443730356), 'tuning_brier': np.float64(0.28175517364025915), 'tuning_logloss': 0.75824441433492}

epoch 6:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 6, 'train_loss': 1.3144044593760842, 'tuning_auroc': np.float64(0.6285215173025732), 'tuning_auprc': np.float64(0.10424859372232134), 'tuning_brier': np.float64(0.18948750146096208), 'tuning_logloss': 0.5691018849857707}

epoch 7:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 7, 'train_loss': 1.2847075795656757, 'tuning_auroc': np.float64(0.6026785714285714), 'tuning_auprc': np.float64(0.0811941717321804), 'tuning_brier': np.float64(0.15311786366405367), 'tuning_logloss': 0.48976673059852255}

epoch 8:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 8, 'train_loss': 1.2758360787441856, 'tuning_auroc': np.float64(0.6526009316770186), 'tuning_auprc': np.float64(0.1181597701875428), 'tuning_brier': np.float64(0.25870350279404514), 'tuning_logloss': 0.7106004589691256}

epoch 9:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 9, 'train_loss': 1.271904249332453, 'tuning_auroc': np.float64(0.6130656610470275), 'tuning_auprc': np.float64(0.09160269115085685), 'tuning_brier': np.float64(0.1220997359945116), 'tuning_logloss': 0.4110188772971801}

epoch 10:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 10, 'train_loss': 1.2955799596874338, 'tuning_auroc': np.float64(0.7042424578527061), 'tuning_auprc': np.float64(0.12036248672282543), 'tuning_brier': np.float64(0.17863385199117965), 'tuning_logloss': 0.5331356168921877}

epoch 11:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 11, 'train_loss': 1.191092253417561, 'tuning_auroc': np.float64(0.6392080745341616), 'tuning_auprc': np.float64(0.13509351622639673), 'tuning_brier': np.float64(0.04952288587393839), 'tuning_logloss': 0.2042699681363182}

epoch 12:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 12, 'train_loss': 1.2259697454344285, 'tuning_auroc': np.float64(0.6704358917480036), 'tuning_auprc': np.float64(0.20433726430620072), 'tuning_brier': np.float64(0.05082737762429411), 'tuning_logloss': 0.2122735270461913}

,task,version,model,calibration,heldout_auroc,heldout_auprc,heldout_brier,heldout_logloss
0,guo_icu,compressed_hybrid,LSTM_1L_numeric,raw,0.648921,0.137506,0.052487,0.217120
1,guo_icu,compressed_hybrid,LSTM_1L_numeric,platt,0.648921,0.137506,0.038660,0.163931

,task,version,model,calibration,top_frac,top_k,events_in_top_k,top_k_event_rate,top_k_lift,event_capture,base_event_rate,n,n_positive
4,guo_icu,compressed_hybrid,LSTM_1L_numeric,platt,0.01,21,8,0.380952,9.129412,0.094118,0.041728,2037,85
5,guo_icu,compressed_hybrid,LSTM_1L_numeric,platt,0.05,102,18,0.176471,4.229066,0.211765,0.041728,2037,85
6,guo_icu,compressed_hybrid,LSTM_1L_numeric,platt,0.10,204,33,0.161765,3.876644,0.388235,0.041728,2037,85
7,guo_icu,compressed_hybrid,LSTM_1L_numeric,platt,0.20,408,40,0.098039,2.349481,0.470588,0.041728,2037,85

====================================================================================================
Experiment: guo_icu | compressed_hybrid | LSTM_2L_numeric

numeric stats:   0%|          | 0/2402 [00:00<?, ?it/s]

epoch 1:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 1, 'train_loss': 1.5203642147152048, 'tuning_auroc': np.float64(0.6253161047027507), 'tuning_auprc': np.float64(0.0788988645834325), 'tuning_brier': np.float64(0.2319502127272099), 'tuning_logloss': 0.6570161410922277}

epoch 2:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 2, 'train_loss': 1.3576547303482105, 'tuning_auroc': np.float64(0.6254713842058562), 'tuning_auprc': np.float64(0.07943799821392852), 'tuning_brier': np.float64(0.25415525079581996), 'tuning_logloss': 0.7015180678851274}

epoch 3:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 3, 'train_loss': 1.3662133663892746, 'tuning_auroc': np.float64(0.6351652617568766), 'tuning_auprc': np.float64(0.08286517220022255), 'tuning_brier': np.float64(0.07653730200387046), 'tuning_logloss': 0.3126040381960376}

epoch 4:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 4, 'train_loss': 1.4431805534190254, 'tuning_auroc': np.float64(0.6578582519964506), 'tuning_auprc': np.float64(0.08269944921433106), 'tuning_brier': np.float64(0.27542447154420074), 'tuning_logloss': 0.7455353799363305}

epoch 5:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 5, 'train_loss': 1.334054835140705, 'tuning_auroc': np.float64(0.6546057009760424), 'tuning_auprc': np.float64(0.08379553078841576), 'tuning_brier': np.float64(0.1449117934714645), 'tuning_logloss': 0.4751315289118335}

epoch 6:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 6, 'train_loss': 1.3133922760423862, 'tuning_auroc': np.float64(0.6179458740017746), 'tuning_auprc': np.float64(0.08541578989203992), 'tuning_brier': np.float64(0.14277734789792074), 'tuning_logloss': 0.46884377983483877}

epoch 7:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 7, 'train_loss': 1.526361718381706, 'tuning_auroc': np.float64(0.6402340283939663), 'tuning_auprc': np.float64(0.08279024611139546), 'tuning_brier': np.float64(0.23772831519146514), 'tuning_logloss': 0.6685959849602279}

epoch 8:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 8, 'train_loss': 1.349433291115259, 'tuning_auroc': np.float64(0.633706743566992), 'tuning_auprc': np.float64(0.08206639739447633), 'tuning_brier': np.float64(0.17917952881611207), 'tuning_logloss': 0.5500476190546604}

epoch 9:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 9, 'train_loss': 1.3140994698593491, 'tuning_auroc': np.float64(0.6290095385980479), 'tuning_auprc': np.float64(0.08462594993190384), 'tuning_brier': np.float64(0.1017705844220563), 'tuning_logloss': 0.3793908880389817}
Early stopping at epoch 9

,task,version,model,calibration,heldout_auroc,heldout_auprc,heldout_brier,heldout_logloss
0,guo_icu,compressed_hybrid,LSTM_2L_numeric,raw,0.626501,0.072029,0.144685,0.473271
1,guo_icu,compressed_hybrid,LSTM_2L_numeric,platt,0.626501,0.072029,0.039710,0.169815

,task,version,model,calibration,top_frac,top_k,events_in_top_k,top_k_event_rate,top_k_lift,event_capture,base_event_rate,n,n_positive
4,guo_icu,compressed_hybrid,LSTM_2L_numeric,platt,0.01,21,2,0.095238,2.282353,0.023529,0.041728,2037,85
5,guo_icu,compressed_hybrid,LSTM_2L_numeric,platt,0.05,102,11,0.107843,2.584429,0.129412,0.041728,2037,85
6,guo_icu,compressed_hybrid,LSTM_2L_numeric,platt,0.10,204,15,0.073529,1.762111,0.176471,0.041728,2037,85
7,guo_icu,compressed_hybrid,LSTM_2L_numeric,platt,0.20,408,34,0.083333,1.997059,0.400000,0.041728,2037,85

====================================================================================================
Experiment: guo_icu | compressed_hybrid | RETAIN_lite_numeric

numeric stats:   0%|          | 0/2402 [00:00<?, ?it/s]

epoch 1:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 1, 'train_loss': 1.352695056874501, 'tuning_auroc': np.float64(0.6499722715173025), 'tuning_auprc': np.float64(0.07345387641690626), 'tuning_brier': np.float64(0.19749995472828744), 'tuning_logloss': 0.577354626650028}

epoch 2:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 2, 'train_loss': 1.337186649441719, 'tuning_auroc': np.float64(0.6496561668145518), 'tuning_auprc': np.float64(0.07676675535461155), 'tuning_brier': np.float64(0.1941842010681358), 'tuning_logloss': 0.5685107748931503}

epoch 3:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 3, 'train_loss': 1.3011139341090854, 'tuning_auroc': np.float64(0.7107919254658386), 'tuning_auprc': np.float64(0.1451704004309711), 'tuning_brier': np.float64(0.10007344783240563), 'tuning_logloss': 0.35681874051488705}

epoch 4:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 4, 'train_loss': 1.2555388004371995, 'tuning_auroc': np.float64(0.754353371783496), 'tuning_auprc': np.float64(0.1947808063308294), 'tuning_brier': np.float64(0.341147298270905), 'tuning_logloss': 0.9023786658785129}

epoch 5:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 5, 'train_loss': 1.1755233277615749, 'tuning_auroc': np.float64(0.7724101597160603), 'tuning_auprc': np.float64(0.2556708324575317), 'tuning_brier': np.float64(0.06515756489057034), 'tuning_logloss': 0.26483657184225007}

epoch 6:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 6, 'train_loss': 1.1247972312726473, 'tuning_auroc': np.float64(0.7683174356699201), 'tuning_auprc': np.float64(0.22583010461013817), 'tuning_brier': np.float64(0.0953926216977842), 'tuning_logloss': 0.324303322566881}

epoch 7:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 7, 'train_loss': 1.093795024446751, 'tuning_auroc': np.float64(0.7684061668145519), 'tuning_auprc': np.float64(0.1818034267087216), 'tuning_brier': np.float64(0.12858904391003695), 'tuning_logloss': 0.4263664555227542}

epoch 8:   0%|          | 0/76 [00:00<?, ?it/s]

{'epoch': 8, 'train_loss': 1.0773397035112506, 'tuning_auroc': np.float64(0.7645629991126885), 'tuning_auprc': np.float64(0.22935361384996175), 'tuning_brier': np.float64(0.10138038260525525), 'tuning_logloss': 0.3518124635834262}
Early stopping at epoch 8

,task,version,model,calibration,heldout_auroc,heldout_auprc,heldout_brier,heldout_logloss
0,guo_icu,compressed_hybrid,RETAIN_lite_numeric,raw,0.731527,0.164009,0.065393,0.266272
1,guo_icu,compressed_hybrid,RETAIN_lite_numeric,platt,0.731527,0.164009,0.037441,0.154758

,task,version,model,calibration,top_frac,top_k,events_in_top_k,top_k_event_rate,top_k_lift,event_capture,base_event_rate,n,n_positive
4,guo_icu,compressed_hybrid,RETAIN_lite_numeric,platt,0.01,21,7,0.333333,7.988235,0.082353,0.041728,2037,85
5,guo_icu,compressed_hybrid,RETAIN_lite_numeric,platt,0.05,102,24,0.235294,5.638754,0.282353,0.041728,2037,85
6,guo_icu,compressed_hybrid,RETAIN_lite_numeric,platt,0.10,204,35,0.171569,4.111592,0.411765,0.041728,2037,85
7,guo_icu,compressed_hybrid,RETAIN_lite_numeric,platt,0.20,408,46,0.112745,2.701903,0.541176,0.041728,2037,85

,task,version,model,calibration,n_tuning,n_heldout,n_positive_heldout,event_rate_heldout,heldout_auroc,heldout_auprc,heldout_brier,heldout_logloss
92,guo_icu,compressed_hybrid,GRU_2L_numeric,raw,2052,2037,85,0.041728,0.793605,0.215872,0.056325,0.236349
93,guo_icu,compressed_hybrid,GRU_2L_numeric,platt,2052,2037,85,0.041728,0.793605,0.215872,0.038011,0.158068
50,guo_icu,raw,GRU_1L_numeric,raw,2052,2037,85,0.041728,0.724602,0.180168,0.079329,0.289808
51,guo_icu,raw,GRU_1L_numeric,platt,2052,2037,85,0.041728,0.724602,0.180168,0.037878,0.156879
70,guo_icu,compressed_first_last,GRU_1L_numeric,raw,2052,2037,85,0.041728,0.713410,0.177232,0.042135,0.169255
...,...,...,...,...,...,...,...,...,...,...,...,...
1,guo_readmission,raw,GRU_1L_numeric,platt,2206,2189,260,0.118776,0.687341,0.267068,0.097802,0.338444
14,guo_readmission,compressed_dedup,LSTM_1L_numeric,raw,2206,2189,260,0.118776,0.703348,0.261853,0.165523,0.515394
15,guo_readmission,compressed_dedup,LSTM_1L_numeric,platt,2206,2189,260,0.118776,0.703348,0.261853,0.097076,0.334172
30,guo_readmission,compressed_condition_era,GRU_1L_numeric,raw,2206,2189,260,0.118776,0.684332,0.260262,0.230141,0.658154
31,guo_readmission,compressed_condition_era,GRU_1L_numeric,platt,2206,2189,260,0.118776,0.684332,0.260262,0.098214,0.339242

## 10. Compare with previous code-only sequence baseline

In [19]:
PREVIOUS_SEQUENCE_RESULTS_PATH = Path("ehrshot_sequence_results/sequence_baseline_results.csv")

if PREVIOUS_SEQUENCE_RESULTS_PATH.exists():
    prev = pd.read_csv(PREVIOUS_SEQUENCE_RESULTS_PATH)
    prev = prev[prev["calibration"] == "platt"].copy()
    curr = sequence_numeric_results_df[sequence_numeric_results_df["calibration"] == "platt"].copy()

    prev_best = (
        prev.sort_values(["task", "version", "heldout_auprc"], ascending=[True, True, False])
        .groupby(["task", "version"], as_index=False)
        .head(1)
        [["task", "version", "model", "heldout_auroc", "heldout_auprc", "heldout_brier", "heldout_logloss"]]
        .rename(columns={"model": "best_code_only_model", "heldout_auroc": "code_only_auroc", "heldout_auprc": "code_only_auprc", "heldout_brier": "code_only_brier", "heldout_logloss": "code_only_logloss"})
    )
    curr_best = (
        curr.sort_values(["task", "version", "heldout_auprc"], ascending=[True, True, False])
        .groupby(["task", "version"], as_index=False)
        .head(1)
        [["task", "version", "model", "heldout_auroc", "heldout_auprc", "heldout_brier", "heldout_logloss"]]
        .rename(columns={"model": "best_numeric_model", "heldout_auroc": "numeric_auroc", "heldout_auprc": "numeric_auprc", "heldout_brier": "numeric_brier", "heldout_logloss": "numeric_logloss"})
    )
    cmp_df = prev_best.merge(curr_best, on=["task", "version"], how="inner")
    cmp_df["delta_auroc_numeric_minus_code_only"] = cmp_df["numeric_auroc"] - cmp_df["code_only_auroc"]
    cmp_df["delta_auprc_numeric_minus_code_only"] = cmp_df["numeric_auprc"] - cmp_df["code_only_auprc"]
    cmp_df["delta_brier_numeric_minus_code_only"] = cmp_df["numeric_brier"] - cmp_df["code_only_brier"]
    cmp_df["delta_logloss_numeric_minus_code_only"] = cmp_df["numeric_logloss"] - cmp_df["code_only_logloss"]
    cmp_df.to_csv(RESULTS_DIR / "numeric_vs_code_only_best_by_task_version.csv", index=False)
    display(cmp_df)
else:
    print("Previous results CSV not found:", PREVIOUS_SEQUENCE_RESULTS_PATH)

,task,version,best_code_only_model,code_only_auroc,code_only_auprc,code_only_brier,code_only_logloss,best_numeric_model,numeric_auroc,numeric_auprc,numeric_brier,numeric_logloss,delta_auroc_numeric_minus_code_only,delta_auprc_numeric_minus_code_only,delta_brier_numeric_minus_code_only,delta_logloss_numeric_minus_code_only
0,guo_icu,compressed_condition_era,LSTM_1L,0.722191,0.184673,0.037907,0.157627,GRU_2L_numeric,0.770287,0.170596,0.038209,0.158038,0.048095,-0.014077,0.000302,0.000410
1,guo_icu,compressed_dedup,GRU_1L,0.745474,0.151499,0.037885,0.155611,RETAIN_lite_numeric,0.753236,0.158373,0.038032,0.155685,0.007763,0.006874,0.000147,0.000074
2,guo_icu,compressed_first_last,GRU_2L,0.715929,0.149425,0.038502,0.160899,GRU_1L_numeric,0.713410,0.177232,0.037622,0.155315,-0.002519,0.027806,-0.000881,-0.005584
3,guo_icu,compressed_hybrid,LSTM_2L,0.693846,0.152087,0.038475,0.162373,GRU_2L_numeric,0.793605,0.215872,0.038011,0.158068,0.099759,0.063785,-0.000463,-0.004306
4,guo_icu,raw,LSTM_1L,0.711391,0.146446,0.038049,0.157459,GRU_1L_numeric,0.724602,0.180168,0.037878,0.156879,0.013211,0.033722,-0.000170,-0.000580
5,guo_readmission,compressed_condition_era,RETAIN_lite,0.769033,0.338576,0.092244,0.313725,RETAIN_lite_numeric,0.754528,0.345361,0.091972,0.316718,-0.014505,0.006785,-0.000272,0.002993
6,guo_readmission,compressed_dedup,RETAIN_lite,0.781585,0.382325,0.089831,0.307238,RETAIN_lite_numeric,0.776034,0.376194,0.088144,0.304184,-0.005551,-0.006132,-0.001687,-0.003055
7,guo_readmission,compressed_first_last,RETAIN_lite,0.762739,0.353660,0.091631,0.314384,RETAIN_lite_numeric,0.771829,0.371733,0.089774,0.308885,0.009090,0.018073,-0.001856,-0.005499
8,guo_readmission,compressed_hybrid,RETAIN_lite,0.767205,0.364681,0.090536,0.310999,RETAIN_lite_numeric,0.777451,0.364969,0.091712,0.313266,0.010246,0.000288,0.001176,0.002266
9,guo_readmission,raw,RETAIN_lite,0.729218,0.314486,0.094349,0.325476,RETAIN_lite_numeric,0.772471,0.380255,0.089038,0.307085,0.043253,0.065768,-0.005311,-0.018391

## Bootstrap CI for numeric-aware sequence results

Bootstrap CI below is computed over held-out prediction examples. This is consistent with the previous code-only sequence baseline. A stricter patient-level bootstrap is possible, but was not used here because it is substantially slower and not required for the current comparison.

In [21]:
# Pick numeric results / predictions dataframes

if "sequence_numeric_results_df" in globals():
    numeric_results_df = sequence_numeric_results_df.copy()
else:
    raise NameError(
        "Не найден results dataframe. Ожидаю sequence_numeric_results_df или sequence_results_df."
    )


if "sequence_numeric_predictions_df" in globals():
    numeric_predictions_df = sequence_numeric_predictions_df.copy()
else:
    prediction_files = sorted(RESULTS_DIR.glob("*__heldout_predictions.csv"))

    if len(prediction_files) == 0:
        raise FileNotFoundError(
            f"No heldout prediction files found in {RESULTS_DIR}."
        )

    numeric_predictions_df = pd.concat(
        [pd.read_csv(path) for path in prediction_files],
        ignore_index=True,
    )


required_result_cols = {
    "task",
    "version",
    "model",
    "calibration",
    "heldout_auprc",
    "heldout_auroc",
    "heldout_brier",
}

missing_result_cols = required_result_cols - set(numeric_results_df.columns)
if missing_result_cols:
    raise ValueError(f"Missing result columns: {missing_result_cols}")


required_pred_cols = {
    "task",
    "version",
    "model",
    "calibration",
    "y_true",
    "risk",
}

missing_pred_cols = required_pred_cols - set(numeric_predictions_df.columns)
if missing_pred_cols:
    raise ValueError(f"Missing prediction columns: {missing_pred_cols}")


numeric_predictions_df["y_true"] = numeric_predictions_df["y_true"].astype(int)
numeric_predictions_df["risk"] = numeric_predictions_df["risk"].astype(float)

print("numeric_results_df:", numeric_results_df.shape)
print("numeric_predictions_df:", numeric_predictions_df.shape)

display(numeric_results_df.head())
display(numeric_predictions_df.head())

numeric_results_df: (100, 12)
numeric_predictions_df: (211300, 9)

,task,version,model,calibration,n_tuning,n_heldout,n_positive_heldout,event_rate_heldout,heldout_auroc,heldout_auprc,heldout_brier,heldout_logloss
0,guo_readmission,raw,GRU_1L_numeric,raw,2206,2189,260,0.118776,0.687341,0.267068,0.170771,0.519469
1,guo_readmission,raw,GRU_1L_numeric,platt,2206,2189,260,0.118776,0.687341,0.267068,0.097802,0.338444
2,guo_readmission,raw,GRU_2L_numeric,raw,2206,2189,260,0.118776,0.744148,0.328227,0.107992,0.358488
3,guo_readmission,raw,GRU_2L_numeric,platt,2206,2189,260,0.118776,0.744148,0.328227,0.092704,0.318963
4,guo_readmission,raw,LSTM_1L_numeric,raw,2206,2189,260,0.118776,0.735385,0.291786,0.189810,0.571372

,task,version,model,calibration,row_id,subject_id,y_true,risk,logit
0,guo_readmission,raw,GRU_1L_numeric,raw,3,115972225,0,0.204805,-1.356528
1,guo_readmission,raw,GRU_1L_numeric,raw,6,115973293,0,0.120283,-1.989750
2,guo_readmission,raw,GRU_1L_numeric,raw,7,115973293,0,0.177194,-1.535477
3,guo_readmission,raw,GRU_1L_numeric,raw,22,115972475,0,0.165649,-1.616783
4,guo_readmission,raw,GRU_1L_numeric,raw,23,115972475,0,0.246309,-1.118397

In [23]:
# Fast bootstrap CI for numeric-aware sequence results

import numpy as np
import pandas as pd

from sklearn.metrics import (
    roc_auc_score,
    average_precision_score,
    brier_score_loss,
    log_loss,
)

N_BOOTSTRAP = 1000
BOOTSTRAP_SEED = 42

BOOTSTRAP_CI_PATH = RESULTS_DIR / "sequence_numeric_bootstrap_ci.csv"


def bootstrap_metric_ci(
    y_true,
    y_prob,
    metric_fn,
    n_bootstrap: int = N_BOOTSTRAP,
    ci: float = 0.95,
    random_state: int = BOOTSTRAP_SEED,
):
    rng = np.random.default_rng(random_state)

    y_true = np.asarray(y_true).astype(int)
    y_prob = np.asarray(y_prob).astype(float)

    n = len(y_true)
    values = []

    for _ in range(n_bootstrap):
        idx = rng.integers(0, n, size=n)

        y_b = y_true[idx]
        p_b = y_prob[idx]

        try:
            value = metric_fn(y_b, p_b)
        except Exception:
            value = np.nan

        values.append(value)

    values = np.asarray(values, dtype=float)
    values = values[~np.isnan(values)]

    alpha = 1 - ci

    return {
        "mean": float(np.mean(values)) if len(values) else np.nan,
        "ci_low": float(np.quantile(values, alpha / 2)) if len(values) else np.nan,
        "ci_high": float(np.quantile(values, 1 - alpha / 2)) if len(values) else np.nan,
        "n_bootstrap_valid": int(len(values)),
    }


def auroc_metric(y, p):
    return roc_auc_score(y, p) if len(np.unique(y)) > 1 else np.nan


def auprc_metric(y, p):
    return average_precision_score(y, p) if len(np.unique(y)) > 1 else np.nan


def brier_metric(y, p):
    p = np.clip(p, 1e-6, 1 - 1e-6)
    return brier_score_loss(y, p)


def logloss_metric(y, p):
    p = np.clip(p, 1e-6, 1 - 1e-6)
    return log_loss(y, p, labels=[0, 1])


def topk_precision_metric(k_fraction: float):
    def metric(y, p):
        y = np.asarray(y).astype(int)
        p = np.asarray(p).astype(float)

        n_top = max(1, int(np.ceil(len(y) * k_fraction)))
        order = np.argsort(-p)

        return float(y[order[:n_top]].mean())

    return metric

In [24]:
# Fast bootstrap for best numeric model per task/version

best_platt_numeric = (
    numeric_results_df[numeric_results_df["calibration"] == "platt"]
    .sort_values(
        ["task", "version", "heldout_auprc"],
        ascending=[True, True, False],
    )
    .groupby(["task", "version"], as_index=False)
    .head(1)
    .reset_index(drop=True)
)

display(
    best_platt_numeric[
        [
            "task",
            "version",
            "model",
            "heldout_auprc",
            "heldout_auroc",
            "heldout_brier",
        ]
    ]
)

bootstrap_rows = []

metrics_to_bootstrap = [
    ("auroc", auroc_metric),
    ("auprc", auprc_metric),
    ("brier", brier_metric),
    ("logloss", logloss_metric),
    ("top_1pct_precision", topk_precision_metric(0.01)),
    ("top_5pct_precision", topk_precision_metric(0.05)),
    ("top_10pct_precision", topk_precision_metric(0.10)),
    ("top_20pct_precision", topk_precision_metric(0.20)),
]

for _, row in best_platt_numeric.iterrows():
    pred = numeric_predictions_df[
        (numeric_predictions_df["task"] == row["task"])
        & (numeric_predictions_df["version"] == row["version"])
        & (numeric_predictions_df["model"] == row["model"])
        & (numeric_predictions_df["calibration"] == "platt")
    ].copy()

    if len(pred) == 0:
        print("No predictions for:", row["task"], row["version"], row["model"])
        continue

    y = pred["y_true"].to_numpy()
    p = pred["risk"].to_numpy()

    n = len(y)
    n_positive = int(y.sum())
    event_rate = float(y.mean())

    print(
        f'Bootstrap: task={row["task"]}, version={row["version"]}, '
        f'model={row["model"]}, n={n}, positives={n_positive}'
    )

    for metric_name, metric_fn in metrics_to_bootstrap:
        ci_result = bootstrap_metric_ci(
            y_true=y,
            y_prob=p,
            metric_fn=metric_fn,
            n_bootstrap=N_BOOTSTRAP,
            random_state=BOOTSTRAP_SEED,
        )

        bootstrap_rows.append({
            "task": row["task"],
            "version": row["version"],
            "model": row["model"],
            "calibration": "platt",
            "metric": metric_name,
            **ci_result,
            "n": n,
            "n_positive": n_positive,
            "event_rate": event_rate,
            "n_bootstrap_requested": N_BOOTSTRAP,
            "bootstrap_level": "prediction_example",
        })

sequence_numeric_bootstrap_ci_df = pd.DataFrame(bootstrap_rows)

sequence_numeric_bootstrap_ci_df.to_csv(BOOTSTRAP_CI_PATH, index=False)

print("Saved:", BOOTSTRAP_CI_PATH)

display(
    sequence_numeric_bootstrap_ci_df
    .sort_values(["task", "version", "metric"])
)

,task,version,model,heldout_auprc,heldout_auroc,heldout_brier
0,guo_icu,compressed_condition_era,GRU_2L_numeric,0.170596,0.770287,0.038209
1,guo_icu,compressed_dedup,RETAIN_lite_numeric,0.158373,0.753236,0.038032
2,guo_icu,compressed_first_last,GRU_1L_numeric,0.177232,0.713410,0.037622
3,guo_icu,compressed_hybrid,GRU_2L_numeric,0.215872,0.793605,0.038011
4,guo_icu,raw,GRU_1L_numeric,0.180168,0.724602,0.037878
5,guo_readmission,compressed_condition_era,RETAIN_lite_numeric,0.345361,0.754528,0.091972
6,guo_readmission,compressed_dedup,RETAIN_lite_numeric,0.376194,0.776034,0.088144
7,guo_readmission,compressed_first_last,RETAIN_lite_numeric,0.371733,0.771829,0.089774
8,guo_readmission,compressed_hybrid,RETAIN_lite_numeric,0.364969,0.777451,0.091712
9,guo_readmission,raw,RETAIN_lite_numeric,0.380255,0.772471,0.089038

Bootstrap: task=guo_icu, version=compressed_condition_era, model=GRU_2L_numeric, n=2037, positives=85
Bootstrap: task=guo_icu, version=compressed_dedup, model=RETAIN_lite_numeric, n=2037, positives=85
Bootstrap: task=guo_icu, version=compressed_first_last, model=GRU_1L_numeric, n=2037, positives=85
Bootstrap: task=guo_icu, version=compressed_hybrid, model=GRU_2L_numeric, n=2037, positives=85
Bootstrap: task=guo_icu, version=raw, model=GRU_1L_numeric, n=2037, positives=85
Bootstrap: task=guo_readmission, version=compressed_condition_era, model=RETAIN_lite_numeric, n=2189, positives=260
Bootstrap: task=guo_readmission, version=compressed_dedup, model=RETAIN_lite_numeric, n=2189, positives=260
Bootstrap: task=guo_readmission, version=compressed_first_last, model=RETAIN_lite_numeric, n=2189, positives=260
Bootstrap: task=guo_readmission, version=compressed_hybrid, model=RETAIN_lite_numeric, n=2189, positives=260
Bootstrap: task=guo_readmission, version=raw, model=RETAIN_lite_numeric, n=2189, positives=260
Saved: ehrshot_sequence_numeric_results/sequence_numeric_bootstrap_ci.csv

,task,version,model,calibration,metric,mean,ci_low,ci_high,n_bootstrap_valid,n,n_positive,event_rate,n_bootstrap_requested,bootstrap_level
1,guo_icu,compressed_condition_era,GRU_2L_numeric,platt,auprc,0.180442,0.113818,0.260746,1000,2037,85,0.041728,1000,prediction_example
0,guo_icu,compressed_condition_era,GRU_2L_numeric,platt,auroc,0.769994,0.720161,0.819707,1000,2037,85,0.041728,1000,prediction_example
2,guo_icu,compressed_condition_era,GRU_2L_numeric,platt,brier,0.038251,0.030879,0.045172,1000,2037,85,0.041728,1000,prediction_example
3,guo_icu,compressed_condition_era,GRU_2L_numeric,platt,logloss,0.158170,0.132536,0.182575,1000,2037,85,0.041728,1000,prediction_example
6,guo_icu,compressed_condition_era,GRU_2L_numeric,platt,top_10pct_precision,0.132833,0.088235,0.181373,1000,2037,85,0.041728,1000,prediction_example
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,guo_readmission,raw,RETAIN_lite_numeric,platt,logloss,0.307485,0.284928,0.332358,1000,2189,260,0.118776,1000,prediction_example
78,guo_readmission,raw,RETAIN_lite_numeric,platt,top_10pct_precision,0.430566,0.369863,0.502283,1000,2189,260,0.118776,1000,prediction_example
76,guo_readmission,raw,RETAIN_lite_numeric,platt,top_1pct_precision,0.625727,0.409091,0.818182,1000,2189,260,0.118776,1000,prediction_example
79,guo_readmission,raw,RETAIN_lite_numeric,platt,top_20pct_precision,0.327847,0.283105,0.374429,1000,2189,260,0.118776,1000,prediction_example
77,guo_readmission,raw,RETAIN_lite_numeric,platt,top_5pct_precision,0.527773,0.427273,0.627500,1000,2189,260,0.118776,1000,prediction_example

In [25]:
# Compact bootstrap table

main_metric_table = (
    sequence_numeric_bootstrap_ci_df[
        sequence_numeric_bootstrap_ci_df["metric"].isin(["auroc", "auprc", "brier", "logloss"])
    ]
    .copy()
)

main_metric_table["mean_ci"] = main_metric_table.apply(
    lambda r: f'{r["mean"]:.3f} [{r["ci_low"]:.3f}, {r["ci_high"]:.3f}]',
    axis=1,
)

main_metric_table = (
    main_metric_table
    .pivot_table(
        index=["task", "version", "model"],
        columns="metric",
        values="mean_ci",
        aggfunc="first",
    )
    .reset_index()
)

display(main_metric_table)


topk_table = (
    sequence_numeric_bootstrap_ci_df[
        sequence_numeric_bootstrap_ci_df["metric"].str.contains("top_")
    ]
    .copy()
)

topk_table["mean_ci"] = topk_table.apply(
    lambda r: f'{r["mean"]:.3f} [{r["ci_low"]:.3f}, {r["ci_high"]:.3f}]',
    axis=1,
)

topk_table = (
    topk_table
    .pivot_table(
        index=["task", "version", "model"],
        columns="metric",
        values="mean_ci",
        aggfunc="first",
    )
    .reset_index()
)

display(topk_table)

metric,task,version,model,auprc,auroc,brier,logloss
0,guo_icu,compressed_condition_era,GRU_2L_numeric,"0.180 [0.114, 0.261]","0.770 [0.720, 0.820]","0.038 [0.031, 0.045]","0.158 [0.133, 0.183]"
1,guo_icu,compressed_dedup,RETAIN_lite_numeric,"0.166 [0.103, 0.238]","0.753 [0.698, 0.803]","0.038 [0.031, 0.045]","0.156 [0.132, 0.181]"
2,guo_icu,compressed_first_last,GRU_1L_numeric,"0.188 [0.122, 0.273]","0.713 [0.644, 0.779]","0.038 [0.031, 0.045]","0.155 [0.131, 0.181]"
3,guo_icu,compressed_hybrid,GRU_2L_numeric,"0.222 [0.144, 0.317]","0.794 [0.740, 0.839]","0.038 [0.031, 0.045]","0.158 [0.132, 0.184]"
4,guo_icu,raw,GRU_1L_numeric,"0.187 [0.114, 0.273]","0.724 [0.666, 0.784]","0.038 [0.031, 0.045]","0.157 [0.132, 0.182]"
5,guo_readmission,compressed_condition_era,RETAIN_lite_numeric,"0.351 [0.292, 0.413]","0.755 [0.720, 0.787]","0.092 [0.084, 0.101]","0.317 [0.294, 0.343]"
6,guo_readmission,compressed_dedup,RETAIN_lite_numeric,"0.380 [0.319, 0.445]","0.776 [0.742, 0.807]","0.088 [0.080, 0.097]","0.305 [0.282, 0.329]"
7,guo_readmission,compressed_first_last,RETAIN_lite_numeric,"0.374 [0.314, 0.439]","0.772 [0.736, 0.805]","0.090 [0.082, 0.099]","0.309 [0.287, 0.333]"
8,guo_readmission,compressed_hybrid,RETAIN_lite_numeric,"0.366 [0.311, 0.428]","0.777 [0.745, 0.807]","0.092 [0.083, 0.100]","0.314 [0.291, 0.338]"
9,guo_readmission,raw,RETAIN_lite_numeric,"0.382 [0.320, 0.446]","0.772 [0.738, 0.804]","0.089 [0.081, 0.098]","0.307 [0.285, 0.332]"

metric,task,version,model,top_10pct_precision,top_1pct_precision,top_20pct_precision,top_5pct_precision
0,guo_icu,compressed_condition_era,GRU_2L_numeric,"0.133 [0.088, 0.181]","0.356 [0.143, 0.571]","0.120 [0.088, 0.157]","0.213 [0.137, 0.294]"
1,guo_icu,compressed_dedup,RETAIN_lite_numeric,"0.161 [0.113, 0.216]","0.298 [0.095, 0.524]","0.115 [0.083, 0.147]","0.191 [0.118, 0.265]"
2,guo_icu,compressed_first_last,GRU_1L_numeric,"0.182 [0.127, 0.240]","0.371 [0.189, 0.571]","0.112 [0.081, 0.147]","0.259 [0.176, 0.353]"
3,guo_icu,compressed_hybrid,GRU_2L_numeric,"0.168 [0.118, 0.221]","0.460 [0.238, 0.714]","0.129 [0.098, 0.164]","0.188 [0.108, 0.275]"
4,guo_icu,raw,GRU_1L_numeric,"0.161 [0.113, 0.216]","0.356 [0.143, 0.571]","0.109 [0.081, 0.142]","0.205 [0.127, 0.285]"
5,guo_readmission,compressed_condition_era,RETAIN_lite_numeric,"0.403 [0.338, 0.470]","0.574 [0.318, 0.773]","0.309 [0.267, 0.358]","0.520 [0.418, 0.618]"
6,guo_readmission,compressed_dedup,RETAIN_lite_numeric,"0.449 [0.384, 0.521]","0.600 [0.364, 0.818]","0.347 [0.297, 0.397]","0.512 [0.409, 0.609]"
7,guo_readmission,compressed_first_last,RETAIN_lite_numeric,"0.436 [0.370, 0.502]","0.594 [0.364, 0.818]","0.331 [0.288, 0.377]","0.474 [0.373, 0.573]"
8,guo_readmission,compressed_hybrid,RETAIN_lite_numeric,"0.379 [0.315, 0.447]","0.662 [0.455, 0.864]","0.315 [0.274, 0.363]","0.500 [0.391, 0.609]"
9,guo_readmission,raw,RETAIN_lite_numeric,"0.431 [0.370, 0.502]","0.626 [0.409, 0.818]","0.328 [0.283, 0.374]","0.528 [0.427, 0.627]"

## 11. Upload artifacts to ClearML

In [17]:
if task is not None:
    task.upload_artifact("sequence_numeric_results", sequence_numeric_results_df)
    task.upload_artifact("sequence_numeric_topk", sequence_numeric_topk_df)
    task.upload_artifact("numeric_coverage_sequence_length", numeric_coverage_df)
    task.upload_artifact("results_dir", str(RESULTS_DIR))
    print("Uploaded artifacts to ClearML")
else:
    print("ClearML disabled; artifacts are saved locally in", RESULTS_DIR)

ClearML disabled; artifacts are saved locally in ehrshot_sequence_numeric_results

In [26]:
tabular_reference_df = pd.DataFrame([
    {
        "task": "guo_readmission",
        "reference": "tabular HistGradientBoosting + Platt",
        "auroc": 0.764,
        "auprc": 0.373,
        "brier": 0.090,
        "logloss": 0.311,
    },
    {
        "task": "guo_icu",
        "reference": "tabular RandomForest + Platt",
        "auroc": 0.794,
        "auprc": 0.190,
        "brier": 0.038,
        "logloss": 0.150,
    },
])

numeric_reference_df = pd.DataFrame([
    {
        "task": "guo_readmission",
        "reference": "numeric sequence raw + RETAIN_lite_numeric",
        "auroc": 0.772,
        "auprc": 0.380,
        "brier": 0.089,
        "logloss": 0.307,
    },
    {
        "task": "guo_icu",
        "reference": "numeric sequence compressed_hybrid + GRU_2L_numeric",
        "auroc": 0.794,
        "auprc": 0.216,
        "brier": 0.038,
        "logloss": 0.158,
    },
])

display(pd.concat([tabular_reference_df, numeric_reference_df], ignore_index=True))

,task,reference,auroc,auprc,brier,logloss
0,guo_readmission,tabular HistGradientBoosting + Platt,0.764,0.373,0.090,0.311
1,guo_icu,tabular RandomForest + Platt,0.794,0.190,0.038,0.150
2,guo_readmission,numeric sequence raw + RETAIN_lite_numeric,0.772,0.380,0.089,0.307
3,guo_icu,numeric sequence compressed_hybrid + GRU_2L_nu...,0.794,0.216,0.038,0.158

## Главные выводы

1. Числовой сигнал присутствует примерно в 69–72% событий, так что он не маргинальный.
2. Для `guo_readmission` модели с числовыми признаками не показали явного улучшения по сравнению с предыдущим code-only sequence baseline. Лучшая числовая конфигурация была близка к code-only, но не превзошла лучший code-only `compressed_dedup + RETAIN_lite`.
3. Для `guo_icu` числовые sequence-модели существенно улучшились по сравнению с code-only sequence baseline. Лучшая конфигурация была `compressed_hybrid + GRU_2L_numeric`, с AUROC 0.794 и AUPRC 0.216.
4. Числовые sequence-модели почти догнали табличный ICU baseline по AUROC и превзошли его по AUPRC, но LogLoss остался немного хуже.
5. Compression по-прежнему снижает длину последовательности только незначительно, потому что большинство событий EHRSHOT — это измерения / числовые события, а не диагнозы.
6. Следующий шаг — комбинированная модель: табличные агрегированные признаки + sequence embedding.